### ISSUE TITLE
采用push方式进行消费时,是什么时候更新offset的?

### ISSUE THREAD

**Issue by zhenchuan** [alibaba/RocketMQ#104]
RT.

个人猜想应该是在 return ConsumeConcurrentlyStatus.CONSUME_SUCCESS; 后才更新的.

担心采用push方式时,如果出现异常会有数据丢失...

多谢

**Comment by diwayou** [comment]
你消费成功了，然后每10秒持久化一次消费的offset，也就是说有可能重复消费数据，因为你消费成功了的数据也有可能没有及时持久化offset
