### ISSUE TITLE
兼容性升级？

### ISSUE THREAD

**Issue by vongosling** [alibaba/RocketMQ#106]
3.2.5升级上来，接口MQPushConsumer方法registerMessageListener签名直接变成了下面两个子类，设计上要考虑下兼容

    @Override
    public void registerMessageListener(MessageListenerConcurrently messageListener) {
        this.messageListener = messageListener;
        this.defaultMQPushConsumerImpl.registerMessageListener(messageListener);
    }

    @Override
    public void registerMessageListener(MessageListenerOrderly messageListener) {
        this.messageListener = messageListener;
        this.defaultMQPushConsumerImpl.registerMessageListener(messageListener);
    }

**Comment by vintagewang** [comment]
:+1:
