### ISSUE TITLE
Is it possible to put english documentation?

### ISSUE THREAD

**Issue by vimalk78** [alibaba/RocketMQ#107]
the machine translation is never good enough, doesn't give confidence.

**Comment by vongosling** [comment]
Of course,can you introduce some use-cases for our rocketmq product?^_^

**Comment by naman-singhal** [comment]
@vongosling it would be great if you provide an english documentation, this project would be easier to use outside China then

**Comment by jbpin** [comment]
+1. It will be easier to jump in

**Comment by vongosling** [comment]
@jbpin  can you introduce some use-cases for our rocketmq ? or to say, you have making chosen between our product and other products(such as activemq ,rabbitmq or kafka)^_^

**Comment by jbpin** [comment]
@vongosling. Thanks for the reply. It's a general purpose. I'd like to try RocketMQ to see capabilities and if it suit our goals. But first It could be nice to have some docs to jump in and see what can do RocketMQ please.
