### ISSUE TITLE
消费偏移量出现远大于broker偏移量的情况

### ISSUE THREAD

**Issue by zhenchuan** [alibaba/RocketMQ#109]
如下,左边的是消费偏移量,右边的是我们统计的进度差.
暂时不明白这种情况出现的原因,属于偶尔发生事件....

消费方式为push,单个consumer ,
三个broker,其中两个broker的消费偏移量正常, 这是在另外一个broker发生的这样的问题 

![tmp1bf402c9](https://cloud.githubusercontent.com/assets/6836386/7878464/662a3b7e-0619-11e5-98d8-823530379549.png)

**Comment by vintagewang** [comment]
新版本会修复这个问题。

**Comment by zhenchuan** [comment]
多谢.能否告知一下时间点?
另外想确认的是,这个问题会不会影响broker的性能?

**Comment by vintagewang** [comment]
时间点暂时无法给出，请耐心等待。

**Comment by OlinaRuan** [comment]
@zhenchuan 这3个broker都是master吗？进度差在这里， 指的是consumer的broker的consume queue max offset - client consume queue max offset么？ 能否提供更多信息？

**Comment by zhenchuan** [comment]
一个月了还没修复么?今天又出问题了...

**Comment by yaoguangluo** [comment]
有个QQ群不错,服务器高手都在里面 id是 167461951

**Comment by lizhanhui** [comment]
@zhenchuan 你用的是哪个版本？ broker和Consumer都是3.2.6吗？

**Comment by icanfly** [comment]
这倒底是个什么问题，官方的能不能大概解释一下？或者简单提一个PR,　这个问题似乎已经出现一年多了，还没有修复，如果线上出现这种问题，岂不是让人抓狂，使用起来不放心呀

**Comment by BruceChoo** [comment]
没有时间更新开源代码，给出具体原因和修改办法也行，我们好自己改下

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
