### ISSUE TITLE
使用Flume消费RocketMq数据，没有生成offsets.json文件

### ISSUE THREAD

**Issue by lvjia** [alibaba/RocketMQ#117]
使用Flume作为RocketMq的消费者，在Flume没有停止的情况下，offsets.json文件一直没有生成，重启flume5~6次后生成offsets.json文件，这是为什么？
我使用的RocketMq版本3.2.6，通过log跟踪rocketmq-client部分的代码发现在调用LocalFileOffsetStore的persistAll方法时传入的参数mqs为null， 查看rocketmq_client.log日志发现这个警告 log.warn("doRebalance, {}, but the topic[{}] not exist.", consumerGroup, topic);

求解答

**Comment by vongosling** [comment]
please refer https://github.com/alibaba/RocketMQ/issues/108

**Comment by lvjia** [comment]
此问题已经解决，是rocketmq-flume-source插件bug
