### ISSUE TITLE
虚拟机老生代垃圾回收频繁出现

### ISSUE THREAD

**Issue by witaste** [alibaba/RocketMQ#119]
runbroker.sh JAVA_OPT 使用的是默认参数,broker运行过程中新生代垃圾回收次数较少，频繁出现老生代垃圾回收 cms gc ，并且老生代内存回收不掉。造成卡顿、消息发送失败。最终导致java heap 被占用完，broker 宕机。求教！

**Comment by Shawyeok** [comment]
通过threaddump查看当前有哪些线程正在运行, 重点看是否存在线程长时间阻塞
通过堆dump文件分析当前主要占用内存空间的对象是什么
请结合以上两种方式分析, 若堆内存较大, 可能其产生的dump文件分析, 尝试调低堆内存即可

希望对你有所帮助
