### ISSUE TITLE
请问RocketMQ如何做到分承租人订阅消息

### ISSUE THREAD

**Issue by shenzhenjia** [alibaba/RocketMQ#120]
请问RocketMQ如何做到分承租人订阅消息？
在saas中数据是按承租人分隔的，比如订单产生创建，如何配置RocketMQ可以让它只将对应承租人的订单消息通知递送给相应的承租人。

**Comment by shenzhenjia** [comment]
假设主题topic 是一个，比如order_created, 是不分承租人的

**Comment by tanweii163** [comment]
message设置tag,客户端根据tag自己区分
