### ISSUE TITLE
RocketMQ发送消息时，消息体太大，无法发送成功。

### ISSUE THREAD

**Issue by tianjixiaoying** [alibaba/RocketMQ#128]
RocketMQ发送消息时，消息体太大（8M大小），无法发送成功。
1.配置了maxMessageSize属性，若是值配的小点，就报超过消息规定大小 over max size
2.若是配置大点，就报错：不合法的消息,消息体大小not match。
请问各位，改怎么配置参数，配置哪些参数？求大神赐教。谢谢

**Comment by vongosling** [comment]
MQ不解决大文件消息，可以考虑发元信息，数据存储在FTP上
