### ISSUE TITLE
统计读取磁盘落后的情况，没有实现把？

### ISSUE THREAD

**Issue by vonzhou** [alibaba/RocketMQ#130]
// 统计读取磁盘落后情况
                                    if (diskFallRecorded) {
                                        diskFallRecorded = true;
                                        long fallBehind = consumeQueue.getMaxPhysicOffset() - offsetPy;
                                        brokerStatsManager.recordDiskFallBehind(group, topic, queueId,
                                            fallBehind);
                                    }

**Comment by vintagewang** [comment]
暂未实现。
