### ISSUE TITLE
Producer 配置createTopicKey后， No route info of this topic问题

### ISSUE THREAD

**Issue by xiongs** [alibaba/RocketMQ#133]
请教一下：为什么Producer 配置 createTopicKey后，发送消息时会报 No route info of this topic；发送消息时无论topic是否与createTopicKey 一致都会报错。如果createTopicKey不设置，随便写topic 发送消息都不会报错。

sh ./bin/mqbroker -m
namesrvAddr=
brokerIP1=192.168.10.69
brokerName=gn-web-dep
brokerClusterName=DefaultCluster
brokerId=0
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
rejectTransactionMessage=false
fetchNamesrvAddrByAddressServer=false
storePathRootDir=/app/gn_web_dep/store
storePathCommitLog=/app/gn_web_dep/store/commitlog
flushIntervalCommitLog=1000
flushCommitLogTimed=false
deleteWhen=04
fileReservedTime=72
maxTransferBytesOnMessageInMemory=262144
maxTransferCountOnMessageInMemory=32
maxTransferBytesOnMessageInDisk=65536
maxTransferCountOnMessageInDisk=8
accessMessageInMemoryMaxRatio=40
messageIndexEnable=true
messageIndexSafe=false
haMasterAddress=
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
cleanFileForciblyEnable=true

**Comment by vintagewang** [comment]
建议不要配置createTopic则个参数，服务器和客户端基于一个一致的默认参数。
