### ISSUE TITLE
 CODE: 14  DESC: service not available now, maybe disk full, CL:  0.91 CQ:  0.91 INDEX:  0.91, maybe your broker machine memory too small.

### ISSUE THREAD

**Issue by mushroom1113** [alibaba/RocketMQ#134]
CODE: 14  DESC: service not available now, maybe disk full, CL:  0.91 CQ:  0.91 INDEX:  0.91, maybe your broker machine memory too small.

**Comment by vintagewang** [comment]
磁盘超过90%， 会拒绝服务。可以清除一些磁盘数据试下。

**Comment by mushroom1113** [comment]
嗯嗯，貌似是这个问题，在修改，谢谢

**Comment by olddoor** [comment]
学会修改store的位置会更好
