### ISSUE TITLE
hashmap未同步

### ISSUE THREAD

**Issue by brucechan0921** [alibaba/RocketMQ#137]
https://github.com/alibaba/RocketMQ/blob/master/rocketmq-broker/src/main/java/com/alibaba/rocketmq/broker/client/ProducerManager.java

    public HashMap<String, HashMap<Channel, ClientChannelInfo>> getGroupChannelTable() {
        HashMap<String /* group name */, HashMap<Channel, ClientChannelInfo>> newGroupChannelTable =
                new HashMap<String, HashMap<Channel, ClientChannelInfo>>();
        try {
            if (this.groupChannelLock.tryLock(LockTimeoutMillis, TimeUnit.MILLISECONDS)){
                try {
                    newGroupChannelTable.putAll(groupChannelTable);
                } finally {
                    groupChannelLock.unlock();
                }
            }
        } catch (InterruptedException e) {
           log.error("",e);
        }
        return newGroupChannelTable;
    }

HashMap(Channel, ClientChannelInfo) 未复制，而是直接被暴露出去，会被ProducerManager进行迭代，需要复制

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
