### ISSUE TITLE
MessgeExt中的reconsumeTimes(消息被某个订阅组重新消费了几次概念问题)

### ISSUE THREAD

**Issue by zhongfuhua19** [alibaba/RocketMQ#139]
在MessgeExt消息体里面有个消息被某个订阅组重新消费了几次的字段(reconsumeTimes)
1、所谓重新消费是个怎样的概念，是回退某一个点的消费进度，再pull或push这个进度后的消息都算重新消费么？
2、reconsumeTimes 是某个订阅组重新消费次数，而MessageExt通过producer查询消息时，查询时没有任何地方指定consumerGroup，那么查出来的reconsumeTimes是哪个消费组的。还是说只能通过consumer来查询消息时 这个reconsumeTimes才算有效？

**Comment by vongosling** [comment]
in CLUSTERING mode,failed consume when you call MessageListenerConcurrently,this value +1
