### ISSUE TITLE
rocketmq-client-3.2.6 生产者发送消息递归死循环问题

### ISSUE THREAD

**Issue by xiaolezheng** [alibaba/RocketMQ#140]
类：com.alibaba.rocketmq.client.producer.DefaultMQProducer 

下面方法死循环，应该是疏忽导致的，直接请求 DefaultMQProducerImpl 对应方法即可
@Override
    public void send(Message msg, MessageQueue mq, SendCallback sendCallback) throws MQClientException,
            RemotingException, InterruptedException {
        send(msg, mq, sendCallback);
    }

**Comment by lizhanhui** [comment]
3.2.6 有这个问题

**Comment by lizhanhui** [comment]
@xiaolezheng 你可以弄个pull request
