### ISSUE TITLE
如何删除已消费的消息

### ISSUE THREAD

**Issue by jingbing** [alibaba/RocketMQ#146]
我使用的是顺序消息，消费之后想把消息删除，以免占用空间或内存，请问该如何操作。

**Comment by csiVictor** [comment]
rocketMQ根据配置的文件保留时间、占用内存大小等自动删除

**Comment by baijunhong** [comment]
在那个配置文件上可以看到，因为现在我的broker占用内容一点一点的增加，不见减少。

**Comment by sunnyhcw** [comment]
举例：rocketmq/conf/2m-noslave/broker-a.properties 文件里面有配置：
deleteWhen=04

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
