### ISSUE TITLE
集群消费模式下，消息不能轮询到每个Consumer下

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/RocketMQ#147]
JSTORM集群对接RocketMQ。如果有4个以上的Consumer，只有其中某4个Consumer可以收到消息（这4个是轮询方式），其它的Consumer完全收不到信息

**Comment by lizhanhui** [comment]
是不是你Queue的个数就是4？

**Comment by xiaoyao2102** [comment]
楼上说得对。。题主小白了。。
