### ISSUE TITLE
集群消费模式下，同一consumerGroup在同一容器中多次消费的问题

### ISSUE THREAD

**Issue by iamchenney** [alibaba/RocketMQ#157]
现象：
集群消费模式，在同一tomcat中启动2个consumerGroupName="consumer_group"的web应用，订阅相同topic消息后，每条消息都会收到2次，启动3个，则每条消息会收到3次，在不同tomcat中分别启动则只有一个应用可以收到消息。
不知这算不算bug,还是设计如此？如果设计如此，如何在同一容器中不收到重复消息？
现在发现，如果在同一tomat中启动多个，有可能收不到消息，如果收到就同时收到多个

**Comment by shaozhengmao** [comment]
遇到了相同的问题

**Comment by lizhanhui** [comment]
通过setInstanceName， 给每个client实例set不同的名字， 就可以了。

**Comment by Jaskey** [comment]
```
    public void changeInstanceNameToPID() {
        if (this.instanceName.equals("DEFAULT")) {
            this.instanceName = String.valueOf(UtilAll.getPid());
        }
    }
```

在不设置instanceName的情况下，会被动态改为进程号，所以在同一个进程里面启动多个consumer会认为是同一个实例。

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
