### ISSUE TITLE
主从broker的配置问题

### ISSUE THREAD

**Issue by ronyongxian** [alibaba/RocketMQ#158]
两台broker ，一主一从，试验主broker宕机后，从broker可以接替运行。客户端开始发送和订阅，中途shell停掉主broker，客户端日志先报主broker connect faied，再报No route info of this topic，观察从的TPS和offset，都是0

这是我的主从配置，
主：brokerName=app98 brokerId=0 brokerRole=SYNC_MASTER
从：brokerName=app98 brokerId=1 brokerRole=SLAVE

请问是否配置错误？

**Comment by asdr14** [comment]
@ronyongxian 这样配置应该是没错的吧
