### ISSUE TITLE
netty版本问题

### ISSUE THREAD

**Issue by qushiw** [alibaba/RocketMQ#159]
我的项目中同时使用netty5.0和rocketMQ3.2.6，但是rocketMQ本身使用的是netty4.0.25，所以导致netty版本冲突，请问如何解决

**Comment by Lihuanghe** [comment]
https://github.com/Lihuanghe/RocketMQ/tree/useNetty5?files=1

**Comment by vongosling** [comment]
参考https://github.com/alibaba/RocketMQ/pull/148
