### ISSUE TITLE
rocketmq3.26.版本关于pushConsumer的消费位点重置的最佳实践是什么？

### ISSUE THREAD

**Issue by solomonqbq** [alibaba/RocketMQ#163]
如题，我做了两种尝试：
第一：在启动时设置
consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_TIMESTAMP);
consumer.setConsumeTimestamp("20151015161000");
但似乎没生效，我感觉pushConsumer是在RebalancePushImpl里算出位点通过心跳来通知broker变更位点的（不是很确定），但是RebalancePushImpl的128-132行似乎根本走不到，也就没法重置位点。

第二：尝试运行期通过offsetStore强制重置位点
long timestamp =  UtilAll.parseDate("20151015161000", UtilAll.yyyyMMddHHmmss).getTime();
        consumer.setOffsetStore(new RemoteBrokerOffsetStore(MQClientManager.getInstance().getAndCreateMQClientInstance(consumer), consumer.getConsumerGroup()));
        consumer.start();
        synchronized (consumer){
            for (MessageQueue mq:consumer.fetchSubscribeMessageQueues("BenchmarkTest")){
                long offset = consumer.searchOffset(mq,timestamp);
                consumer.getOffsetStore().updateOffset(mq,offset,false);
                consumer.getOffsetStore().persist(mq);
            }
        }
似乎能重置，但是每次消费的数量总是不同，这段期间肯定没有新数据，数据消费的条数应该是一样的才对，这是为什么？

**Comment by zhaoshunxin** [comment]
![image](https://cloud.githubusercontent.com/assets/16201489/12372297/1219039c-bc8c-11e5-84fc-bfe54a0bb3d9.png)
您好您见过这样的情景吗？retry那个一直在接收数据

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
