### ISSUE TITLE
bug：broker删除过期文件之后，造成死循环，无线打印错误日志，offset无法自动调整成正常值

### ISSUE THREAD

**Issue by lwclover** [alibaba/RocketMQ#164]
15-10-15 19:47:08 WARN PullMessageThread_38 - findMapedFileByOffset offset not matched, request Offset: 53406511739, index: -262, mapedFileSize: 1073741824, mapedFiles count: 25, StackTrace: 
        java.lang.Thread.getStackTrace(Thread.java:1479)
        com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
        com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
        com.alibaba.rocketmq.store.CommitLog.getMessage(CommitLog.java:680)
        com.alibaba.rocketmq.store.DefaultMessageStore.getMessage(DefaultMessageStore.java:540)
        com.alibaba.rocketmq.broker.processor.PullMessageProcessor.processRequest(PullMessageProcessor.java:290)
        com.alibaba.rocketmq.broker.processor.PullMessageProcessor.processRequest(PullMessageProcessor.java:80)
        com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:172)
        java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        java.util.concurrent.FutureTask.run(FutureTask.java:138)
        java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        java.lang.Thread.run(Thread.java:662)

**Comment by bwzhang2011** [comment]
any update with such issue ?

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
