### ISSUE TITLE
能否提供一些协议相关的文档，好方便制作多语言的producer和consumer

### ISSUE THREAD

**Issue by JacksonTian** [alibaba/RocketMQ#166]
RT.

**Comment by vongosling** [comment]
顺着RemotingCommand这个类，reference一下，Ｏ（∩＿∩）Ｏ～目前相关文档还在整理中。。。。。

**Comment by XadillaX** [comment]
还没整理好么 -。 -

**Comment by vongosling** [comment]
please refer https://github.com/alibaba/RocketMQ/issues/353
