### ISSUE TITLE
对于%DLQ%的消息大家是如何查看以及如何处理的？

### ISSUE THREAD

**Issue by yanfeipeng** [alibaba/RocketMQ#170]

**Comment by zhaoshunxin** [comment]
请问你的问题解决了吗?

**Comment by yanfeipeng** [comment]
@zhaoshunxin 
%DLQ%的消息是存储的是超过重试消费次上限的消息。
它本身就是一个队列，但是由于只有写的权限无法被读取。
只要把队列的权限增加读就可以读取展示，这样就可维护管理。
