### ISSUE TITLE
BUG 发送消息时出现超时失败但不再重试

### ISSUE THREAD

**Issue by Shawyeok** [alibaba/RocketMQ#173]
我的部署结构是:
三台broker全为主, 三台nameserver, 每台机器上部署一个namesrv和一个broker
RocketMQ版本: 
3.0.7

线上一台机器系统崩溃, 发消息时出现MQClientException: Retry many times, still failed, 2分钟后恢复正常, 消息发送大约失败了2000条, 查看源码了解其重试机制时发现如下代码:
```java
for (int times = 0; times < timesTotal
                    && (endTimestamp - beginTimestamp) < this.defaultMQProducer.getSendMsgTimeout(); times++) {
// from DefaultMQProducerImpl
```
大致意为超时异常不做重试处理, 又看了github上最新的版本代码, 如下:
```java
final long maxTimeout = this.defaultMQProducer.getSendMsgTimeout() + 1000;
for (; times < timesTotal && (endTimestamp - beginTimestamp) < maxTimeout; times++) {
// from DefaultMQProducerImpl
```
我理解为在默认超时时间3000ms情况下, 允许一次发消息超时错误后重发消息, 但是, 我的问题是如果刚好三台机器中有两台崩溃了(集群任然可用), 这里就会放弃重试而抛出异常了
我想能不能将这种情况默认交给后台线程(mqclient内部线程)来处理?

**Comment by vongosling** [comment]
很明显，目前超时是由次数和时间共同决定的。关于这块的设计，在分布式里面有个叫backoff原则，建议你了解下。目前RMQ没有发送端异步重试机制（后续会有，需要期待一下，＾＿＾），所以从更高HA的角度来看，你需要自己实现。
