### ISSUE TITLE
消息重复消费

### ISSUE THREAD

**Issue by yxt1019** [alibaba/RocketMQ#174]
某一个queueId的offset值consumer端和broker中保存的offset不一致，导致重复消费。

broker日志：
the request offset: 14568 too small, broker min offset: 32831, consumer: ***
PULL_OFFSET_MOVED:

client日志：
WARN PullMessageServiceScheduledThread - fix the pull request offset, PullRequest

**Comment by zhaoshunxin** [comment]
您好，我这边老是出现RETRY 的topic 与broker的offset相差很多，请问您的问题解决了吗？

**Comment by lizhanhui** [comment]
应该是bug https://github.com/alibaba/RocketMQ/issues/109 触发了

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
