### ISSUE TITLE
异步存放，大并发，目前同样配置测试到不同云主机跑性能不同

### ISSUE THREAD

**Issue by byebye758** [alibaba/RocketMQ#177]
532549992@qq.com
应用物联网项目，处于学习阶段，目前测试同样配置在测试机 4核心 16G内存跑到 1W 并发 异步模式
不过更换为  各种云提供机器 最高跑到4万 不明所以，请帮忙提供文档，非常感谢

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
