### ISSUE TITLE
如何查看某一个消息被哪个消费者消费

### ISSUE THREAD

**Issue by chinaccj** [alibaba/RocketMQ#181]
开发测试的时候，发了消息，，但是消费者没有收到，，
不知道被谁消费掉了，，，，
通过 ./mqadmin queryMsgById   只能查到，消息的生产者的ip，，查不到消费者的ip，，，

**Comment by huapuyu** [comment]
同问

**Comment by Lihuanghe** [comment]
这个可能得不到。据我所知，mq只记录每个消费者当前的msgOffset。 mq服务器只知道哪个消费者消费到哪个位置了，只有消费者自己才知道自己消费了哪些消息，及消息内容。而且一个msg可能被多个消费者消费，没办法把所有的消费者IP记下来。
mq服务器可以认为超过offset的消息都被消费了。 想知道服务器给消费者发了哪些消息只能看日志了（还不知道有没有记录）。
