### ISSUE TITLE
使用producer时，当消息速度达到5w/s，每次ParNew的GC后，old区域都有明显增长，请问有优化办法吗？

### ISSUE THREAD

**Issue by cavinyang** [alibaba/RocketMQ#185]
您好：
        我服务端使用1个broke， produer使用sendOneway 方式，producer.setSendMsgTimeout(6000); 其他地方都是默认配置。
        非常期待解答，谢谢！

**Comment by lizhanhui** [comment]
From/To区太小了， 短命对象被迫提前promote到old区了。试试增大堆内内存大小， 尤其是Eden区。

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
