### ISSUE TITLE
集群消费模式下消费速度的问题

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/RocketMQ#189]
我这里是用RocketMQ和JSTORM配合使用的。性能调优的时候做了这么一个实验。
固定相同的数据量（比如说10W数据），硬件、NameServer、Broker和Producer数量也都是不变的。
然后对应开启不同数量的Consumer。
结果发现Consumer数量和消费时间是正相关的，即Consumer数量越多消费时间越长。
开始的时候以为是业务逻辑拖慢了消费速度，去掉逻辑后只保留RocketMQ和JSTORM框架重复上面的实验也有相同的现象，然后再去掉JSTORM框架只保留RocketMQ还是有同样的现象。

请问这样的情况是正常现象么？如果不是，应该如何解决？

**Comment by newjunwei** [comment]
卧槽。求解答

**Comment by xiaoyao2102** [comment]
其实道理挺简单的，我后来又做了下面一个试验。
只保留RocketMQ，在Consumer端我阻塞线程10s（即每消费一条消息需要10s），Producer端用一个for循环来发送消息，并且只发送21条消息（选21是因为每个Consumer实际上对应了20个线程来消费）。
1Consumer的情况下，消费21条需要20s
2Consumer的情况下，消费21条需要10s

2Consumer比1Consumer消费速度快的原因显然是因为同时有40个线程来接收消息，而1Consumer只有20个线程。
我认为可以得出结论，在压力一定的情况下，多个Consumer还是消费得更快的。
至于之前最开始看到的现象，我想应该是由于入口处压力不够大的原因（生产者只有一个线程for循环发送消息，消费者仅仅有一个打印的操作，几乎不消耗时间，造成了消费速度比生产快的情况），所以在后来的试验中，我强行降低了消费速度，这样多Consumer的效果就显示出来了。

**Comment by yanfeipeng** [comment]
还有topic队列数的因素在里面，不是consumer越多消费越快的。官方文档上说明得很清楚comsumer与消费队列的关系。

**Comment by gaoyf** [comment]
> 选21是因为每个Consumer实际上对应了20个线程来消费

这句话说的不对，很显然，你没有设置consumeMessageBatchMaxSize，这个参数默认是1，即你一批要消费多少个消息。
默认消费的线程池确实为20，使用了阻塞无界队列，所以第21个消息会放到队列里等着，这样前20条消息需要10s，第21条也需要10s。
两个consumer的情况下，消息被均分消费，所以一共用了10s

假设你设置了consumeMessageBatchMaxSize为40，那么21条消息其实只用一个线程消费，照样是10s

消费速度其实跟你如何消费消息是相关的，比如存到数据库，取决于数据库的速度。
当然也更多少个线程，每个线程消费多少个消息相关

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
