### ISSUE TITLE
您好，请问这样的情景怎么处理？谢谢

### ISSUE THREAD

**Issue by zhaoshunxin** [alibaba/RocketMQ#194]
![image](https://cloud.githubusercontent.com/assets/16201489/12372303/454d94b2-bc8c-11e5-8096-6a9e80a33d89.png)

RETRY那个一直在接收数据。

**Comment by lizhanhui** [comment]
在消费接口， 你应该返回CONSUME_LATER或者抛异常了。

**Comment by zhaoshunxin** [comment]
您好非常感谢您的回复。
还有一个问题就是 消费端consume的返回 Action.CommitMessage 有时间限制吗？ 如果有多长时间不返回服务器认为是消费失败重新发起呢？谢谢

**Comment by lizhanhui** [comment]
当前没限制。

**Comment by zhaoshunxin** [comment]
好的 谢谢

**Comment by yezim** [comment]
您好，请问一下这个web页面怎么打开呢？ @zhaoshunxin
