### ISSUE TITLE
多网卡机器消费者数据接收不到问题

### ISSUE THREAD

**Issue by yijia52** [alibaba/RocketMQ#196]
问题描述
=======

* rocket mq对应的机器有两张网卡，IP分别对应为A 和 B
*  nameserver 在IP A启动，broker也在IP A启动

* 消费者集群欲消费mq中的数据，但__只能ping 通B__，__不能ping通A__
* 消费者集群与MQ集群相互独立，互不影响。

目前情况
========
* 在消费者集群用printMsg命令，`sh mqadmin printMsg -n IP-B:9876 -t Topic `可以打印数据
* 在消费者集群，启动consumer程序，同样连接IP-B，push consumer，不能消费到数据

求助问题
========
* 是否能因此断定数据接收不到的原因是MQ多网卡问题？

谢谢

**Comment by Lihuanghe** [comment]
你的A卡跟Consumer集群不通为什么要把namesvr和broker都绑定在A上?
应该绑定在B卡上。

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
