### ISSUE TITLE
设置延时消费，超过5秒，发送MQ消息异常.

### ISSUE THREAD

**Issue by hongwei24** [alibaba/RocketMQ#198]
System.currentTimeMillis()+delayConsumerTime * 1000

设置延时消费，超过5秒，发送MQ消息异常.

[ // 如果设置了延时发送时间，则延时发送 if (mqmessage.getStartDeliverTime() > 0) { m.setStartDeliverTime(mqmessage.getStartDeliverTime()); } ]
异常信息：
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 4 DESC: not set any response code
For more information, please visit the url, #48

RemotingCommand [code=4, language=JAVA, version=112, opaque=4160, flag(B)=1, remark=not set any response code, extFields={}]

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
