### ISSUE TITLE
这个依赖的jar包，有谁下载不了的吗

### ISSUE THREAD

**Issue by zcgewu** [alibaba/RocketMQ#200]
Failed to execute goal on project rocketmq-tools: Could not resolve dependencies for project com.alibaba.rocketmq:rocketmq-tools:jar:3.2.6: Failed to collect dependencies at org.kohsuke:github-api:jar:1.59 -> com.infradna.tool:bridge-method-annotation:jar:1.12 -> org.jenkins-ci:annotation-indexer:jar:1.4: Failed to read artifact descriptor for org.jenkins-ci:annotation-indexer:jar:1.4: Failure to find org.jenkins-ci:jenkins:pom:1.26

**Comment by zcgewu** [comment]
临时这么处理啦
<dependency>
	<groupId>org.kohsuke</groupId>
	<artifactId>github-api</artifactId>
	<version>1.59</version>
	<exclusions>
		<exclusion>
		      <groupId>com.infradna.tool</groupId>
		      <artifactId>bridge-method-annotation</artifactId>
		</exclusion>
	</exclusions>
</dependency>

**Comment by zcgewu** [comment]
临时这么处理啦
<dependency>
			<groupId>org.kohsuke</groupId>
			<artifactId>github-api</artifactId>
			<version>1.59</version>
			<exclusions>
				<exclusion>
					<groupId>com.infradna.tool</groupId>
					<artifactId>bridge-method-annotation</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by zcgewu** [comment]
排除了bridge-method-annotation依赖jar包，会对rocketmq的业务代码有响应吗？

**Comment by eagle8625** [comment]
配置maven的.setting中的repository url: <url>http://maven-repository.com/artifact/</url>  ，用这个可以下载所有的依赖包。
