### ISSUE TITLE
在阿里云上部署RMQ多网卡问题

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/RocketMQ#203]
由于阿里云上包括外网IP和内网IP，我在阿里云上部署了RocketMQ后，从Console看到Broker的地址显示为外网地址。
那么在发消息的时候，数据走的是外网网卡吗？如果是的话，如何设置为内网地址？

**Comment by eagle8625** [comment]
看过那个绑定IP的代码，应该是随机选择一个非本地的地址，好像代码写死了e


发自 网易邮箱大师
On 02/18/2016 11:23, xiaoyao2102 wrote:

由于阿里云上包括外网IP和内网IP，我在阿里云上部署了RocketMQ后，从Console看到Broker的地址显示为外网地址。
那么在发消息的时候，数据走的是外网网卡吗？如果是的话，如何设置为内网地址？

**Comment by gaoyf** [comment]
启动时可以指定配置文件
brokerIP1=内网ip
brokerIP1解释：
本机 IP 地址，默认系统自动识别，但是某些多网卡机器会存在识别错误的情况，这种情况下可以人工配置

**Comment by xiaoyao2102** [comment]
感谢两位的回答！
gaoyf的答案可以解决问题，在properties里配上brokerIP1就行了
