### ISSUE TITLE
创建topic时指定writeQueueNums和readQueueNums的用处？

### ISSUE THREAD

**Issue by gaoyf** [alibaba/RocketMQ#204]
如果writeQueueNums和readQueueNums不相等，经过测试(只针对集群模式)，假设writeQueueNums=6，readQueueNums=3，那么每个broker上有3个queue的消息将无法消费，不知道为啥这里这么设计？

**Comment by gaoyf** [comment]
rocketmq不是淘宝孵化的顶级项目吗？看目前的状况开源版本不更新了啊？

**Comment by vintagewang** [comment]
@gaoyf 这个是为扩缩容设计的。特别在做顺序消息的扩缩容时，会用到这个配置。

**Comment by markray** [comment]
@vintagewang  我也对这个问题很疑问，搜了很多资料，也没有很清楚的说明白，能简单介绍下扩缩容时如何用writeQueueNums和readQueueNums吗？

**Comment by liuylmr** [comment]
为什么没有人认真的回答下这个问题

**Comment by lizhanhui** [comment]
@markray Answer to existing issue has already covered this info. Make sure you have checked existing Q&A issues.
