### ISSUE TITLE
创建topic时，hasUnitSub，unit和order这几个参数有什么作用，谢谢！

### ISSUE THREAD

**Issue by huapuyu** [alibaba/RocketMQ#206]
usage: mqadmin updateTopic [-b <arg>] [-c <arg>] [-h] [-n <arg>] [-o <arg>] [-p <arg>] [-r <arg>] [-s <arg>]
       -t <arg> [-u <arg>] [-w <arg>]
 -b,--brokerAddr <arg>       create topic to which broker
 -c,--clusterName <arg>      create topic to which cluster
 -h,--help                   Print help
 -n,--namesrvAddr <arg>      Name server address list, eg: 192.168.0.1:9876;192.168.0.2:9876
 -o,--order <arg>            set topic's order(true|false
 -p,--perm <arg>             set topic's permission(2|4|6), intro[2:R; 4:W; 6:RW]
 -r,--readQueueNums <arg>    set read queue nums
 -s,--hasUnitSub <arg>       has unit sub (true|false
 -t,--topic <arg>            topic name
 -u,--unit <arg>             is unit topic (true|false
 -w,--writeQueueNums <arg>   set write queue nums

创建和更新topic时，hasUnitSub，unit和order这几个参数不知道有什么作用，咨询下，谢谢！

**Comment by vongosling** [comment]
ignore ,logic can be remove in future
