### ISSUE TITLE
同一台机器上部署主备双机，一台master，一台slave，slave一直没数据

### ISSUE THREAD

**Issue by fanvan** [alibaba/RocketMQ#208]
我两个broker是部署到同一台机器上的，slave一直没数据的生成

#master的配置文件
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=SYNC_MASTER
flushDiskType=SYNC_FLUSH
listenPort=10912
storePathCommitLog=e:/store-m/commitlog
storePathConsumeQueue=e:/store-m/consumequeue
storePathIndex=e:/store-m/index
storeCheckpoint=e:/store-m/checkpoint
abortFile=e:/store-m/abort

#slave的配置文件
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=1
deleteWhen=04
fileReservedTime=48
brokerRole=SLAVE
flushDiskType=SYNC_FLUSH
listenPort=10913
storePathCommitLog=e:/store-s/commitlog
storePathConsumeQueue=e:/store-s/consumequeue
storePathIndex=e:/store-s/index
storeCheckpoint=e:/store-s/checkpoint
abortFile=e:/store-s/abort

而且很奇怪，先启动master，再启动slave会报端口占用，反过来就不会

**Comment by gaoyf** [comment]
参见我这篇文章，有介绍： HAPort：默认采用broker启动时监听的端口+1来作为HA端口 
rocketmq3.26研究之一存储层
http://blog.csdn.net/a417930422/article/details/50606732

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
