### ISSUE TITLE
无法关闭broker自动创建topic

### ISSUE THREAD

**Issue by huapuyu** [alibaba/RocketMQ#209]
rocketmq的broker参数autoCreateTopicEnable，我设为false，不自动创建topic，但是以下代码还是可以自动创建新的topic，这是rocketmq的bug，还是我理解不对，望大家赐教？谢谢！

//topic-20160304-55 是一个新的topic
Message message = new Message("topic-20160304-55", "push", "1", "hello world1".getBytes());
SendResult result = producer.send(message);

**Comment by gaoyf** [comment]
3.26不会自动创建，你用的版本是啥？

**Comment by huapuyu** [comment]
3.2.6，不过我后来发现需要删除TBW102这个默认topic，默认情况，rmq自动创建topic和消费组，也会创建tbw102这个topic，就算你关闭自动创建topic和消费组功能，由于存在tbw102这个topic，还是会自动创建topic，所以需要删除TBW102这个默认topic
