### ISSUE TITLE
同一group下两个consumer订阅不同topic，会导致这些consumer漏掉订阅的消息

### ISSUE THREAD

**Issue by newjunwei** [alibaba/RocketMQ#212]
同一group下两个consumer订阅不同topic，会导致这些consumer漏掉订阅的消息。

**Comment by lizhanhui** [comment]
同一group下两个consumer订阅情况应该一致。 你用法不对。

**Comment by gaoyf** [comment]
这个我之前测试过，参见我这篇文章：
rocketmq问题汇总-一个consumerGroup只对应一个topic
http://blog.csdn.net/a417930422/article/details/50663639

**Comment by yanfeipeng** [comment]
主要是订阅关系由于定时的更新，不断改变导致。

**Comment by Jaskey** [comment]
一个group只能订阅一样的topic的话，在灰度发布时，需要动态监听/去监听某些topic,这种场景下rocketMQ有什么好的方案？ @lizhanhui

**Comment by yanfeipeng** [comment]
@Jaskey #5 
也有相关的一些讨论。
这方面的确是一个麻烦。

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
