### ISSUE TITLE
设置延时消费，有时收不到消息

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/RocketMQ#213]
我这里RocketMQ最近有这么个现象，在设置了延时消费比如30s或者1m，Producer端有SendResult发送成功的打印，但是Consumer端迟迟收不到消息。
如果把延时设置为10s以下，那么又可以正常收发消息。

请问大牛这种情况是什么原因造成的？延时消费的原理又是怎样的？

目前倒是有一个粗暴的办法可以解决这个问题，就是把MQ在/root/store的文件夹删除然后重启MQ。

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
