### ISSUE TITLE
运行Examples里面的ordermessage，可以解释一下想演示什么吗？

### ISSUE THREAD

**Issue by tiger822** [alibaba/RocketMQ#215]
producer里面的
SendResult sendResult = producer.send(msg, new MessageQueueSelector() {
                    @Override
                    public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
                        Integer id = (Integer) arg;
                        int index = id % mqs.size();
                        return mqs.get(index); //选择消息队列？ 有什么用呢？
                    }
  }, orderId);

consumer里面的：
consumer.registerMessageListener(new MessageListenerOrderly() {
            AtomicLong consumeTimes = new AtomicLong(0);

            @Override
            public ConsumeOrderlyStatus consumeMessage(List<MessageExt> msgs, ConsumeOrderlyContext context) {
                context.setAutoCommit(false);
                System.out.println(Thread.currentThread().getName() + " Receive New Messages: " + msgs);
                this.consumeTimes.incrementAndGet();
                if ((this.consumeTimes.get() % 2) == 0) {
                    return ConsumeOrderlyStatus.SUCCESS;
                }
                else if ((this.consumeTimes.get() % 3) == 0) {
                    return ConsumeOrderlyStatus.ROLLBACK;
                }
                else if ((this.consumeTimes.get() % 4) == 0) {
                    return ConsumeOrderlyStatus.COMMIT;
                }
                else if ((this.consumeTimes.get() % 5) == 0) {
                    context.setSuspendCurrentQueueTimeMillis(3000);
                    return ConsumeOrderlyStatus.SUSPEND_CURRENT_QUEUE_A_MOMENT;
                }

                return ConsumeOrderlyStatus.SUCCESS;
            }
        });

能解释一下返回不同状态后的区别是什么？（回接着发生什么事？）

**Comment by yanfeipeng** [comment]
rmq实现消息按顺序发送的的功能是通过Topic的同一队列顺序插入消息完成的。例子中提到select queue就是为了让客户端实现这个选择。比如说，你某个订单号的所有消息通过mod后得到一个下标，之后的这个订单相关的消息都是通订单号去路由同一个队列，则可以完成消息的顺序性。
由于顺序消息队列要保证每个消息必须消费成功后才能消费下一个，状态的返回就是为了让你在消费过程中出现异常选择如何处理。
