### ISSUE TITLE
如何使用MQ模拟“A发起支付并等待－〉B支付－〉A收到成功支付信息并退出”

### ISSUE THREAD

**Issue by tiger822** [alibaba/RocketMQ#216]
如题，如何让producer等待并获取B返回的支付状态？

**Comment by ambauerbauer** [comment]
Hi,您好。

这个问题的场景类似于A直接通过RPC调用B， 您是出于什么考虑选择用MQ实现，而不是选择一个RPC框架来做，例如Dubbo

**Comment by tiger822** [comment]
@ambauerbauer 剛涉足於這方面，沒什麼基礎，如果像支付寶這種能應對海量並發的支付流程，我覺得用MQ也適合（即使排隊兩三秒亦能接受吧），但前提是這個MQ中間件必須可靠，不漏發、重發。

關於您提到的Dubbo，是實時傳遞的吧？能否應對海量並發的需求？

**Comment by vongosling** [comment]
请入QQ交流群聊

**Comment by yezim** [comment]
@vongosling 请问交流群号是多少？
