### ISSUE TITLE
producer端如何进行广播？

### ISSUE THREAD

**Issue by tiger822** [alibaba/RocketMQ#217]
有没有特定的广播命令？

**Comment by gaoyf** [comment]
看来你对rocketmq还不了解，广播是对消费者来说的，消费时指定为集群消费或非集群消费
参见com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.setMessageModel(MessageModel messageModel)

**Comment by wenxzhen** [comment]
默认情况下面，如果不指定MessageModel,那么应该是集群消费的模式。但l是我看到一个现象实，不同进程的DefaultMQPushConsumer，订阅了相同的Topic和Tags, 竟然同时消费同一条消息，问题是还有什么因素起作用？

**Comment by gaoyf** [comment]
DefaultMQPushConsumer指定的consumer group是否一致？

**Comment by wenxzhen** [comment]
如果Group名不一致，会有这种问题？我看了Best Practice, 已经改成一致

**Comment by kaybinwong** [comment]
Group不一致肯定会重复消费的
