### ISSUE TITLE
事务消息  LocalTransactionState.UNKNOW  状态下不回查

### ISSUE THREAD

**Issue by sunxueye** [alibaba/RocketMQ#221]
当提交本地事务的时候,事务的状态为未知的情况下，注册的 TransactionCheckListener 并没有接收到broker的回查请求。后来查看了源码,版本 3.2.6  broker 的 Broker2Client类的回查方法 checkProducerTransactionState 没有客户端调用，没有任何的服务线程或者对象去主动调用这个方法，
这个事务消息的回查机制是如何使用的,现在只要是未知事务状态的消息,都一直在本地事务表里

**Comment by suihanyou** [comment]
这部分内容，还没有开源，所以现在的版本压根就没有这个功能。要使用这个功能，遥遥无期

**Comment by sunxueye** [comment]
谢谢 已经在 之前的 issues中发现了
