### ISSUE TITLE
DispatchMessageService的volatile疑问

### ISSUE THREAD

**Issue by brucechan0921** [alibaba/RocketMQ#225]
https://github.com/alibaba/RocketMQ/blob/master/rocketmq-store/src/main/java/com/alibaba/rocketmq/store/DefaultMessageStore.java

class DispatchMessageService 

private volatile List<DispatchRequest> requestsWrite;
private volatile List<DispatchRequest> requestsRead;

这2个使用volatile是否必要？ DispatchMessageService里必要的地方都使用synchronized

**Comment by vongosling** [comment]
do we need to make some field volatile?.may be some prior discuss(http://stackoverflow.com/questions/29404851/do-we-need-to-make-concurrenthashmap-volatile,http://stackoverflow.com/questions/3668462/what-does-using-volatile-when-using-a-java-util-concurrent-concurrent-container) can give you advice.

**Comment by brucechan0921** [comment]
你好：

实际上，你发的链接没有看到实质性东西，还请详细指出。

我认为，volatile 和 synchronized在内存可见性上是一致的，都提供 锁的释放 和 获取 的语义。
