### ISSUE TITLE
3.4.9 在哪

### ISSUE THREAD

**Issue by ddatsh** [alibaba/RocketMQ#228]
maven中央库看见版本已经到了3.4.9
试了发MQ会报错 ，看会往 10909端口发送
3.4.6还可以

**Comment by bwzhang2011** [comment]
@ddatsh, 已经看到了，不过请注意看一下其中的POM
modules>
<module>rocketmq-client</module>
<module>rocketmq-common</module>




<module>rocketmq-remoting</module>



</modules>

也就是这个版本只涉及到  rocketmq-common/remoting/client 这几个组件版本的变动（后续看一下source jar，对比一下变动）

**Comment by vongosling** [comment]
后续会有新版本发布

**Comment by bwzhang2011** [comment]
@vongosling, 期待相关版本发布。

**Comment by bwzhang2011** [comment]
@vongosling, 已到5月了，新版本大概什么时候会公布（修复了哪些ISSUE，MQTT会提供支持否）

**Comment by bwzhang2011** [comment]
@vongosling, any update with such issue ?

**Comment by bwzhang2011** [comment]
@vongosling, 注意到3.5.2都已经发布了，但是开源这边迟迟还没有同步更新任何版本。请问什么时候能够合并上述改动啊
