### ISSUE TITLE
eclipse集成rocketmq客户端，运行起来日志输出地址不能改

### ISSUE THREAD

**Issue by loongshaw** [alibaba/RocketMQ#232]
集成rocketmq-client客户端后，客户端输出日志的地址：${user.home}/logs/rocketmqlogs/rocketmq_client.log，默认在自己用户目录下面，不知该输出路径可以更高不。

**Comment by vongosling** [comment]
目前却是不能改~

**Comment by loongshaw** [comment]
了解

**Comment by intecos** [comment]
默认地址：${user.home}/logs/rocketmqlogs/rocketmq_client.log，目前只能通过环境变量配置
见 ClientLogger.java 类，

public static final String CLIENT_LOG_ROOT = 'rocketmq.client.logRoot'; 
public static final String CLIENT_LOG_MAXINDEX = 'rocketmq.client.logFileMaxIndex'; 
public static final String CLIENT_LOG_LEVEL = 'rocketmq.client.logLevel';

相关代码：
String clientLogRoot = System.getProperty(CLIENT_LOG_ROOT,"${user.home}/logs/rocketmqlogs");
System.setProperty("client.logRoot",clientLogRoot);

在 client 的logback 的配置中，引用了环境变量：client.logRoot
