### ISSUE TITLE
rocketmq_client.log 缺少路径和个数，大小配置

### ISSUE THREAD

**Issue by ronyongxian** [alibaba/RocketMQ#235]
broker上疯狂堆积，请提供显式的配置。

**Comment by gaoyf** [comment]
这儿不是有俩配置文件吗，自己改不就行了
https://github.com/alibaba/RocketMQ/tree/master/rocketmq-client/src/main/resources

**Comment by ronyongxian** [comment]
修改client jar包，然后再给客户端使用？这明明是broker上的日志文件，路径配置为什么放到client包里面？

**Comment by vongosling** [comment]
问题和描述说了两个事情，O(∩_∩)O~
