### ISSUE TITLE
MQ挂掉后需要重启Consumer才能继续消费？

### ISSUE THREAD

**Issue by xiaoyao2102** [alibaba/RocketMQ#239]
MQ包括一个Namesrv和一个Broker，还有一个Producer和一个Consumer
具体场景如下：
1.正常开启MQ、Producer和Consumer，此时是可以正常收发消息的。
2.将MQ kill掉。
3.重新启动MQ。
4.再次发送消息，这时候Consumer是收不到数据的。
5.重启Consumer，此时可以正常收发数据，并且在启动后可以收到在第4步中那些没有消费的数据。

请问这样的现象是什么原因？有没有办法可以不用重启Consumer就继续收发消息的办法？

**Comment by doushini** [comment]
不用，Consumer有30s的心跳检查

**Comment by xiaoyao2102** [comment]
非常感谢！原来确实把心跳时间设得过长了
