### ISSUE TITLE
执行‘sh mqadmin wipeWritePerm’后重启broker，消息路由如何恢复

### ISSUE THREAD

**Issue by hanguanghong** [alibaba/RocketMQ#243]
我的mq集群有4台broker，其中一台有大量消息堆积，消费offset一直不变，所以想停掉此broker后删除store下的数据再重启。根据这篇文章，http://www.bubuko.com/infodetail-1093494.html，在停止broker前执行了‘sh mqadmin wipeWritePerm’。启动后发现此broker不能再接收消息。请问这种情况如何恢复？

**Comment by gaoyf** [comment]
原因分析：
1 sh mqadmin wipeWritePerm会将该broker的写权限从nameserver中清除
2 此时生产者rebalance之后，便不再往此broker上发送消息，参见[源码分析](http://blog.csdn.net/a417930422/article/details/50675289#updateTopicRouteInfoFromNameServer)
3 你重启broker，并且删掉了store下的数据
4 broker重启后会定时的向nameserver进行注册，此时是携带topic配置的，但是由于你删掉了topic的配置，所以broker不会携带topic配置，所以注册时nameserver会认为这个broker是新的，没有任何topic
5 此时，当然生产者不会往它发消息了
解决方法：
将其他机器上topic.json复制到有问题的broker下，重启

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
