### ISSUE TITLE
filter server自动加载失败

### ISSUE THREAD

**Issue by zhangnaqijie** [alibaba/RocketMQ#248]
根据[https://github.com/alibaba/RocketMQ/wiki/filter_server_guide](https://github.com/alibaba/RocketMQ/wiki/filter_server_guide)，把BrokerConfig的filterServerNums配置成1。FilterServerManager的定时任务，调用shell指令启动filter server。结果，shell指令不断执行，每次都没有启动成功，为什么？

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
