### ISSUE TITLE
通过MQAdmin获取统计信息时发生错误

### ISSUE THREAD

**Issue by zhuchunlai** [alibaba/RocketMQ#254]
#操作描述：
1、启动一个Producer实例向三个Topic中发送消息
2、启动三个Consumer实例，其中一个不订阅任何Topic，另外两个各订阅一个Topic（彼此订阅的Topic不同）
3、通过DefaultMQAdminExtImpl.examineConsumeStats方法获取消费统计信息，出现统计信息时有时无，没有的时候报如下异常：
com.alibaba.rocketmq.client.exception.MQClientException: Not found the consumer group consume stats, because return offset table is empty, maybe the consumer not consume any message
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumeStats(DefaultMQAdminExtImpl.java:239) ~[rocketmq-tools-3.2.6.jar:na]
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumeStats(DefaultMQAdminExt.java:177) ~[rocketmq-tools-3.2.6.jar:na]

#但是在此期间，消费者实例一直处于连接状态，并消费消息，通过DefaultMQAdminExtImpl.examineConsumerConnectionInfo方法可以看到消费者有三个连接，

客户端ID	地址	语言	版本
192.168.140.193@4103	192.168.140.193:50621	JAVA	79
192.168.140.193@4046	192.168.140.193:50279	JAVA	79
192.168.140.193@4045	192.168.140.193:50272	JAVA	79

**Comment by gaoyf** [comment]
你是不是三个consumer使用同一个consumergroup?

**Comment by zhuchunlai** [comment]
是，三个consumer使用同一个group

而且，进一步测试发现了一些问题：

1、两个订阅不同topic的Consumer实例，彼此只能交替消费消息，而不能同时消费消息。再动态调整订阅关系使两者订阅相同topic后，彼此能同时消费消息

2、上述现象期间，查看消费统计数据时，均会出现：
com.alibaba.rocketmq.client.exception.MQClientException: Not found the consumer group consume stats, because return offset table is empty, maybe the consumer not consume any message

3、当把三个consumer实例都停止时，查看消费统计数据，没有问题，且数据正确

**Comment by gaoyf** [comment]
看下吧 也许能解决你的疑惑 http://blog.csdn.net/a417930422/article/details/50663639

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
