### ISSUE TITLE
RocketMQ集群一个Consumer节点下单独某个Queue无法被消费的问题

### ISSUE THREAD

**Issue by gloomysundayy** [alibaba/RocketMQ#258]
MQ集群情况：2nameServer，6broker（3m+3s）
ConsumerGroup情况：6个节点

一直运行正常，今天12:40左右开始，一个Consumer节点下的4个queue中，第6个queue消息一直堆积没有被消费，从Consumer所在的服务看，所有Consumer的Thread都正常，除了一个正在处理数据时，其他都处于waiting状态，所以基本可以排除消费端服务阻塞导致，且，如果消费端阻塞，应该会影响这个Consumer节点下所有queue的消费，不会只有一个queue被阻塞。

### 阻塞时的这组consumer状态（出问题的节点在172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db下）：
[wangy@vlnx041012 bin]$ ./mqadmin consumerConnection -g oms_thirdpush_consumer_ios -n 127.0.0.1:9876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
##### 001  172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db 172.17.32.214:41324    JAVA     V3_2_6_SNAPSHOT
002  172.17.32.211@ac88a641-d346-42ca-a1c8-ff7ce29a7637 172.17.32.211:50793    JAVA     V3_2_6_SNAPSHOT
003  172.17.32.213@374173f7-40c9-4a4d-8bc8-5f6bb8c66d6e 172.17.32.213:60326    JAVA     V3_2_6_SNAPSHOT
004  172.17.32.216@a152c12d-4657-40ec-b46d-e3f88423e6ad 172.17.32.216:37264    JAVA     V3_2_6_SNAPSHOT
005  172.17.32.215@8b9b2386-afeb-475a-a6c5-b533ea548913 172.17.32.215:37067    JAVA     V3_2_6_SNAPSHOT
006  172.17.32.212@3396e28d-ca8a-48fd-b2b5-0e248e2d1d1e 172.17.32.212:34325    JAVA     V3_2_6_SNAPSHOT

Below is subscription:
001  Topic: %RETRY%oms_thirdpush_consumer_ios        SubExpression: *
002  Topic: OnlineManageThirdPush_iOS                SubExpression: *

ConsumeType: CONSUME_PASSIVELY
MessageModel: CLUSTERING
ConsumeFromWhere: CONSUME_FROM_LAST_OFFSET

### 整个Consumer的队列情况：
[wangy@vlnx041012 bin]$ ./mqadmin consumerProgress -g oms_thirdpush_consumer_ios -n 127.0.0.1:9876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Topic                            #Broker Name                      #QID  #Broker Offset        #Consumer Offset      #Diff
%RETRY%oms_thirdpush_consumer_io  broker-a                          0     0                     0                     0
%RETRY%oms_thirdpush_consumer_io  broker-b                          0     0                     0                     0
%RETRY%oms_thirdpush_consumer_io  broker-c                          0     10                    10                    0
OnlineManageThirdPush_iOS         broker-a                          0     320436                320436                0
OnlineManageThirdPush_iOS         broker-a                          1     320427                320427                0
OnlineManageThirdPush_iOS         broker-a                          2     320422                320422                0
OnlineManageThirdPush_iOS         broker-a                          3     320419                320419                0
OnlineManageThirdPush_iOS         broker-a                          4     320417                320417                0
OnlineManageThirdPush_iOS         broker-a                          5     320412                320412                0
OnlineManageThirdPush_iOS         broker-a                          6     320408                320407                1
OnlineManageThirdPush_iOS         broker-a                          7     320405                320404                1
OnlineManageThirdPush_iOS         broker-b                          0     319214                319214                0
OnlineManageThirdPush_iOS         broker-b                          1     319213                319213                0
OnlineManageThirdPush_iOS         broker-b                          2     319211                319211                0
OnlineManageThirdPush_iOS         broker-b                          3     319211                319211                0
OnlineManageThirdPush_iOS         broker-b                          4     319209                319209                0
OnlineManageThirdPush_iOS         broker-b                          5     319209                319209                0
##### OnlineManageThirdPush_iOS         broker-b                          6     319209                318523                686
OnlineManageThirdPush_iOS         broker-b                          7     319207                319207                0
OnlineManageThirdPush_iOS         broker-c                          0     319206                319205                1
OnlineManageThirdPush_iOS         broker-c                          1     319205                319204                1
OnlineManageThirdPush_iOS         broker-c                          2     319204                319204                0
OnlineManageThirdPush_iOS         broker-c                          3     319201                319201                0
OnlineManageThirdPush_iOS         broker-c                          4     319199                319198                1
OnlineManageThirdPush_iOS         broker-c                          5     319196                319196                0
OnlineManageThirdPush_iOS         broker-c                          6     319194                319194                0
OnlineManageThirdPush_iOS         broker-c                          7     319193                319193                0
出问题就是上面 broker-b 第 6 个queue

### 当时172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db这个节点的状态：
wangy@vlnx041012 bin]$ ./mqadmin consumerStatus -g oms_thirdpush_consumer_ios -i 172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db -n 127.0.0.1:9876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Consumer Properties#
unitMode                                : false
adjustThreadPoolNumsThreshold           : 100000
messageModel                            : CLUSTERING
consumerGroup                           : oms_thirdpush_consumer_ios
allocateMessageQueueStrategy            : com.alibaba.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely@49bfbe25
PROP_CLIENT_VERSION                     : V3_2_6_SNAPSHOT
consumeConcurrentlyMaxSpan              : 2000
postSubscriptionWhenPull                : false
consumeTimestamp                        : 20160511180314
PROP_CONSUME_TYPE                       : CONSUME_PASSIVELY
consumeMessageBatchMaxSize              : 1
defaultMQPushConsumerImpl               : com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl@4a5d57d7
PROP_THREADPOOL_CORE_SIZE               : 20
pullThresholdForQueue                   : 1000
pullInterval                            : 0
consumeFromWhere                        : CONSUME_FROM_LAST_OFFSET
PROP_NAMESERVER_ADDR                    : 172.17.41.12:9876;172.17.41.16:9876;172.17.41.14:9876;
pullBatchSize                           : 10
consumeThreadMin                        : 20
PROP_CONSUMER_START_TIMESTAMP           : 1462962794228
consumeThreadMax                        : 64
subscription                            : {}
PROP_CONSUMEORDERLY                     : false
messageListener                         : com.facishare.oms.thirdpush.mq.PushMessageConsumer$1@7021d6ae

#Consumer Subscription#
001 Topic: %RETRY%oms_thirdpush_consumer_ios        ClassFilter: false    SubExpression: *
002 Topic: OnlineManageThirdPush_iOS                ClassFilter: false    SubExpression: *

#Consumer Offset#
#Topic                            #Broker Name                      #QID  #Consumer Offset    
OnlineManageThirdPush_iOS         broker-b                          4     319300              
OnlineManageThirdPush_iOS         broker-b                          5     319300              
## OnlineManageThirdPush_iOS         broker-b                          6     318523              
OnlineManageThirdPush_iOS         broker-b                          7     319298              

#Consumer MQ Detail#
#Topic                            #Broker Name                      #QID  #ProcessQueueInfo   
OnlineManageThirdPush_iOS         broker-b                          4     ProcessQueueInfo [commitOffset=319300, cachedMsgMinOffset=0, cachedMsgMaxOffset=0, cachedMsgCount=0, transactionMsgMinOffset=0, transactionMsgMaxOffset=0, transactionMsgCount=0, locked=false, tryUnlockTimes=0, lastLockTimestamp=20160511183330192, droped=false, lastPullTimestamp=20160516134531678, lastConsumeTimestamp=20160516134531684]
OnlineManageThirdPush_iOS         broker-b                          5     ProcessQueueInfo [commitOffset=319300, cachedMsgMinOffset=0, cachedMsgMaxOffset=0, cachedMsgCount=0, transactionMsgMinOffset=0, transactionMsgMaxOffset=0, transactionMsgCount=0, locked=false, tryUnlockTimes=0, lastLockTimestamp=20160511183330190, droped=false, lastPullTimestamp=20160516134533686, lastConsumeTimestamp=20160516134533692]
##### OnlineManageThirdPush_iOS         broker-b                          6     ProcessQueueInfo [commitOffset=318523, cachedMsgMinOffset=318523, cachedMsgMaxOffset=318523, cachedMsgCount=1, transactionMsgMinOffset=0, transactionMsgMaxOffset=0, transactionMsgCount=0, locked=false, tryUnlockTimes=0, lastLockTimestamp=20160511183330189, droped=false, lastPullTimestamp=20160516134536415, lastConsumeTimestamp=20160516134536421]
OnlineManageThirdPush_iOS         broker-b                          7     ProcessQueueInfo [commitOffset=319298, cachedMsgMinOffset=0, cachedMsgMaxOffset=0, cachedMsgCount=0, transactionMsgMinOffset=0, transactionMsgMaxOffset=0, transactionMsgCount=0, locked=false, tryUnlockTimes=0, lastLockTimestamp=20160511183338088, droped=false, lastPullTimestamp=20160516134536416, lastConsumeTimestamp=20160516134536421]

#Consumer RT&TPS#
#Topic                                  #Pull RT      #Pull TPS    #Consume RT #ConsumeOK TPS #ConsumeFailed TPS  #ConsumeFailedMsgsInHour
%RETRY%oms_thirdpush_consumer_ios            0.00           0.00           0.00           0.00               0.00                         0
OnlineManageThirdPush_iOS                2067.89           1.62         173.76           1.62               0.00                         0

### 出问题Consumer节点本地RocketMQ的日志（queueId=6 的offset一直停留在318523）：
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_ios ClientId: 172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_iOS, brokerName=broker-b, queueId=7] 321528
##### 2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_ios ClientId: 172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_iOS, brokerName=broker-b, queueId=6] 318523
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_ios ClientId: 172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_iOS, brokerName=broker-b, queueId=5] 321532
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_ios ClientId: 172.17.32.214@cd21e6f5-648f-4f5a-9af2-cab2c5c194db updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_iOS, brokerName=broker-b, queueId=4] 321532
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_android ClientId: 172.17.32.214@ea59df91-85e6-4b6a-add0-3ba5317fb7ff updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_Android, brokerName=broker-b, queueId=7] 284757
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_android ClientId: 172.17.32.214@ea59df91-85e6-4b6a-add0-3ba5317fb7ff updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_Android, brokerName=broker-b, queueId=4] 284761
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_android ClientId: 172.17.32.214@ea59df91-85e6-4b6a-add0-3ba5317fb7ff updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_Android, brokerName=broker-b, queueId=6] 284758
2016-05-16 14:40:24 INFO MQClientFactoryScheduledThread - Group: oms_thirdpush_consumer_android ClientId: 172.17.32.214@ea59df91-85e6-4b6a-add0-3ba5317fb7ff updateConsumeOffsetToBroker MessageQueue [topic=OnlineManageThirdPush_Android, brokerName=broker-b, queueId=5] 284760

大概信息就这样，盼复

**Comment by gloomysundayy** [comment]
问题已经找到，是我们自己使用姿势不正确，Consumer的一个线程处理业务被socket挂住，没设置超时一直没返回，导致对应的queue得不到结果，后面的消息也就没办法拉下来

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
