### ISSUE TITLE
windows7下利用install.bat无法再根木录找到target文件夹

### ISSUE THREAD

**Issue by anLA7856** [alibaba/RocketMQ#262]
已经装好了maven，

[ERROR] Failed to execute goal on project rocketmq-tools: Could not resolve depe
ndencies for project com.alibaba.rocketmq:rocketmq-tools:jar:3.2.6: Failed to co
llect dependencies at org.kohsuke:github-api:jar:1.59 -> com.infradna.tool:bridg
e-method-annotation:jar:1.12 -> org.jenkins-ci:annotation-indexer:jar:1.4: Faile
d to read artifact descriptor for org.jenkins-ci:annotation-indexer:jar:1.4: Cou
ld not transfer artifact org.jenkins-ci:jenkins:pom:1.26 from/to repo.jenkins-ci
.org (http://repo.jenkins-ci.org/public/): 这是在主机名解析时通常出现的暂时错误
，它意味着本地服务器没有从权威服务器上收到响应。: Unknown host 这是在主机名解析
时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。 -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :rocketmq-tools

**Comment by anLA7856** [comment]
问题虽然没有解决，但是可以下载一个已经编译好的rocketmq文件，然后可以直接用里面的mqnamesrv.exe解决

**Comment by justimkiss** [comment]
#200
