### ISSUE TITLE
消息发错服务器了（标题太短不好描述）

### ISSUE THREAD

**Issue by saaavsaaa** [alibaba/RocketMQ#263]
我的生产环境是双主未集群，各自单独部署，双写的，今天生产者所在的tomcat以替换class的方式上线了一个无关的功能，3个完全相同的tomcat启动后，其中一个tomcat出现了生产发出的两条消息都进了一个主，而没有每个主一个，另外两个tomcat正常，这个问题在再次重启这个tomcat后消失了
代码临时传到下面这里了
srv.addresses=192.168.1.44:9876,192.168.1.45:9876

https://github.com/saaavsaaa/warn-report/blob/master/src/main/java/rocketDoubleWrite/ProducerClient.java

**Comment by gaoyf** [comment]
可以把当时出问题机器的业务日志和tomcat日志发出来，没有日志不好看啊

**Comment by saaavsaaa** [comment]
thx，日志其实看过，没有什么线索

**Comment by saaavsaaa** [comment]
今天又出这个问题了，有这样两条日志
[http-nio-443-exec-22:20766][Producer:cn.******.***.rocket.Producer.send(ProducerClient.java:122)] ==============ip : 101.201.210.158, send NamesrvAddr : 192.168.1.44:9876, send key: *********, topic :r****Topic
[http-nio-443-exec-22:20785][Producer:cn.*******.***.rocket.Producer.send(ProducerClient.java:122)] ==============ip : 101.201.210.158, send NamesrvAddr : 192.168.1.45:9876, send key: ********1, topic :r****Topic

但是都发到192.168.1.45上了

**Comment by saaavsaaa** [comment]
感觉上和应用启动有关系。。。

**Comment by gaoyf** [comment]
你的判断条件有问题啊
···
if (sendResult != null && sendResult.getSendStatus() != SendStatus.SEND_OK) {
  errorSendeds.add(msg);
}
···
这个SendStatus不是OK并不代表没有发送成功啊，你把这样的消息重复发送了。。。

**Comment by saaavsaaa** [comment]
这个判断是故意这样写的，为了防止消息发送成功刷盘失败然后rocket挂了这样，这个ProducerSingle代码昨天临时加了个单主的，线上不是用的这个，用的是https://github.com/saaavsaaa/warn-report/blob/master/src/main/java/rocketDoubleWrite/ProducerDouble.java，重复发送也应该有打repeat的日志，但是没有，而且重发也是两台都发的，谢啦

**Comment by gaoyf** [comment]
我感觉像我之前遇到的问题，你看下这个，是否是这个问题，自己debug一下：
[rocketmq问题汇总-instanceName参数何时该设置？](http://blog.csdn.net/a417930422/article/details/50663629)

**Comment by saaavsaaa** [comment]
好的，我试下是不是这个问题，这个逻辑也是故意的，就是只要有超过一个rocket出问题，直接将错误返回给前面，前面的业务逻辑执行错误分支的逻辑

**Comment by saaavsaaa** [comment]
经过测试发现确实是实例名的问题，谢啦
