### ISSUE TITLE
`if (BrokerRole.SLAVE == messageStoreConfig.getBrokerRole())`即使是slave也不会为true

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#264]
final MessageStoreConfig messageStoreConfig = new MessageStoreConfig();
     // 如果是slave，修改默认值
            if (BrokerRole.SLAVE == messageStoreConfig.getBrokerRole()) {

`BrokerStartup`中，当Broker启动的时候，有这样的一段代码，然而中间没有修改过这个brokerRole的值，而默认值是代码写死的AYNC_MASTER

那这段代码是否位置错了，应该放在合并配置文件之后？

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
