### ISSUE TITLE
目前开源的版本是不是事务还没有支持？

### ISSUE THREAD

**Issue by scyehan** [alibaba/RocketMQ#265]
我看了源码，broker查询client本地事务是否成功的逻辑存在但没有使用，后续回补上吗？

**Comment by zhoujmhz** [comment]
我查了源代码，事务消息支持，但不完整。
本地endTransaction()如果失败。后继的Broker没有check发送的Producer。
我查了阿里云的ONS内部的版本好像更新到了，rocketmq-client-3.4.9.jar
并且已经支持完整个事务，但没有开源出来
ONS的client：https://help.aliyun.com/document_detail/29546.html?spm=5176.doc29548.6.107.P2Far0
事务消息的文档说明：https://help.aliyun.com/document_detail/29548.html?spm=5176.doc29546.6.109.MXujFE

**Comment by vongosling** [comment]
yeah.we plan not to open source  transaction message function.if you want to use this feather,please using our commercial version ONS,https://www.aliyun.com/product/ons/?spm=5176.7960203.237031.136.YGe41J
