### ISSUE TITLE
RocketMQ事务消息支持不完整

### ISSUE THREAD

**Issue by zhoujmhz** [alibaba/RocketMQ#266]
我查了源代码，事务消息支持，但不完整。
本地endTransaction()如果失败。后继的Broker没有check发送的Producer。
我查了阿里云的ONS内部的版本好像更新到了，rocketmq-client-3.4.9.jar
并且已经支持完整个事务，但没有开源出来
ONS的client：https://help.aliyun.com/document_detail/29546.html?spm=5176.doc29548.6.107.P2Far0
事务消息的文档说明：https://help.aliyun.com/document_detail/29548.html?spm=5176.doc29546.6.109.MXujFE

**Comment by YunaiV** [comment]
是的，回查这块目前“404”了。

我整理了下事务的历史情况：http://www.yunai.me/RocketMQ/message-transaction/?gtihub&03
