### ISSUE TITLE
连接超时设置问题

### ISSUE THREAD

**Issue by ccvcd** [alibaba/RocketMQ#270]
项目中最近发现客户端连接服务端总是超时，造成连接不上，查看mq连接代码，结合相关资料，发现mq连接实现有点问题。
资料1：
在使用Netty编写客户端的时候，我们一般会有类似这样的代码：
bootstrap.connect(address).await(1000, TimeUnit.MILLISECONDS)
向对端发起一个连接，超时等待1秒钟。如果1秒钟没有连接上则重连或者做其他处理。而其实在bootstrap的选项里，还有这样的一项：
bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 3000);
如果这两个值设置的不一致，在await的时候较短，而option里设置的较长就出问题了。这个时候你会发现connect里已经超时了，你以为连接失败了，但实际上await超时Netty并不会帮你取消正在连接的链接。这个时候如果第2秒的时候连上了对端服务器，那么你刚才的判断就失误了。如果你根据connect(address).await(1000, TimeUnit.MILLISECONDS)来决定是否重连，很有可能你就建立了两个连接，而且很有可能你的handler就在这两个channel里共享起来了，这就有可能让你产生：哎呀，Netty的handler不是在单线程里执行的这样的假象。所以我的建议是，不要在await上设置超时，而总是使用option上的选项来设置。这个更准确些，超时了就是真的表示没有连上。

资料2：
不要混淆IO超时（IO timeout）和await超时（await timeout）。调用方法Future.await(long),Future.await(long, TimeUnit), Future.awaitUninterruptibly(long), 或者Future.awaitUninterruptibly(long, TimeUnit)的超时与IO超时没有任何关系。如果IO超时channelfuture对象会被标记为带失败的完成状态（completed with failure），IO超时的参数可以通过option设置，代码如下：

// BAD - NEVER DO THIS 永远不要这样做
 Bootstrap b = ...; 
 ChannelFuture f = b.connect(...);
 f.awaitUninterruptibly(10, TimeUnit.SECONDS);//IO超时应该设置到channelconfig，而不是channelfuture
 if (f.isCancelled()) {
     // Connection attempt cancelled by user
 } else if (!f.isSuccess()) {
     // You might get a NullPointerException here because the future
     // might not be completed yet.
     f.cause().printStackTrace();
 } else {
     // Connection established successfully
 }

 // GOOD 正确的做法
 Bootstrap b = ...;
 // Configure the connect timeout option. 
 b.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000);//这里最终会通过channelconfig来配置
 ChannelFuture f = b.connect(...);
 f.awaitUninterruptibly();

 // Now we are sure the future is completed.
 assert f.isDone();

 if (f.isCancelled()) {
     // Connection attempt cancelled by user
 } else if (!f.isSuccess()) {
     f.cause().printStackTrace();
 } else {
     // Connection established successfully
 }

结果：
Netty中ChannelOption.CONNECT_TIMEOUT_MILLIS的默认值是30000，mq没有设置此项值，连接应该走默认值30000，而awaitUninterruptibly时值为3000，这样的情况正好是资料1所描述的，所以连接实现是不是调整成资料1和资料2建议的方式。

**Comment by jerrysearch** [comment]
关注

**Comment by gaoyf** [comment]
赞

**Comment by saaavsaaa** [comment]
关注

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions and using english to question

**Comment by owenludong** [comment]
是3.4.6版本 已经解决了这个问题了吗？ 我看remoting工程这半年都没改过

**Comment by yuweitaocn** [comment]
为了堵这一个坑我容易么。

**Comment by Jaskey** [comment]
我想确认下：fix这个issue 的唯一修改点是不是：

start 的时候对设置boot strap 的ChannelOption.CONNECT_TIMEOUT_MILLIS 和nettyclient config 的connection time out 一致：

                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, nettyClientConfig.getConnectTimeoutMillis())

**Comment by MaoJianwei** [comment]
so, is this question closed without any applied solution? (just because of chinese post?)

**Comment by gaoyf** [comment]
This has been fixed at version [v3.5.8](https://github.com/alibaba/RocketMQ/releases), @MaoJianwei.
