### ISSUE TITLE
broker 启动失败，提示找不到JAVA_HOME

### ISSUE THREAD

**Issue by noprom** [alibaba/RocketMQ#271]
我已经设置了JAVA_HOME,并且也生效了，在用
```
nohup mqbroker >/var/log/mq.log &
```
时提示没有设置JAVA_HOME.
再启动broker之前已经启动nameserver,而且已经指定nameserver地址,如下所示:
```
➜  bin nohup  mqnamesrv >/var/log/ns.log &
[1] 2228
➜  bin cat /var/log/ns.log
The Name Server boot success.
➜  bin export NAMESRV_ADDR=localhost:9876
```
下面是详细报错信息:
```
➜  bin sudo nohup mqbroker >/var/log/mq.log &
[2] 2309
➜  bin
[2]  + 2309 exit 1     sudo nohup mqbroker > /var/log/mq.log
➜  bin tail -f /var/log/mq.log
ERROR: Please set the JAVA_HOME variable in your environment, We need java(x64)! !!
^C
➜  bin echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
➜  bin
```

**Comment by gaoyf** [comment]
`bin sudo nohup mqbroker >/var/log/mq.log &`
`sudo` 应该是用root用户执行吧，root有配置JAVA_HOME的环境变量吗？
`bin nohup  mqnamesrv >/var/log/ns.log &` 你这个nameserver是用当前用户，没有用root哦

**Comment by saaavsaaa** [comment]
我写了些代码调用ssh2执行shell的方式执行rocket命令的时候也是这个提示，用户的环境变量是有的，于是我把tools.sh改了JAVA_HOME=/usr/java/jdk1.8.0_91，其实加个软链也可以的吧，不过顺手就改了。。。

**Comment by noprom** [comment]
@gaoyf  谢谢，就是这个问题，去掉root就可以了。
