### ISSUE TITLE
mqadmin cloneGroupOffset命令未设置请求头

### ISSUE THREAD

**Issue by zhangyl** [alibaba/RocketMQ#273]
方法：com.alibaba.rocketmq.client.impl.MQClientAPIImpl.cloneGroupOffset(String, String, String, String, boolean, long)2103行：
RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.CLONE_GROUP_OFFSET, null);
应该修改为：
RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.CLONE_GROUP_OFFSET, requestHeader);

否则：

**Comment by zhangyl** [comment]
否则：
com.alibaba.rocketmq.client.exception.MQClientException: CODE: 1  DESC: java.lang.NullPointerException, com.alibaba.rocketmq.broker.processor.AdminBrokerProcessor.cloneGroupOffset(AdminBrokerProcessor.java:1219)

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
