### ISSUE TITLE
请教高手 rocketMQ如何设置分配内存比较好?  failed; error='Cannot allocate memory' (errno=12)

### ISSUE THREAD

**Issue by musicaptain** [alibaba/RocketMQ#275]
centos 6.5
alibaba-rocketmq-3.2.6
broker.BrokerStartup -Xms4g -Xmx4g -Xmn2g -XX:PermSize=128m -XX:MaxPermSize=320m

经常报java错误  failed; error='Cannot allocate memory' (errno=12)

**Comment by vongosling** [comment]
your virtual memory 60%～８０％
