### ISSUE TITLE
测试时发现消费端有消费不到数据的情况和消费后乱码的情况

### ISSUE THREAD

**Issue by XinCao** [alibaba/RocketMQ#279]
生产者
topic : antifraud
tags: "register", "login", "lend", "cash"
1.生产者，分别写入 2000条
2.写成功，数据
#Broker Name	#QID	#Min Offset	#Max Offset	#Last Updated
broker-a	0	0	667	2016-06-23 10:18:01,883
broker-a	1	0	667	2016-06-23 10:18:01,884
broker-a	2	0	667	2016-06-23 10:18:01,885
broker-a	3	0	667	
broker-b	0	0	667	2016-06-23 10:18:01,883
broker-b	1	0	667	2016-06-23 10:18:01,884
broker-b	2	0	667	2016-06-23 10:18:01,885
broker-b	3	0	667	2016-06-23 10:18:01,885
broker-c	0	0	666	2016-06-23 10:18:01,876
broker-c	1	0	666	2016-06-23 10:18:01,880
broker-c	2	0	666	2016-06-23 10:18:01,881
broker-c	3	0	666	2016-06-23 10:18:01,881

消费者统计
共消费 7783 条
lend 1886
cash 1
login 1967
register1967

奇怪的出现了 tag=null 共 1938  tag= c\00\00\00 共25

**Comment by XinCao** [comment]
代码：
package com.br.rocketmq.test.producer;

import com.alibaba.rocketmq.client.exception.MQBrokerException;
import com.alibaba.rocketmq.client.exception.MQClientException;
import com.alibaba.rocketmq.client.producer.DefaultMQProducer;
import com.alibaba.rocketmq.common.message.Message;
import com.alibaba.rocketmq.remoting.exception.RemotingException;
import java.nio.charset.Charset;

/**
 *
 * @author xin.cao@100credit.com
 */
public class DefaultMQProducerTest {

    private DefaultMQProducer defaultMQProducer;

    public void init() throws MQClientException {
        defaultMQProducer = new DefaultMQProducer();
        defaultMQProducer.setNamesrvAddr("127.0.0.1:9876");
        defaultMQProducer.setClientIP("127.0.0.1"); // 某些机器存在无法识别客户端ip的情况
        defaultMQProducer.setInstanceName("DefaultMQProducerTest");
        defaultMQProducer.setClientCallbackExecutorThreads(4);
        defaultMQProducer.setPollNameServerInteval(30000);
        defaultMQProducer.setHeartbeatBrokerInterval(30000);
        defaultMQProducer.setPersistConsumerOffsetInterval(5000);
        defaultMQProducer.setProducerGroup("DefaultMQProducerTestGroup");
        defaultMQProducer.setDefaultTopicQueueNums(4);
        defaultMQProducer.setSendMsgTimeout(10000);
        defaultMQProducer.setCompressMsgBodyOverHowmuch(4096);
        defaultMQProducer.setRetryAnotherBrokerWhenNotStoreOK(false);
        defaultMQProducer.setMaxMessageSize(131072);
        defaultMQProducer.start();
    }

    public void send(String topic, String tag, String key, String data) throws MQClientException, RemotingException, MQBrokerException, InterruptedException {
        Message message = new Message();
        message.setTopic(topic);
        message.setTags(tag);
        message.setKeys(key);
        message.setBody(data.getBytes(Charset.forName("UTF-8")));
        defaultMQProducer.send(message);
    }

    public static void main(String... args) throws MQClientException, RemotingException, MQBrokerException, InterruptedException {
        DefaultMQProducerTest defaultMQProducerTest = new DefaultMQProducerTest();
        defaultMQProducerTest.init();
        String topic = "antifraud";
        String[] events = new String[]{"register", "login", "lend", "cash"};
        int loop = 8000;
        for (int i = 0; i < loop; i++) {
            int index = i % events.length;
            String event = events[index];
            defaultMQProducerTest.send(topic, event, String.valueOf(i), new StringBuilder("index=").append(i).append(" hello world!").toString());
        }
    }

}

package com.br.rocketmq.test.consumer;

import com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer;
import com.alibaba.rocketmq.client.consumer.listener.ConsumeConcurrentlyContext;
import com.alibaba.rocketmq.client.consumer.listener.ConsumeConcurrentlyStatus;
import com.alibaba.rocketmq.client.consumer.listener.MessageListenerConcurrently;
import com.alibaba.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely;
import com.alibaba.rocketmq.client.exception.MQClientException;
import com.alibaba.rocketmq.common.consumer.ConsumeFromWhere;
import com.alibaba.rocketmq.common.message.MessageExt;
import com.alibaba.rocketmq.common.protocol.heartbeat.MessageModel;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author xin.cao@100credit.com
 */
public class DefaultMQPushConsumerTest {

    private DefaultMQPushConsumer defaultMQPushConsumer;
    private AtomicInteger counter = new AtomicInteger(0);

    public void init(String topic) throws MQClientException {
        defaultMQPushConsumer = new DefaultMQPushConsumer();
        defaultMQPushConsumer.setNamesrvAddr("127.0.0.1:9876");
        defaultMQPushConsumer.setClientIP("127.0.0.1"); // 某些机器存在无法识别客户端ip的情况
        defaultMQPushConsumer.setInstanceName("DefaultMQPushConsumerTest");
        defaultMQPushConsumer.setClientCallbackExecutorThreads(4);
        defaultMQPushConsumer.setPollNameServerInteval(30000);
        defaultMQPushConsumer.setHeartbeatBrokerInterval(30000);
        defaultMQPushConsumer.setPersistConsumerOffsetInterval(5000);
        defaultMQPushConsumer.setConsumerGroup("DefaultMQPushConsumerTestGroup");
        defaultMQPushConsumer.setMessageModel(MessageModel.CLUSTERING);
        defaultMQPushConsumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        defaultMQPushConsumer.setAllocateMessageQueueStrategy(new AllocateMessageQueueAveragely());
//        defaultMQPushConsumer.setSubscription(null);
//        defaultMQPushConsumer.setMessageListener(null);
//        defaultMQPushConsumer.setOffsetStore(null);
        defaultMQPushConsumer.setConsumeThreadMin(10);
        defaultMQPushConsumer.setConsumeThreadMax(20);
        defaultMQPushConsumer.setConsumeConcurrentlyMaxSpan(2000);
        defaultMQPushConsumer.setPullThresholdForQueue(1000);
        defaultMQPushConsumer.setPullInterval(0);
        defaultMQPushConsumer.setConsumeMessageBatchMaxSize(1);
        defaultMQPushConsumer.setPullBatchSize(32);
        defaultMQPushConsumer.subscribe(topic, null);
        defaultMQPushConsumer.registerMessageListener(new MessageListenerConcurrently() {

            @Override
            public ConsumeConcurrentlyStatus consumeMessage(final List<MessageExt> msgs, final ConsumeConcurrentlyContext context) {
                for (MessageExt messageExt : msgs) {
                    System.out.println(String.format("no = %s tag = %s data = %s", counter.getAndAdd(1), messageExt.getTags(), new String(messageExt.getBody())));
                }
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });
        defaultMQPushConsumer.start();
    }

    public static void main(String... args) throws MQClientException {
        String topic = "antifraud";
        DefaultMQPushConsumerTest defaultMQPushConsumerTest = new DefaultMQPushConsumerTest();
        defaultMQPushConsumerTest.init(topic);
    }
}

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
