### ISSUE TITLE
重启Broker-Master 会导致之前已成功消费过的消息被全部重新消费一次！

### ISSUE THREAD

**Issue by flysqrlboy** [alibaba/RocketMQ#28]
重启Broker-Master 会导致之前已成功消费过的消息被全部重新消费一次！

1。【环境】
rocketmq version : 3.1.9 
集群方式： 2个nameserver；1个broker-master ，1个broker-slave，异步复制

2。【过程重现】
（1）关闭broker-master 之前，topic=mobileSyncDataTopic 的消费进度：已成功消费50条消息。

mqadmin  consumerProgress -g mobileSyncDataConsumerGroup -n 10.10.10.131:9876
#Topic                            #Broker Name                      #QID  #Broker Offset        #Consumer Offset      #Diff
%RETRY%mobileSyncData       broker-a                          0     0                     0                     0
mobileSyncDataTopic               broker-a                          0     13                    13                    0
mobileSyncDataTopic               broker-a                          1     13                    13                    0
mobileSyncDataTopic               broker-a                          2     12                    12                    0
mobileSyncDataTopic               broker-a                          3     12                    12                    0

（2）关闭broker-master 后，offset重置为0，Diff也为0

mqadmin  consumerProgress -g mobileSyncDataConsumerGroup -n 10.10.10.131:9876
#Topic                            #Broker Name                      #QID  #Broker Offset        #Consumer Offset      #Diff
%RETRY%mobileSync              broker-a                          0     0                     0                     0
mobileSyncDataTopic               broker-a                          0     0                     0                     0
mobileSyncDataTopic               broker-a                          1     0                     0                     0
mobileSyncDataTopic               broker-a                          2     0                     0                     0
mobileSyncDataTopic               broker-a                          3     0                     0                     0

（3）重启broker-master后，offset 、diff 会恢复成重启前的值。且已经在重启前成功消费过的50条消息会重新消费一次。
 
mqadmin  consumerProgress -g mobileSyncDataConsumerGroup -n 10.10.10.131:9876 
#Topic                            #Broker Name                      #QID  #Broker Offset        #Consumer Offset      #Diff
%RETRY%mobileSync              broker-a                          0     0                     0                     0
mobileSyncDataTopic               broker-a                          0     13                    13                    0
mobileSyncDataTopic               broker-a                          1     13                    13                    0
mobileSyncDataTopic               broker-a                          2     12                    12                    0
mobileSyncDataTopic               broker-a                          3     12                    12                    0

下面分别是重启前的消费日志和重启后的消费日志，可以看到，消息确实被重新消费了【日志太多，节选三条消息对比如下】！

【重启前消费日志】
ConsumeMessageThread_1 Receive New Messages: [MessageExt [queueId=0, storeSize=146, queueOffset=0, sysFlag=0, bornTimestamp=1418712824540, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824677, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F000000000089920F, commitLogOffset=9015823, bodyCRC=613185359, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=16]]]
ConsumeMessageThread_2 Receive New Messages: [MessageExt [queueId=0, storeSize=146, queueOffset=1, sysFlag=0, bornTimestamp=1418712825062, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824759, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F0000000000899457, commitLogOffset=9016407, bodyCRC=601994070, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=16]]]
ConsumeMessageThread_5 Receive New Messages: [MessageExt [queueId=0, storeSize=147, queueOffset=4, sysFlag=0, bornTimestamp=1418712825175, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824884, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F0000000000899B35, commitLogOffset=9018165, bodyCRC=1659149091, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=17]]]

【重启后消费日志】
ConsumeMessageThread_19 Receive New Messages: [MessageExt [queueId=0, storeSize=146, queueOffset=0, sysFlag=0, bornTimestamp=1418712824540, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824677, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F000000000089920F, commitLogOffset=9015823, bodyCRC=613185359, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=16]]]
ConsumeMessageThread_19 Receive New Messages: [MessageExt [queueId=0, storeSize=146, queueOffset=1, sysFlag=0, bornTimestamp=1418712825062, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824759, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F0000000000899457, commitLogOffset=9016407, bodyCRC=601994070, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=16]]]
ConsumeMessageThread_18 Receive New Messages: [MessageExt [queueId=0, storeSize=147, queueOffset=4, sysFlag=0, bornTimestamp=1418712825175, bornHost=/10.10.10.1:55629, storeTimestamp=1418712824884, storeHost=/10.10.10.131:10911, msgId=0A0A0A8300002A9F0000000000899B35, commitLogOffset=9018165, bodyCRC=1659149091, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message [topic=mobileSyncDataTopic, flag=0, properties={TAGS=TagA, WAIT=true, MAX_OFFSET=13, MIN_OFFSET=0}, body=17]]]

3.【问题】
（1）如何避免在broker-master重启后以前已被消费过的消息再一次被全部消费？
（2）当broker-master宕机后，broker-slave不会自动切换为master。在broker-master宕掉后，再发消息会报错：
          No route info of this topic, mobileSyncDataTopic
          See https://github.com/alibaba/RocketMQ/issues/264 for further details.
     at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl( DefaultMQProducerImpl.java:624)
     at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send( DefaultMQProducerImpl.java:1050)
     at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send( DefaultMQProducer.java:122)
          也就是说master-slave没有起到HA failover的效果。

**Comment by hlf3300** [comment]
flysqrlboy  能留下你的联系方式不，我想详细了解下这个问题具体的重现场景：
1.主备broker是如何与两个nameserver连接的（是不是都连了）；
2. 主broker是同步复制，还是异步复制；
3. 重启主broker时consumer是否一直在线；
4. consumer是不是pushconsumer；

**Comment by vintagewang** [comment]
无回应， 关闭。

**Comment by vintagewang** [comment]
问题原因已经确定。

3.2.4之前版本主备同步有bug，导致数据由延迟，参见以下issue

https://github.com/alibaba/RocketMQ/pull/25
