### ISSUE TITLE
offset无法正常更新

### ISSUE THREAD

**Issue by lizhengnan** [alibaba/RocketMQ#281]
使用rocketmq进行消息处理， 在消息处理的业务逻辑中会调用第三方接口，最近第三方偶尔不太稳定，会调用60s超时，但业务处理都会捕获异常并返回CONSUME_SUCCESS.
但现在会出现奇怪的问题就是出现以上问题后，会出现无法正确更新offset的问题
16-06-21 12:57:28 INFO MQClientFactoryScheduledThread - Group: sms_consumer_group ClientId: 192.168.1.148@9560 updateConsumeOffsetToBroker MessageQueue [topic=YooliSMSTopic, brokerName=broker-b, queueId=6] 707212
16-06-21 12:58:28 INFO MQClientFactoryScheduledThread - Group: sms_consumer_group ClientId: 192.168.1.148@9560 updateConsumeOffsetToBroker MessageQueue [topic=YooliSMSTopic, brokerName=broker-b, queueId=6] 707212
16-06-21 12:59:28 INFO MQClientFactoryScheduledThread - Group: sms_consumer_group ClientId: 192.168.1.148@9560 updateConsumeOffsetToBroker MessageQueue [topic=YooliSMSTopic, brokerName=broker-b, queueId=6] 707212

更新的offset始终都是一个值，但实际上消息还在正常的拉取处理
16-06-21 13:09:00 INFO MQClientFactoryScheduledThread - [PULL_TPS] [YooliSMSTopic@sms_consumer_group] Stats In One Minute, SUM: 9 TPS: 0.15 AVGPT: 1.00
16-06-21 13:09:00 INFO MQClientFactoryScheduledThread - [CONSUME_OK_TPS] [YooliSMSTopic@sms_consumer_group] Stats In One Minute, SUM: 9 TPS: 0.15 AVGPT: 1.00
但回写的offset确不变，是否存在某种情况导致消息后的消息无法从ProcessQueue中的msgTreeMap中删除，使得这条消息永远处于树的根部，导致更新offset异常？

**Comment by gaoyf** [comment]
之后呢  更新的offset   一直不变了吗？

**Comment by lizhengnan** [comment]
是的，更新的offset永远都不变了，直到我重启消费服务。 
这样就是我消费端还在消费，但broker中大量消息堆积，重启服务后还会导致消息重复的处理。

**Comment by lizhengnan** [comment]
是的，更新的offset永远都不变了，直到我重启消费服务。 
这样就是我消费端还在消费，但broker中大量消息堆积，重启服务后还会导致消息重复的处理。

**Comment by lizhengnan** [comment]
是的，更新的offset永远都不变了，直到我重启消费服务。 
这样就是我消费端还在消费，但broker中大量消息堆积，重启服务后还会导致消息重复的处理。

**Comment by lizhengnan** [comment]
是的，更新的offset永远都不变了，直到我重启消费服务。 
这样就是我消费端还在消费，但broker中大量消息堆积，重启服务后还会导致消息重复的处理。

**Comment by lizhengnan** [comment]
是的，更新的offset永远都不变了，直到我重启消费服务。 
这样就是我消费端还在消费，但broker中大量消息堆积，重启服务后还会导致消息重复的处理。

**Comment by gaoyf** [comment]
consumeMessageBatchMaxSize设的是多大？你是顺序消费还是并发消费？

**Comment by lizhengnan** [comment]
consumeMessageBatchMaxSize使用默认的1， 并发消费。

**Comment by gaoyf** [comment]
CONSUME_OK_TPS有值表明有消息消费成功，但是不代表queueId=6的消息被消费成功
只有queueId=6的offset不变了，还是所有的queue的offset都不变了？
