### ISSUE TITLE
批量消费消息，ACK的机制是否有丢消息的可能

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#282]
`ConsumeMessageConcurrentlyService `中，成功后，会update 最大offset。

例如一批是1-10，然后并发消费给了两个ConsumeRequest, 1-5, 6-10。

假设6-10先消费成功，会更新offset为10，但其实这时候假设1-5消费慢，而10已经更新了。前面这些又还没有完全消费完成。

意外发生了：在消费1的时候立刻就consumer 实例断电了。

broker这段是否会认为1-10都消费完成了？不再发送1-5的消息？如果不是，是怎么规避的？

**Comment by lizhengnan** [comment]
从代码上看好像并不是回写最大的offset， 而是当前处理队列中最小的。
`public long removeMessage(final List<MessageExt> msgs) {
        long result = -1;
        final long now = System.currentTimeMillis();
        try {
            this.lockTreeMap.writeLock().lockInterruptibly();
            this.lastConsumeTimestamp = now;
            try {
                if (!msgTreeMap.isEmpty()) {
                    result = this.queueOffsetMax + 1;
                    int removedCnt = 0;
                    for (MessageExt msg : msgs) {
                        MessageExt prev = msgTreeMap.remove(msg.getQueueOffset());
                        if (prev != null) {
                            removedCnt--;
                        }
                    }
                    msgCount.addAndGet(removedCnt);

                    if (!msgTreeMap.isEmpty()) {
                        result = msgTreeMap.firstKey();
                    }
                }
            }
            finally {
                this.lockTreeMap.writeLock().unlock();
            }
        }
        catch (Throwable t) {
            log.error("removeMessage exception", t);
        }

        return result;
    }`

这样如果出问题了，可能10会重复消费，要求自己做好幂等性

**Comment by Jaskey** [comment]
@lizhengnan ，不是这里的问题，而是说你两个consumer 实例，C1,C2两台机子，分别消费1，2

假设C2先消费完成，ack回去2了，这时候C1挂了，断电。那Broker不就以为现在消费进度是2，再也拉不回来1的消息咯？

**Comment by lizhengnan** [comment]
RocketMQ的代码我也没有太细看，只是这两天遇到点问题简单看了一下。
RocketMQ并发消费模式下，是以Queue为单位进行负载的，每一个broker下的topic都会对应多个Queue, 在有消费者加入后，消费者会收到当前queueId和cid(消费者)列表，以平局分配为列就是queueId数 / cid数来获取当前消费者应处理的queue。
所以这种情况下并不会出现2个消费者同时消费一个queue里的消息的情况，也就不会出现你说的这种问题

**Comment by Jaskey** [comment]
@lizhengnan , queue的数量是可以配置的，当Customer的实例数量大于queue数量的时候，必然会出现多个customer消费一个queue的情况，极端的例子是，只有一个quene, N个Customer。

所以这样的场景是必然存在的。

**Comment by lizhengnan** [comment]
但是 Consumer 数量要小于等于队列数 量,如果 Consumer 超过队列数量,那么多余的 Consumer 将不能消费消息。

[以上这句话是官方设计文档里写的](https://github.com/alibaba/RocketMQ-docs/tree/gh-pages/document/design)
你也可以看一下AllocateMessageQueueAveragely类中的allocate方法

**Comment by Jaskey** [comment]
@lizhengnan ，所以Rocket是这样在全都消费成功的情况下，不会丢消息的：

1. ack 回去的是多线程消费中的最小者，故在全部消费完之前，broker不会贸然跳跃。
2. 不会有多机器去听一个queue的情况。所以同一个queue的进度不会分布在不同机器上。


那还有一个问题，这种并发消费的，如果有一条消费失败：
1.rocket会全部重发
1.1若重发失败，则直接consumeLater
2.offset立刻更新（告诉broker当成功处理）。

如果有一条offset=5失败了，api尝试重发了1-10的消息。再发送到第6条的时候重发失败，`sendMessageBack`，这时候会consumeLater

如果这个时候2执行完成，则broker认为消费进度到了10。这时候消费实例进程退出，这条6是不是就丢了？

**Comment by lizhengnan** [comment]
broker的代码我也没看，不能确定的回答你。

消息消费失败回退给broker后，重试的消息会进去RETRY队列，而不影响现有的消费队列。
每一个消息消费后都要给broker一个ack， 没有得到ack的消息不认为是消费成功，所以offset=6的消息还在broker中存在，当消费者重启还会收到这条offset=6的消息。

rocketmq的文档中说保证以下情况是消息不丢失或不丢失(依赖刷盘的方式是同步还是异步):
(1). Broker 正常关闭
(2). Broker 异常 Crash
(3). OS Crash
(4). 机器掉电,但是能立即恢复供电情况。

**Comment by Jaskey** [comment]
尝试放到RETRY topic的时候如果失败，会consumeLater。

而这是在另外一个线程delay一段事件后执行。

在原线程，就立刻更新offset（当全部成功处理），这段期间假如broker offset更新了但是还没有重试消费的话，断电就丢了，不是吗？

**Comment by gaoyf** [comment]
```
if (!msgBackFailed.isEmpty()) {
                consumeRequest.getMsgs().removeAll(msgBackFailed);//此代码会将放入RETRY失败的移除
                this.submitConsumeRequestLater(msgBackFailed, consumeRequest.getProcessQueue(),
                    consumeRequest.getMessageQueue());
}

long offset = consumeRequest.getProcessQueue().removeMessage(consumeRequest.getMsgs());//此代码获取offset时，并不包含  放入RETRY失败的  消息
```
@Jaskey  不知道我是否解释明白了

**Comment by Jaskey** [comment]
@gaoyf ，嗯，已经自己看代码看出来了。rocketMQ在已有的offset机制下，都是已重复去保证消息不丢失的。
