### ISSUE TITLE
自动创建的Topic的用处分别是什么？

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#284]
系统启动的时候，会自动创建一些TOPIC，如集群名称，broker名称，defaultTopic(TBW102)，`OFFSET_MOVED_EVENT`

这些Topic都各自有什么用处？

**Comment by gaoyf** [comment]
1 TBW102作用：如果broker启动时指定autoCreateTopicEnable=true，那么broker中会增加一个topic的配置，topic名字为TBW102， queue默认为8，用于生产消息时，没有创建topic，参照TBW102 的配置创建一个topic，线上不推荐开启此选项。
2 OFFSET_MOVED_EVENT作用：consumer端拉取消息时，传入的offset不合法，比如过大，而队列中还没有相应的消息，那么会将这个 ```offset不合法的消息```  发到OFFSET_MOVED_EVENTt的opic中,
那么只要订阅这个topic就可以知道offset不正确的情况了
3 其他的系统topic不知道啥用处
