### ISSUE TITLE
能配制成外网能访问吗？

### ISSUE THREAD

**Issue by lifubang** [alibaba/RocketMQ#286]
rocketmq能配制成外网能访问吗？

**Comment by Lihuanghe** [comment]
好象不能，目前应该不支持ssl访问。外网有数据泄漏风险

**Comment by lifubang** [comment]
谢谢！那我就不找了。
关于docker的事情，我另开一个issue，麻烦看能否帮忙解答。

**Comment by Lihuanghe** [comment]
我是说可以配置成外网访问，只需要绑定一个外网ip就行。
但数据有安全风险。

**Comment by saaavsaaa** [comment]
目前我的是外网可以访问的，不过正在去掉。。。

**Comment by lifubang** [comment]
嗯。我试了，是可以配置成外网访问的。
我以前是docker部署的，是docker的问题无法外网访问。
#287
