### ISSUE TITLE
把nameSrv，brokerMaster，和brokerSlave都装在docker里面，是不是也没法用？

### ISSUE THREAD

**Issue by lifubang** [alibaba/RocketMQ#287]
rt
#BID	#Addr	#Version	#InTPS	#OutTPS	#InTotalYest	#OutTotalYest	#InTotalToday	#OutTotalToday
0	192.168.42.4:10911	V3_2_6	0.0	0.0	0	0	0	0
1	192.168.42.8:10911	V3_2_6	0.0	0.0	0	0	0	0

broker向nameSrv注册的都是docker的内部地址，这个内部地址192.168.42.4在外部是无法访问的。
是不是rocketMQ无法通过docker部署？

**Comment by vintagewang** [comment]
broker启动的时候可以指定broker的地址

brokerIP1这个参数来指定。
