### ISSUE TITLE
每个消费组自动会听上什么topic?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#288]
重试的时候会把消息放到retry topic, 而delay的消息会放到一个SCHEDULE_TOPIC_XXXX的topic。

是否每个消费组都会听上
1. 自己topic的retry topic
2. SCHEDULE_TOPIC_XXXX topic

还有没有其他？

**Comment by gaoyf** [comment]
1 不会
2 不会
有内部的消费者 定时消费SCHEDULE_TOPIC_XXXX，并将消息发送到原来的topic中

**Comment by Jaskey** [comment]
@gaoyf ，那retry topic呢？ 不听是怎么收到的？ 也是会还原的放到原来的topic中？
