### ISSUE TITLE
放到延时任务的消息，有没有方法删除？

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#289]
延时消息会放到SCHEDULE_TOPIC_XXX中，到时后再放到对应的topic下。

我希望达到某个条件下，删除那个消息避免其投递，broker/store这里有没有方法做到？

**Comment by gaoyf** [comment]
rocketmq所有的消息都存储在队列文件中，没有直接删除消息的方法。
你说的某种条件，可以在消费端判断

**Comment by Jaskey** [comment]
@gaoyf 
由于希望做到去重，在某些场景下我需要删除broker的消息，现在的commit log之类的已有方法（private 也算），没有方法做到删除一条消息？

**Comment by gaoyf** [comment]
你说的这样的情形，与事务消息类似，发送事务消息后，broker反查发送者的状态，状态OK了提交这条消息，状态失败删除这条消息，状态未知就一直反查。
可惜的是rocketmq事务的反查代码没有开源。
