### ISSUE TITLE
关闭服务器写请求时，由于长轮询导致消费者消费延迟

### ISSUE THREAD

**Issue by guoyu9** [alibaba/RocketMQ#29]
有下线服务器需求时，需要关闭服务器的写请求，这样等待消息都过期后再执行下线工作。

问题是如果消费者数目少，那么对应消费的队列数比较多的情况下，一个消费者向被已经关闭了写请求的服务器拉请求时，会被长轮训等待超时才返回，并且一个消费者异步发请求时有信号量的约束，导致消费其他队列的拉请求无法及时发出去。

https://github.com/alibaba/RocketMQ/blob/develop/rocketmq-broker/src/main/java/com/alibaba/rocketmq/broker/processor/PullMessageProcessor.java

case ResponseCode.PULL_NOT_FOUND:
                // 长轮询
                if (brokerAllowSuspend && hasSuspendFlag) {
                    long pollingTimeMills = suspendTimeoutMillisLong;
                    if (this.brokerController.getBrokerConfig().isLongPollingEnable()) {
                        pollingTimeMills = this.brokerController.getBrokerConfig().getShortPollingTimeMills();
                    }

                    PullRequest pullRequest =
                            new PullRequest(request, channel, pollingTimeMills, this.brokerController
                                .getMessageStore().now(), requestHeader.getQueueOffset());
                    this.brokerController.getPullRequestHoldService().suspendPullRequest(
                        requestHeader.getTopic(), requestHeader.getQueueId(), pullRequest);
                    response = null;
                    break;
                }

建议这里的长轮询增加判断当前机器是否有写权限，无写权限则不需要继续长轮询。

**Comment by vintagewang** [comment]
应该没有问题， 消息已经不能写入了， 那么长轮询请求过来  如果没有消息  就会帮hang住， 如果有消息就立刻返回， 符合预期。
