### ISSUE TITLE
windows下broker启动不了

### ISSUE THREAD

**Issue by 1040003585** [alibaba/RocketMQ#290]
已经成功启动了mqnamesrv.exe，保持mqnamesrv.exe运行，这个服务器没关闭。
然后，在另一个cmd终端输入`set NAMESRV_ADDR=127.0.0.1:9876`。
最后在这个终端运行mqbroker不成功：
> E:\Alibaba\alibaba-rocketmq-3.2.6\alibaba-rocketmq\bin>mqbroker
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; sup
port was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128M; suppor
t was removed in 8.0
E:\Alibaba\alibaba-rocketmq-3.2.6\alibaba-rocketmq\bin>

9876端口也没被占用！

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/108
