### ISSUE TITLE
设置了tag code过滤的消息一直没有被消费，会影响同topic的其他消息消费进度？

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#292]
关于消息过滤，假如有一个topic1, 其中C1（绝大部分）都听A 的tag,  而中间有个B的tag发送到了store存起来。

在queue中这样存储了下来：如 A A B A A A A A A A A A 

tag过滤先在broker端进行，扫描consume queue,比较tag的hashcode过滤一遍。消息拉下来后，再客户端再用tag 过滤一遍。所以如果只有C1在监听topic1, B永远都拉不下来。

这样所有的A都被成功消费后，这时候的consumer offset是什么？是不是2？

1. 会不会在消费进度上卡住A Tag的消费进度（update offset）。
2. 后面投递消息的时候，都必须要从B这个位置开始往后找？是否会导致重复消息？一直存在的B会否影响性能

**Comment by gaoyf** [comment]
首先，说一下broker端的consumer offset存储，是类似
topic@consumerGroup<->queue0<->offset
topic@consumerGroup<->queue1<->offset
topic@consumerGroup<->queue2<->offset
其次，对于同一个consumerGroup，其下的每个consumer和topic的queue的关系是，一对多。即一个consumer可以消费多个queue，但是一个queue，只能被一个consumer消费。

通过上面两点，就可以随时知道一个consumer对于某个queue的消费进度。

所以，如果想通过tag来过滤消息，要不就这么写
```
   DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("TopicTestConsumerGroup");
    consumer.subscribe("TopicTest", "TagA || TagB");
    consumer.registerMessageListener(new MessageListenerConcurrently() {
        public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                ConsumeConcurrentlyContext context) {
        	for(MessageExt msg : msgs) {
        		if (msg.getTags() != null && msg.getTags().equals("TagA")) {
        			// 执行TagA的消费
        		}
        		else if (msg.getTags() != null && msg.getTags().equals("TagB")) {
        			// 执行TagC的消费
        		}
        	}
    });
```
要不就执行两个不同的consumerGroup，来订阅同一个topic的不同Tag

你说的tag过滤，是在消费端收到消息后过滤的，tag B的消息已经被拉过来后过滤掉了，那么对于订阅tag A的consumerGroup来说，offset正常前进即可，不受任何影响。

**Comment by Jaskey** [comment]
@gaoyf ,消息过滤按照文本的说法，是在服务端进行的，目的是节省网卡资源。

> 简单消息过滤通过挃定多个Tag 来过滤消息，过滤劢作在服务器迕行。

所以B如果在一直没有被消费的情况下，是不会被投递到消费组，那么进度怎么处理？

**Comment by gaoyf** [comment]
在服务端执行过滤需要启动filterserver，你可以自己研究研究，研究好了共享下啊

**Comment by Jaskey** [comment]
@gaoyf 简单的消息过滤也是服务端进行的，就像文档说的：

> 简单消息过滤通过挃定多个Tag 来过滤消息，过滤动作在服务器进行

在`DefaultMessageStore.java`的getMessage的时候，有一个

                            // 消息过滤
                            if (this.messageFilter.isMessageMatched(subscriptionData, tagsCode)) {


具体过滤的代码是：

```
public class DefaultMessageFilter implements MessageFilter {

    @Override
    public boolean isMessageMatched(SubscriptionData subscriptionData, long tagsCode) {
        if (null == subscriptionData) {
            return true;
        }

        if (subscriptionData.isClassFilterMode())
            return true;

        if (subscriptionData.getSubString().equals(SubscriptionData.SUB_ALL)) {
            return true;
        }

        return subscriptionData.getCodeSet().contains((int) tagsCode);
    }

}
```

只是，我的问题是，在某个topic下的打某个tag的消息如果一直没有消费到，似乎会影响同组其他消息的消息进度和性能。

1. 会不会在消费进度上卡住A Tag的消费进度（update offset）。
2. 如果不会，是不是每次后面投递消息的时候，都必须要从B这个位置开始往后找？是否会导致重复消息？

**Comment by Jaskey** [comment]
@gaoyf 
消息过滤的确是在服务端进行，只是为了避免hash冲突，客户端在拉下来消费前，再过滤了一遍。

tag过滤先在broker端进行，扫描consume queue,比较tag的hashcode过滤一遍。消息拉下来后，再客户端再用tag 过滤一遍。

我的问题是，消费进度（messqgeQueue的）offset，是对于一个队列的，如果这个队列中间的这个B tag的消息一直没有人去消费他，整个进度不就卡住了？

例如，只有一条Q，其中消息这样存储了下来：如 A A B A A A A A A A A A。

第三个B由于没人消费，进度不就一直卡在2了？

**Comment by Jaskey** [comment]
弄明白了，消费进度是针对每隔一个topic@group而言的。

所以如果C1听topic1-TAG1，他的进度的历程是1 ，2，4，5，6，7，8....中间会跳过 **3**。所以C2的3（tag b）一直没有被消费，进度也会继续。

而一旦C2起来，他拉的进度从1开始，但由于只有3匹配上了，所以只拉下来3，并消费成功，他的进度则一下子更新为3。

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
