### ISSUE TITLE
rocketmq Producer 端保证发送消息有序,且发送到同一个队列

### ISSUE THREAD

**Issue by tosilu** [alibaba/RocketMQ#293]
SendResult sendResult = producer.send(msg, new MessageQueueSelector() {
                    @Override
                    public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
                        Integer id = (Integer) arg;
                        int index = id % mqs.size();
                        return mqs.get(index);
                    }
                }, orderId);
当顺序消息的其中一部分发送完毕以后，该队列宕机了，怎么保证后续消息发往同一队列

**Comment by gaoyf** [comment]
应该不能保证
