### ISSUE TITLE
读写队列的数量为什么要分开？

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#295]
TopicConfig下，有readQueueNums, 和writeQueueNums，默认两者相等。

为什么要分开两个两个数量，有什么场景需要两者不想等？

1. readQueueNums大于wriateQueueNums  ---->这样不会听到一些没有消息的queue么？
2. readQueueNums小于wriateQueueNums   --->这样不就有些消息丢了听不到了？

**Comment by gaoyf** [comment]
顺序消息队列扩容保证消息的顺序性：
可以将writeQueueNums增大至需要的queue, 此时消费者readQueueNums还是跟以前一样,所以消费者继续从原先的队列中消费, 等待原先的消息消费完了,将readQueueNums改成和writeQueueNums一样,这样可以保证消息的顺序性

**Comment by Jaskey** [comment]
@gaoyf ， 有无方法动态扩容？ 若增加的消费者已经大于读queue的数量，将无法起到扩容的效果
