### ISSUE TITLE
大量消息堆积后，启动消费者消费，broker堆使用大量上升，gc时间显著增长

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#298]
一主两备，同步双写，异步刷盘。

brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH

使用12个进程持续发送5分钟的消息堆积大量消息，发送结束后，启动一个消费者消费消息。

得到gc log经过分析，在消费后一小段时候后，broker内存堆占用一直上升，无法回收。导致频繁的gc和接近1秒的gc时间。

以下是一个报告：

http://gceasy.io/my-gc-report.jsp?p=L2hvbWUvcmFtL3VwbG9hZC9pbnN0YW5jZTEvc2hhcmVkLzIwMTYtNy0xMS9nY19wdWJhbGxfdGhlbnN1Yi5sb2ctNy0zNi00OA==

使用的是jdk7+g1垃圾回收

**Comment by Jaskey** [comment]
初步怀疑是堆积后快速消费导致大量的`SelectMapedBufferResult`被创建，而`SelectMapedBufferResult`实现了`finalize`方法：

```

    @Override
    protected void finalize() {
        if (this.mapedFile != null) {
            this.release();
        }
    }


    /**
     * 此方法只能被调用一次，重复调用无效
     */
    public synchronized void release() {
        if (this.mapedFile != null) {
            this.mapedFile.release();
            this.mapedFile = null;
        }
    }

```

阻碍了gc快速回收，问题来了，为什么要实现`finalize`而不是手动释放？

如果是这个原因，有什么方法可以解决这个gc问题。

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
