### ISSUE TITLE
求一份最新的文档

### ISSUE THREAD

**Issue by whatsmore** [alibaba/RocketMQ#309]
有没有新一点的文档,不要扔一个很老的很乱的过来

**Comment by whatsmore** [comment]
在https://github.com/alibaba/RocketMQ/issues/1留言过两次了并没有收到任何文档

**Comment by whatsmore** [comment]
@vintagewang @vongosling

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/1

**Comment by onecorner** [comment]
同上，没有收到任何文档！

**Comment by whatsmore** [comment]
@vongosling  发#1有个毛用,根本不会给我发,还关闭问题
