### ISSUE TITLE
How to scale the queue nums when there are more customer instances

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#310]
Now, the number of client instances are at most as same amount as the queue nums, say if I create 10 queues on topicA, if I have 10 clients who subscribes this topic, every client will be given 1 queue to pull message from.

If I want more clients, say I put 10 more clients so that I can consume faster at some special events. 

At this case, the broker will not give queues to 10 clients and there are still only 10 clients who can pull message from.

How to solve this problem?

**Comment by gaoyf** [comment]
You just need to modify route of topic,  `readQueueNums` and `writeQueueNums`.
producer & consumer will rebanlance themselves automatically.

**Comment by Jaskey** [comment]
@gaoyf I mean , how to dymatically change it, how can I know when will my clients put more customers.

**Comment by gaoyf** [comment]
you need to change it by hands, like the following two ways: 
1 the following script:
```
[test bin]# ./mqadmin updateTopic
usage: mqadmin updateTopic [-b <arg>] [-c <arg>] [-h] [-n <arg>] [-o <arg>] [-p <arg>] [-r <arg>] [-s <arg>]
       -t <arg> [-u <arg>] [-w <arg>]
 -b,--brokerAddr <arg>       create topic to which broker
 -c,--clusterName <arg>      create topic to which cluster
 -h,--help                   Print help
 -n,--namesrvAddr <arg>      Name server address list, eg: 192.168.0.1:9876;192.168.0.2:9876
 -o,--order <arg>            set topic's order(true|false
 -p,--perm <arg>             set topic's permission(2|4|6), intro[2:R; 4:W; 6:RW]
 -r,--readQueueNums <arg>    set read queue nums
 -s,--hasUnitSub <arg>       has unit sub (true|false
 -t,--topic <arg>            topic name
 -u,--unit <arg>             is unit topic (true|false
 -w,--writeQueueNums <arg>   set write queue nums
```
2 https://github.com/rocketmq/rocketmq-console
