### ISSUE TITLE
Replace native CRC alrightom with PureJavaCrc？are you sure?

### ISSUE THREAD

**Issue by suhuaguo** [alibaba/RocketMQ#312]
why don't find this class file? PureJavaCrc32.java

**Comment by vongosling** [comment]
PureJavaCrc32 has been widely used in other project,such as snappy ,kafka. can you tell me,what's  your use

**Comment by suhuaguo** [comment]
RocketMQ 3.4.6 cant't find PureJavaCrc32.java。but release notes write 'Replace native CRC alrightom with PureJavaCrc' .
