### ISSUE TITLE
Auto queue scaling support

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#313]
Refereing to #310, we need to scale queue nums by hand which is not realistic for many cases since as a mq provider, we don't know how many and when client instances are put into use. 

Need support for auto scaling.

**Comment by lizhanhui** [comment]
As I commented on this thread: https://github.com/alibaba/RocketMQ/issues/316, you can create an operation tool yourself. Considering the existing administrating commands, this involves very limited efforts to develop.

**Comment by vongosling** [comment]
Give you one example 
    mqadmin updateTopic -t helloworld -n 127.0.0.1:9876 -w 16 -r 16
If you have any question on how to use mqadmin updateTopic,please input this command to resort to help
