### ISSUE TITLE
How to decide how many queues to provide?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#315]
1. Is there any criteria that how many queues should provide?
2. There is a benchmark topic with 1024 queues, should we not privide more than 1024 queue?
3. Should the queue number be the power of 2?

**Comment by lizhanhui** [comment]
1. It depends on how many consuming clients you are going to have.  Number of queues should be greater than that of consumers.
2. There is no constraint on number of queues you may have.
3. No, it does not need to be power of 2.

**Comment by Jaskey** [comment]
@lizhanhui But more queue will give more burden to the broker , won't it?

**Comment by lizhanhui** [comment]
1. No idea how many consumers are in operation? 
2. Actually No. The amount of messages being sent per second matters. Given the sending/consuming speed is constant, impact of increasing/decreasing queue number is minor.
3. No. Being power of 2 or not has not relation with performance at all.

**Comment by Jaskey** [comment]
@lizhanhui 

Referering to point 2, more queues will result in more files to be created and maintain, and it also enlarge the heartbeat data transfering from broker to namesrv and namesrv to all clients, won't it?  Or Rocket MQ will give a large enough value say (10 000) as a default value.

**Comment by lizhanhui** [comment]
As I said previously, it did has some influences. But the influence it brings about is minor acknowledging the frequency of heartbeat is low and normal number of queues is usually not very large.

Defaulting to a large number, 10, 000 as you suggested, is forbiddingly bad. If you are building something related to IoT which assumes large number of clients but low TPS, it's advisable to have front-end connection managers, acting as liaison between RocketMQ and mobile carrier.
