### ISSUE TITLE
Will message will lose/not be consumed anymore if I descrise the queue numbers.

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#316]
For example if I have 10 messages in 10 consume queues. If I descrease the queue numbers(both readnum and writenum) into 5.

Will the 5 messages(from Q5 and Q9) lose or not be consumed anymore?

If yes, when is the safe time to descrese queue numbers.

**Comment by lizhanhui** [comment]
If changing read queue number regardless of consuming progress, messages are at risk of being lost. 

Correct way to decrease number of queue, to my knowledge, is first decrease number of writing queue; wait till all messages in the to-be-dropped queues are consumed by all consume groups; decrease the read queue number.

**Comment by vongosling** [comment]
why should you make this action?whenever you want to scale out or shrink off ,the first important thing you must be care is,please,considering you in-queue.in this case ,that is writing action.
