### ISSUE TITLE
sh install.sh 之后 启动出错 Error: Could not find or load main class com.alibaba.rocketmq.namesrv.NamesrvStartup

### ISSUE THREAD

**Issue by kalsolio** [alibaba/RocketMQ#318]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=320m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Error: Could not find or load main class com.alibaba.rocketmq.namesrv.NamesrvStartup

**Comment by dannyrz** [comment]
me too

**Comment by YuYin** [comment]
？

**Comment by Jack2code** [comment]
+1
