### ISSUE TITLE
同一个group多个consumer中的一个宕机消费的queue没有自动切换

### ISSUE THREAD

**Issue by lindzh** [alibaba/RocketMQ#322]
同一个group的其中一个consumer服务挂掉，其所消费的queue没有自动负载均衡到其他consumer，导致消息堆叠很多

**Comment by lindzh** [comment]
![image](https://cloud.githubusercontent.com/assets/5078928/17453983/60dcb44c-5bba-11e6-8014-9f06d91d1728.png)
![image](https://cloud.githubusercontent.com/assets/5078928/17453985/7b2bd940-5bba-11e6-8cda-cddb4fc563ee.png)

**Comment by vongosling** [comment]
please use english.please check our description on how to answer
