### ISSUE TITLE
Should the instance name be explicitly set?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#327]
If we leave the instance name default, it will be change to pid, as result , the client id will be ip@pid.

If we have multiple producers(say p1, ) or consumers(c1, and c2) in the same process at the same machine, it will share the same clientid. 

Question:

1. Do all instance with same client id shares the same channel? If yes, does shutdown one instance, say p1, will shutdown c1 and c2 too?

2. Is it a best practice to explicityly set a unique instance name for all instance(produer or consumer)

3. Should producer and consumer in the same jvm process uses different instances name?

**Comment by Medusar** [comment]
Exception will be thrown if you have multiple consumer with same topic and and same instance name in one JVM

**Comment by Jaskey** [comment]
@Medusar what about producer and consumer, if an application both sends and recieve message, should they use different instance name?  If I use the same one, will they share the same channel?

**Comment by vongosling** [comment]
@Jaskey one instance per JVM instance.that's our recommended practice.but,if you want to be producer and consumer coexist in one jvm forcly, instanceId must to be set.

**Comment by Jaskey** [comment]
@vongosling 

Our systems will always send and recieve message at the same time. 

If I hopes they share the same channel, can I make it a same instance name.: ip@pid-systemid? Will this cause some problem?

**Comment by vongosling** [comment]
you can diff. it with some prefix or postfix.such as producer \consumer.you'd better not to design the same instanceName

**Comment by Jaskey** [comment]
@vongosling  Would you please tell me if I share the same instance name, do they share the same channel. Since from the console, I can see the client addr is the same if I share the same instance name.
