### ISSUE TITLE
想在书籍中引用RocketMQ项目中的部分图片、文字、代码

### ISSUE THREAD

**Issue by waylau** [alibaba/RocketMQ#330]
首先，感谢阿里巴巴中间件团队对于RocketMQ所做的努力。
 个人目前正在编写一本分布式系统的书籍（<https://github.com/waylau/distributed-systems-technologies-and-cases-analysis>），其中有一个章节是专门介绍市面上流行的消息队列框架，打算引入RocketMQ产品作为其中独立的一个章节，其中会引用RocketMQ项目wiki、《RocketMQ开发指南》中的部分图片、文字、代码等。另一方面，可以通过书籍可以让更多人了解到RocketMQ这款产品。 请问，这样做是否允许？

另外，如果允许我引用RocketMQ，是否还有其他资料可供参考？看了项目wiki貌似内容还是比较少。

感谢！

**Comment by vintagewang** [comment]
可以， 说明出处即可。

**Comment by vongosling** [comment]
关于书籍引用这块，我们聊聊吧，我的qq：3527554

**Comment by waylau** [comment]
@vongosling  已经加你了，通过下（QQ:778907484）

**Comment by waylau** [comment]
@vongosling 之前QQ联系您，但好像您那边一直没有回复。所以还是这里讨论比较及时。下面是这个样书中 关于 RocketMQ 章节部分的内容。您可以给下意见。

<https://github.com/waylau/distributed-systems-technologies-and-cases-analysis/blob/master/images/3.3%20rocketmq.jpg>

主要是想确认几方面内容：
1. 书中这样引用，是否会造成侵权？如果是如果改进才能避免这方面的纠纷？；
2. 书中的内容排布是否合理？对于读者来说，是否是好的入门教程？如果否，如何改进？

本人对于 RocketMQ 也是初学，这个书主要是技术普及、推广类型的，所以技术不会涉及的很深，内容主要还是取材于你们的文档。也想为国内的开源事业出份小力。

期待你们的回复。

**Comment by vongosling** [comment]
1. 快速那个词改成低延迟吧，主页上那个英文单词，我后面会改掉
2. RocketMQ是MetaQ的下一代产品，几乎重写了所有核心组件，基于这个词不是很合适

**Comment by waylau** [comment]
@vongosling 

感谢您的建议！

您提到的这些内容会在书的终稿中进行修改。

**Comment by vongosling** [comment]
稍等，我还没看完呢，只是先记录下来

**Comment by waylau** [comment]
@vongosling  没事，我离终稿估计还有3周左右的时间，期间你都可以提意见。到时，我一并放到终稿里面去。
