### ISSUE TITLE
请问最新的MQ在启动的时候报错: 找不到或无法加载主类 com.alibaba.rocketmq.namesrv.NamesrvStartup

### ISSUE THREAD

**Issue by smj227227** [alibaba/RocketMQ#334]
环境配置如下：
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64
export ROCKETMQ_HOME=/usr/local/MQ 
export PATH=$PATH:$JAVA_HOME/bin:$ROCKETMQ_HOME/bin
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
报错：
    错误: 找不到或无法加载主类 com.alibaba.rocketmq.namesrv.NamesrvStartup

**Comment by vongosling** [comment]
please using english

**Comment by HuangTengyu** [comment]
I have read many articles ,no more about this problem
