### ISSUE TITLE
How to resend message to the origin topic rather than retry topic when consuming failly?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#335]
1. Now, if a message is cosumed failly, the message to be send back to retry topic of the entire group, why not directly resend to the origin topic? What is the desgin purpose? 

Since If I resend it to origin topic, this message will consumed again by the same instance. 

2. If I really want to resend this message to the origin topic, is there any way to achieve this?  Maybe modify the source code? Is it safe to modify below code in broker's `SendMessageProcessor`'s `consumerSendMsgBack`

            String newTopic = MixAll.getRetryTopic(requestHeader.getGroup());

**Comment by gaoyf** [comment]
1 The consumed failed message will be sended to the topic of **SCHEDULE_TOPIC_XXXX** first, then **ScheduleMessageService** will consume this message at some time later and resend it to the topci of **%RETRY%your_consumer_group**. 
2 **your_consumer_group** actually subscribe the topic of **%RETRY%your_consumer_group** at the time you subscribe your topic, so you can receive the failed message again.
3 The more failed times of comsuming this message, the longer interval of sending it to retry topic. At last, the failed message will be sended to %DLQ% queue and no one will consume it。

My English is not very well, if your cannot understand you can ask in Chinese.

**Comment by Jaskey** [comment]
@gaoyf Thank you for your answer. But I can totally understand what you try to describe.

But my question is , why to design a extra topic %RETRY%your_consumer_group, rather than directly resend to the origin topic(passed by schedule topic with delay).

To the origin topic , I can make the message be consumed by the same instance again. But with retry topic, this message can only be consumed by the first instance(sort index =0) by default.

Now, my problem is if I want it to resend to the origin topic, is there an easy way to do that?

**Comment by lizhanhui** [comment]
"But my question is , why to design a extra topic %RETRY%your_consumer_group, rather than directly resend to the origin topic(passed by schedule topic with delay)." This is because a topic may be subscribed by multiple consumer groups. If you resend the message back to the original topic, all consumer groups subscribing the topic will re-consume the message again, which is obviously not desired.

**Comment by lizhanhui** [comment]
"To the origin topic , I can make the message be consumed by the same instance again. But with retry topic, this message can only be consumed by the first instance(sort index =0) by default." Is there any special advantage if  "he message be consumed by the same instance again"? Business servers would better be stateless. And normally, you won't have too many retry-messages. 


"But with retry topic, this message can only be consumed by the first instance(sort index =0) by default.", This depends on your queue allocating algorithm, you may use your own assigning algorithm.

**Comment by lizhanhui** [comment]
"Now, my problem is if I want it to resend to the origin topic, is there an easy way to do that?" If you understand the design properly, you won't want to do this any more.

**Comment by Jaskey** [comment]
@lizhanhui Thank you for your comments.  Got this desgin purpose now.
