### ISSUE TITLE
What is topic "OFFSET_MOVED_EVENT" is used for

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#337]
When I look into the code for select message from consume queue,  I find that a message will be put into this topic when below 3 conditions happen:

1.1 max offset = 0(NO_MESSAGE_IN_QUEUE)  || no match queue(NO_MATCHED_LOGIC_QUEUE)
1.2 request offset !=0
1. offset too small
2. offset overflow badly

queustions:
1. How to use the topic to fix these bad request ?

**Comment by lizhanhui** [comment]
Consumer Client, DefaultMQPushConsumerImpl line#442 has logic to correct illegal offsets.  Make sure you have read the source code thoroughly.

**Comment by Jaskey** [comment]
@lizhanhui I know this fixup at DefaultMQPushConsumerImpl it will correct it into nextOffset returns from broker.

1.Then what is this topic is used for?
2.If I use PullConsumer, can I make use of this topic or just do something like push consumer does

**Comment by lizhanhui** [comment]
1. "Then what is this topic is used for?", I do not understand what you are talking about.
2. "If I use PullConsumer, can I make use of this topic or just do something like push consumer does" -->  Though I do not understand what "can I make use of this topic" means, yep, you need to do something similar to what push client does in case you are using pull.
