### ISSUE TITLE
Why give the extra 4 bytes to the ByteBuffer when encodeing?在通信编码的时候，给ByteBuffer多分配了四个字节，很好奇为啥这样设计呢？

### ISSUE THREAD

**Issue by HaoChou** [alibaba/RocketMQ#339]
in the method encode() of RemotingCommand.java ,there is a line as follow:
ByteBuffer result = ByteBuffer.allocate(4 + length);
and int the method decode() of RemotingCommand.java, there is a line as follow:
int bodyLength = length - 4 - headerLength;

I wonder why give the extra 4 bytes in the ByteBuffer which is encoded ? And why ignore the 4 byte when decoding?
thanks

在RemotingCommand.java的encode()方法里有这么句代码：
ByteBuffer result = ByteBuffer.allocate(4 + length);
在decode方法里有这么句：
int bodyLength = length - 4 - headerLength;

我很好奇为什么在编码的时候要多分配四个字节，然后解码的时候又忽略这四个字节呢？
是有啥目的吗~
谢谢查看我的提问，期待您的回答~

**Comment by vongosling** [comment]
total length，please using english next time

**Comment by HaoChou** [comment]
sorry. It is my mistake to misunderstand the code~ : - )
