### ISSUE TITLE
What is topic with name of clusterName/brokerName used for?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#342]
In broker config, it will create topic of broker name and cluster name by default:

        private boolean clusterTopicEnable = true;
        private boolean brokerTopicEnable = true;

But what are these two topic is used to ? What if I set these two config to false, are there any risks?

**Comment by vongosling** [comment]
You can ignore it now(whether true or false.doesn't matter).it just for availability guarantee，similar activemq advisory messages

**Comment by Jaskey** [comment]
@vongosling I have these topics created at my prod env, is it safe enough to delete these topics and disable these two options?
