### ISSUE TITLE
com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt中笔误

### ISSUE THREAD

**Issue by hiant** [alibaba/RocketMQ#345]
com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt#398
应将
`
return defaultMQAdminExtImpl.cleanUnusedTopicByAddr(cluster);
`
修改为
`
return defaultMQAdminExtImpl.cleanUnusedTopic(cluster);
`

**Comment by vongosling** [comment]
thank you
