### ISSUE TITLE
 Full-dose messages subscription suports.

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#349]
I need a monitor who collects all messages that send to broker, but the topics may grow , so I need somthing like consumer.subscripbe("*") to subscribe all topics, is there any way to do this now?

**Comment by lizhanhui** [comment]
Your mentioned approach would bring about very heavy overhead.  What do you want to monitor? Some customized statistical data? If so, you may refer to existing implementation of collecting statistical data and implement your own customized ones.

**Comment by Jaskey** [comment]
@lizhanhui , the case will be used when my clients reports some duplicated messages or message loss, we can find that message from my backup process, and find the problem, it need not be consume fast, but this is a nessasary need in our properctive.

**Comment by lizhanhui** [comment]
Doing what you suggest won't help at all in terms of duplicate-message issue. It's completely possible that clients of consumer group A sees duplication whilst those of group B do not given two groups share exactly same subscription. 

Message loss is virtually not a valid issue given prerequisites are met, say disks are flushed synchronously, replication is sync. Further, I do not see how your proposal could relieve such issue in any way, should it exist.
