### ISSUE TITLE
In producer transaction message, msgId get by producer is different from that get by consumer

### ISSUE THREAD

**Issue by beston123** [alibaba/RocketMQ#352]
In producer transaction message test case, why the returned msgId from RocketMQ is different from msgId recevied by consumer?

Producer:
> msgId=C0A87C3400002A9F000000000005DF12, status=SEND_OK, localTransactionState=COMMIT_MESSAGE

Comsumer:
> ConsumeMessageThread_2 Receive New Messages: C0A87C3400002A9F000000000005DFC5

**Comment by lizhanhui** [comment]
This is because the prepared message is duplicated, (props)modified and appended to the store on committing.

**Comment by beston123** [comment]
It is not convenient  to find the relationship between the prepared message and the consume received message。So the producer should get the committed message id。

**Comment by lizhanhui** [comment]
Using a custom unique business key is more preferable.
