### ISSUE TITLE
How to become a RocketMQ committer 

### ISSUE THREAD

**Issue by zhouxinyu** [alibaba/RocketMQ#353]
Hi, Everyone

RocketMQ is coming to embrace world, and we need some committers to help us make RocketMQ become better. We have proposed some contribution points at [here](https://github.com/alibaba/RocketMQ/wiki/how-to-be#becoming-a-committer). If you have any interest, please let us know.
### How to Apply?

Just reply this issue with the specified format, like:

Name: Xinyu Zhou
Company: Alibaba Group
Email: zhou@xinyu.im
Interest: RocketMQ Console

Tips: You can use your real name or nick name, but the company and email must be real.

**Comment by vagile-cn** [comment]
Name: Ming Wen
Company: vznet
Email: vagile@foxmail.com
Interest: RocketMQ .Net SDK

**Comment by jerrysearch** [comment]
Name: jerry
Company: 700Bike
Email: search.jerry@gmail.com
Interest: RocketMQ Console

**Comment by syzjava** [comment]
Name: syzjava
Company: leshi
Email: syzjava@gmail.com
Interest: RocketMQ

**Comment by Zhang-Ke** [comment]
Name: ZhangKe
Company: ThoughtWorks
Email: zhangke_beijing@qq.com
Interest: RocketMQ Replicator((MySQL or Redis or MongoDB))

**Comment by Zhang-Ke** [comment]
Name: ZhangKe
Company: ThoughtWorks
Email: zhangke_beijing@qq.com
Interest: RocketMQ Replicator((MySQL or Redis or MongoDB))

**Comment by xuhaoliang** [comment]
Name: sun
Company: BaiLian
Email: haoliang.xu1984@gmail.com
Interest: RocketMQ,RocketMQ Console,RocketMQ Redis

**Comment by zhaoqun1021** [comment]
Name: Zhao Qun
Company: HuaLing
Email: 911@zhaoqun911.cn
Interest: RocketMQ MySQL/Redis Replicator

**Comment by Jaskey** [comment]
Name: Linjunjie
Company: Netease
Email: linjunjie1103@gmail.com
Interest: RocketMQ

**Comment by syzjava** [comment]
Name: syzjava
Company: leshi
Email: syzjava@gmail.com
Interest: RocketMQ Console

**Comment by myparamita** [comment]
Name: Zhenxing LV
Company: HuiAnRong
Email: lzx1221@qq.com
Interest: MQ

**Comment by lizhanhui** [comment]
Name: Li Zhanhui
Company: YeahMobi
Email: lizhanhui@gmail.com
Interest: Wiki & JavaDoc

**Comment by carlislelee** [comment]
Name: Carlisle Lee
Company: 360
Email: carlisle.lee.exe@gmail.com
Interest: RocketMQ MongoDB

**Comment by wuguangxue** [comment]
Name: WuGuangxue
Company: Hylanda
Email: 329613403@qq.com
Interest: RocketMQ MongoDB/Redis Replicator

**Comment by liuweidong07** [comment]
Name: liuwd
Email: 740255035@qq.com
Interest: RocketMQ MySQL

**Comment by githubzy** [comment]
Name: kmhmh
Company: INFOGEM TECHNOLOGIES
Email: peijuez@163.com
Interest: RocketMQ Redis

**Comment by handmail** [comment]
Name: Json
Company: AisaInfo
Email: 56012282@qq.com
Interest: RocketMQ Console

**Comment by tanjxcn** [comment]
Name: dyfh
Company: gooagoo
Email: 1318308616@qq.com
Interest: RocketMQ Redis/Console

**Comment by chen110xi** [comment]
Name: Ethan
 Email: chen110xi@qq.com
 Interest: RocketMQ .Net SDK

**Comment by xiaoerlyl** [comment]
Name: Liang Yunlong
Company: iQIYI
Email: liangyunlong1008@163.com
Interest:  Wiki & JavaDoc

**Comment by zhaozhenzuo** [comment]
Name: zhenzuo Zhao
Company: Tongbanjie
Email: zhaozhenzuo@126.com
Interest: RocketMQ

**Comment by lvhonglei1987** [comment]
Name: HongLei Lv
Company: qccr
Email:lvhonglei@qccr.com
Interest: MySql Redis RocketMQ

**Comment by Hujifang** [comment]
Name: Linghu Chong
Company: Oneplus
Email: hujifang967@gmail.com
Interest: RocketMQ Console

**Comment by madaoguteng** [comment]
Name: CaoJun
Company: cms
Email: 375304941@qq.com
Interest: RocketMQ MySQL/Redis Replicator

**Comment by gaoyf** [comment]
Name: gaoyf
Company: sohu
Email: 554312685@qq.com
Interest: Wiki & JavaDoc RocketMQ Console

**Comment by XadillaX** [comment]
Name: XadillaX
Company: Souche Inc
Email: i@2333.moe
Interest: RocketMQ Node.js SDK & ONS Node.js SDK

something like https://github.com/XadillaX/aliyun-ons

**Comment by lusong1986** [comment]
Name: lusong
Company: hengda
Email: 404828407@qq.com
Interest: RocketMQ  & RocketMQ Console

**Comment by wenweihu86** [comment]
Name: wenweihu86
Company: baidu.com
Email: wenweihu86@163.com
Interest: RocketMQ

**Comment by fofcn** [comment]
Name: jiquanxi
Company: fanzhuankeji
Email: errorfatal89@gmail.com
Interest: RocketMQ & RocketMQ Console

**Comment by gunsluo** [comment]
Name: jerrylou
Company: gome
Email: gunsluo@gmail.com
Interest: RocketMQ Golang SDK

**Comment by LazyLei** [comment]
Name: LazyLei
Company: mogujie
Email: ireflux@163.com
Interest: RocketMQ & RocketMQ Console & replicator

**Comment by dyfhwings** [comment]
Name: dyfh
Company: gooagoo
Email: 1318308616@qq.com
Interest: RocketMQ Redis Replicator

**Comment by wayshall** [comment]
Name: mat
Company: yooyo
Email: pistols@qq.com
Interest: RocketMQ Console

**Comment by Evelyn1122** [comment]
Name: Evelyn
Company: ChinaUnicom
Email: 8186248@qq.com
Interest: RocketMQ Console & RocketMQ MySQL(Oracle\Redis\HBase) Replicator &少量wiki

**Comment by JoshuaAndrew** [comment]
Name: weiwei
Company: Isoftstone Inc.
Email: chweiweich@163.com
Interest: RocketMQ Console & RocketMQ MySQL(Oracle\Redis\HBase) Replicator

**Comment by luoliang222** [comment]
Name: luoliang
Company: shengu cekong
Email: szluoliang@foxmail.com
Interest: RocketMQ MySQL PostgreSQL Redis Replicator

**Comment by smellmine** [comment]
Name: smellmine
Company: i99yun.com
Email: 405936440@qq.com
Interest: RocketMQ MySQL MongoDB

**Comment by a2888409** [comment]
Name: Qianzhenyu
Company: dianhun
Email: 122274659@qq.com
Interest: Redis Replicator/Wiki & JavaDoc

**Comment by jongyoul** [comment]
Name: jongyoul
Company: NFLabs. ZEPL
Email: jongyoul@gmail.com
Interest: RocketMQ/RocketMQ console

**Comment by 1964405262** [comment]
Name: shiwentao
Company: beibei
Email: 1964405262@qq.com
Interest: RocketMQ/RocketMQ console

**Comment by node** [comment]
Name: node
Company: vivo
Email: nodexy@gmail.com
Interest: Wiki & JavaDoc, Python SDK

**Comment by IT-ProfessorX** [comment]
Name: IT-ProfessorX
Company: 100credit.com
Email: 510655387@qq.com
Interest: RocketMQ store/RocketMQ broker

**Comment by shroman** [comment]
Name: [shroman](https://github.com/shroman)
Company: CyberAgent, Inc.
Email: rshtykh@yahoo.com
Interest: RocketMQ internals, console, Apache Ignite Replicator

**Comment by catslave** [comment]
Name: catslave
Company: rekchina
Email: yangjj@rekchina.com
Interest: RocketMQ Go SDK

**Comment by wwenfeng** [comment]
Name: Wenfeng Wang
Company: JD Group
Email: sxian.wang@gmail.com
Interest: Wiki & JavaDoc / RocketMQ SDK(Go)

**Comment by keeping-action** [comment]
Name: Guoping Zhang
Company: 58
Email: guoping_zhang@sina.cn
interest: RocketMQ store/RocketMQ broker

**Comment by qqeasonchen** [comment]
Name: Eason Chen
Company: Tencent
Email: daerduochen@qq.com
Interest: RocketMQ ALL
