### ISSUE TITLE
Bug logs reports from slave: [BUG]logic queue order maybe wrong, expectLogicOffset: 3780 currentLogicOffset: 5280 Topic: token-0000 QID: 0 Diff: -1500]

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#354]
I happen to have some bug log like 

```
[BUG]logic queue order maybe wrong, expectLogicOffset: 3780 currentLogicOffset: 5280 Topic: token-0000 QID: 0 Diff: -1500]
```

Does it mean rockect mq have run into some bugs? When will this log happens, what will be the possible cause?

Is it releated to the auto commit logs deletion ?

**Comment by vongosling** [comment]
version? If you have question,please conform to https://github.com/alibaba/RocketMQ/issues/108

**Comment by Jaskey** [comment]
@vongosling , version 3.2.6 

What will be the possible cause ? Is it fall into some edge case?

**Comment by Jaskey** [comment]
@vongosling any updates?

**Comment by lizhanhui** [comment]
Obviously, your broker has run into inconsistent state.  Where is this log from? Master broker or slave? Is there any other related error or warn log?

**Comment by Jaskey** [comment]
@lizhanhui , this is from slave . 

For more logs,  please refer to https://github.com/alibaba/RocketMQ/issues/351#issuecomment-248193983

**Comment by lizhanhui** [comment]
"Here are some logs I collected from broker and clients, for some security reasons, I can't get the log out of my machine, I can only provide some hints where the code flow goes to." 

I wish I could help but I do not think I can make it without detailed log.

**Comment by Jaskey** [comment]
The logs are huge, and I can't get all of it, the error and warnning logs are all provided. Would you just try to guess where goes wrong and we will try to reproduce it in our test env.

**Comment by liuliuwd** [comment]
I has also encountered this problem , without slave cluster.

**Comment by Jaskey** [comment]
Guess the reason is like https://github.com/alibaba/RocketMQ/issues/359 , which this topic is deleted before but the consume queue files exists in slave, so master will have different consume queue files with slave.

@vongosling , slave will possibly has unconsistent consume queue with master when recreating deleted topic , is this a bug?

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)
