### ISSUE TITLE
RocketMQ接入权限控制功能

### ISSUE THREAD

**Issue by yupengmail2012** [alibaba/RocketMQ#355]
RocketMQ目前还没有接入权限控制的功能，所以无法直接部署在公网上使用，希望能够尽快提供这部分功能，以便RocketMQ可以成为移动业务的消息处理工具。
另外，希望RocketMQ支持HTTP协议的接入，支持RestFul API，谢谢。

**Comment by vongosling** [comment]
If you have some requirement,please look for some committer to collaborate from here https://github.com/alibaba/RocketMQ/issues/353
