### ISSUE TITLE
关于kafka和rocketmq 顺序性对比

### ISSUE THREAD

**Issue by z7658329** [alibaba/RocketMQ#356]
https://github.com/alibaba/RocketMQ/wiki/rmq_vs_kafka
有看到关于kafka和rocketMq的对比的一项：
**Kafka支持消息顺序，但是一台Broker宕机后，就会产生消息乱序**
问题：
为什么说broker宕机会造成消息乱序，根据kafka特性，replicate会被选举新的leader，对于consumers来说，触发rebalance，但是消息为何就乱序了？是不是您这边理解的乱序可能是以下这种情况：假设rebalance后，对于某个消费者组来说，part1由consumer1消费变为了consumer2消费，这就产生了消息乱序？

**Comment by z7658329** [comment]
@vongosling  ??why？

**Comment by vongosling** [comment]
please use english.if you prefer chinese,please go into our qq group

**Comment by kaybinwong** [comment]
what's the qq group number? @vongosling
