### ISSUE TITLE
How to use OFFSET_MOVED_EVENT to fix wrong pull offset

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#357]
If broker detected a PULL_OFFSET_MOVED result, it will generate a OFSET_MOVED_EVENT.

How could I use thie message and , should I monitor this and take actions?

**Comment by gaoyf** [comment]
You can implement `MonitorListener` for monitoring undone, failed and deleted messages.
FYI `MonitorService`.

**Comment by Jaskey** [comment]
It will report some logs for offset moved event, then what should I take actions?
