### ISSUE TITLE
why not clear consumequeue redundant data when commitlog recover normally. Sometimes commitlog recover failed because magic code illegal or CRC check failed.

### ISSUE THREAD

**Issue by liuliuwd** [alibaba/RocketMQ#358]
this will cause consumequeue  max physicOffset not equaled with commitlog  writeposition.

**Comment by Jaskey** [comment]
@liuliuwd , I am suffering the same problem that commit log and consume queue are inconsistent, what's your cause and is there any logs or problematic phenomenon ?
