### ISSUE TITLE
[BUG] pull message result maybe data wrong, nextBeginOffset: 2433072 firstMsgOffset: 843377 prevRequestOffset: 2433064

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#360]
From client logs, happens to meet this problem:

    [BUG] pull message result maybe data wrong, nextBeginOffset: 2433072 firstMsgOffset: 843377 prevRequestOffset: 2433064

This log will continous logged , and very quickly.

From the source code, this will be logged when the pulled message's offset is small when what was intended to pull.

What will the possible cause for this issue?

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/108
