### ISSUE TITLE
Please add unimplemented methods in rocketmq-broker/MockMessageStore

### ISSUE THREAD

**Issue by JoshuaAndrew** [alibaba/RocketMQ#362]
@author qinan.qn@taobao.com

Please add unimplemented methods in rocketmq-broker/MockMessageStore  rocketmq-v3.5.8

public class MockMessageStore implements MessageStore{

      @Override
	public long getEarliestMessageTime() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public long lockTimeMills() {
		// TODO Auto-generated method stub
		return 0;
	}
}

**Comment by vongosling** [comment]
what's problem do you have
