### ISSUE TITLE
[BUG] consumer shutdown function have the problem of  duplicate consumption

### ISSUE THREAD

**Issue by a11123939** [alibaba/RocketMQ#367]
3.4.6 version consumer shutdown 有重复消费的问题。
DefaultMQPushConsumerImpl 
  `        this.consumeMessageService.shutdown();
            this.persistConsumerOffset();
            this.mQClientFactory.unregisterConsumer(this.defaultMQPushConsumer.getConsumerGroup());
            this.mQClientFactory.shutdown();
            log.info("the consumer [{}] shutdown OK", this.defaultMQPushConsumer.getConsumerGroup());
            this.rebalanceImpl.destroy();
            this.serviceState = ServiceState.SHUTDOWN_ALREADY;`

consumeMessageService.shutdown() is not block function ，
persistConsumerOffset is before consumeMessageService shutdown。

because of consumeMessageService have a ThreadPool，ThreadPool shutdown is just a signal，
ThreadPool may shutdown after a few seconds
 this.consumeExecutor.shutdown();

**Comment by lizhanhui** [comment]
Message delivery semantics of RocketMQ is at-least-once. Duplication issue is left to business developers.

**Comment by a11123939** [comment]
consumer shutdown function 
persistConsumerOffset()  is before consumeMessageService.shutdown().
it is mean when consumer shutdown , have update ConsumerOffset but consumeMessageService still running and consumer message , these messages  should not be repeated consumption.
it is consumer bug

**Comment by lizhanhui** [comment]
First, I am crystal clear your reporting.

As I said, the delivery semantics is at-least-once. Thus, there is not need to await termination of message-consuming thread pool. The update-consumer-offset operation here is a good yet actually non-mandatory effort to minimize duplication, let alone what you described above.

Conclusion: It's NOT a bug.

**Comment by Jaskey** [comment]
@a11123939 this is not a bug , since rocket mq does not garanteer that consumer will not have duplicate messgae. 

Indeed, shutdown the thread pool does not stop consuming messages, so these message may possilily consume again after restart.

You can have your code modified like:

        this.consumeExecutor.shutdown();
        while(!consumeExecutor.isTerminated()){
			try {
				consumeExecutor.awaitTermination(50, TimeUnit.MILLISECONDS);
			} catch (InterruptedException e) {
			}
        }

to await all consuming before persisit consumer offset

**Comment by crossz** [comment]
The test is easy. 
As I tested, we can tell the offset updated or not by check "consumer.fetchConsumeOffset(mq, true)". 

If this number change back to an offset which has been treated by consumer, this tells something wrong with the effort update back to remote.
