### ISSUE TITLE
probably send timeout at 4am when deleting commit log files

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#368]
I happen to meet at these days that the producer will have 1000ms send timeout"wait response timeout 1000ms" at around 4am, which is the time to clean commit log.

Also, from my own monitor app, which will count the time cost of sender to produder every hour, the cost is inscreasing from 4:00am to 5:00 am

Will cleaning commit log affect the main processor of send message or pulling message?

PS:  

1 . version 3.2.6 with 100ms clean interval and 48 hours file reserve time.
2.  There are more than 30GB commit log will be expired every day.

**Comment by Jaskey** [comment]
@vongosling any update or comments?

**Comment by Jaskey** [comment]
I find that if I set the file reserve time down to 1 hour, and clean the commit log at every hour by setting `deletewhen=00;01;02;03;04;05;06;07;08;09;10;11;12;13;14;15;16;17;18;19;20;21;22;23;`

The monitor app does not report any  high-time cost issue in all day , which seems to prove that this is caused by large amount deletion. 

Any advise on this? @vongosling

**Comment by vongosling** [comment]
Indeed affect in your version.you can update the latest version. Or, by your way.but you must ensure your message‘s account of the heap up not more than 1 hour(as your config)

**Comment by Jaskey** [comment]
@vongosling that config is just for test, we can't set that config in our prod env.

It seems that the later version had fix this issue. would you please point out that which version excatly fix this(I am using 3.2.6), and which part of code are fixing this, so that we go through the changes and how.

**Comment by Jaskey** [comment]
@vongosling 

I also tested that set deleteCommitLogFilesInterval to larger value ,500ms, which does not have better effect.

**Comment by Jaskey** [comment]
@vongosling 

any update on thsi?

**Comment by Jaskey** [comment]
I do more tests : 

I back up the store messages(arround 60GB), and re-test again and again. These are old message file, so it is older than file reserve time

 If I set the deletewhen to next 1 or 2 hours later, this will not have problem, and from log, I see that it takes mq aroud 100 ms delete one file (at most 500ms). But when I recover the message and let it run, at 4:00am, this takes aroud 800ms to delete one file, which is much more longer.

@vongosling @lizhanhui @gaoyf 

I have serveral questions on this, can anybody help me ?


1. Why the same machine delete a file(the same file) cost different time cost?
2. The delete file is at stand along thread, why it will affect the response on send processor?

**Comment by Jaskey** [comment]
Another finding:

**Comment by lizhanhui** [comment]
The following slide may be helpful: http://events.linuxfoundation.org/sites/events/files/lcjp13_moriya.pdf

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)
