### ISSUE TITLE
ONS可以和其他哪个开源MQ兼容？

### ISSUE THREAD

**Issue by crossz** [alibaba/RocketMQ#370]
RocketMQ文档和单元测试都太惨。公司业务使用阿里云的ONS，但是不想自己的团队再研究本地的RocketMQ了，社区太小。

所以，请问开发团队小伙伴，有没有哪个开源的MQ，可以完美兼容ONS，以便于我们在开发的时候替换掉这个开源的RocketMQ（虽然终于发布3.5.8，但是文档、demo和测试依旧羸弱）

**Comment by vintagewang** [comment]
暂时没有。
