### ISSUE TITLE
PullConsumer的updateConsumeOffset()方法需要多久才能完成？

### ISSUE THREAD

**Issue by crossz** [alibaba/RocketMQ#371]
环境：v3.5.8 默认的单 broker，即用 mqbroker -n $NAMESRV_ADDR 启动的broker。

dos中提到的这个例子：
https://github.com/alibaba/RocketMQ-docs/wiki/pullConsumer%E7%9A%84%E7%A8%8B%E5%BA%8F%E4%BE%8B%E5%AD%90

问题：
4个queueId从0到3的mq，按照这个例子（还是有点bug的），每次启动，还是会重新刷一部分数据出来，即刷回 offset 的时候有问题。通过例子中提出的更改延迟时间长度貌似无效，这个问题经常复现（有的时候有效。。。。）

现在以我的测试，多种环境下，windows的客户端是 queueId=3的，offset回写总是失败；Mac下是queueId=0的，有此问题；但是，都是第一个被处理的queue有这样的问题。 #

**Comment by Jaskey** [comment]
`updateConsumeOffset() ` 只是把offset 刷到内存。

要刷到远端的网络，是通过定时任务`persistAllConsumerOffset`刷的，这个时间默认是5秒。

**Comment by crossz** [comment]
我改成了 consumer.setPersistConsumerOffsetInterval(1000); 但是怎么等，再重启pullconsumer的程序时，还是重新去读那些已经读过的数据。

目前我遇到的问题是无法确保pullconsumer重启后，都读到的是新的数据。

**Comment by Jaskey** [comment]
@crossz 你如何重启？
1.是shutdown的优雅退出不消费

**Comment by crossz** [comment]
我参考 rocketmq 的 example中的例子，以及 rocketmq-docs 中的这段代码：
https://github.com/alibaba/RocketMQ-docs/wiki/pullConsumer%E7%9A%84%E7%A8%8B%E5%BA%8F%E4%BE%8B%E5%AD%90

**Comment by Jaskey** [comment]
1. 把你使用的真正代码都贴出来，你拉成功后，消费是直接pull线程还是提交到线程池工作？
2. 并且说明下你遇到的问题。例如，消息重复是重复多少条？offset 不是最新的，还是消息内容重复？

**Comment by crossz** [comment]
1. 现在的调研，还未用线程池
2. 问题描述，就是如最上面所述，4个queue，有3个都能顺利成功的刷回offset，以便下一轮处理新的刷回来的数据，但是总是有1个，每次offset都和之前的一样，反复刷那些已经处理过的数据，其原因就是offset没有刷回去。

我用的代码在这里：
https://github.com/crossz/rocketmq-example

在simple文件夹下，用 TestProducer 制造一些数据；用TestPullConsumer去消费数据做这个实验。

多谢

**Comment by a11123939** [comment]
[BUG] consumer shutdown function have the problem of duplicate consumption #367
https://github.com/alibaba/RocketMQ/issues/367

**Comment by Jaskey** [comment]
@crossz 你意思是有一个Q上面的数据每次都从0开始消费？有没有使用控制台看看consume progress的情况，上面记录了broker端记录的consumergroup 的offset

**Comment by crossz** [comment]
@Jaskey 不是都从0开始；如果我按照 rocketmq-docs中的实现方法去做，4个Q，有3个能够正常刷回offset，但是总有一个特殊。绝大多数都是从上一次的offset继续消费数据，但是我如果开了debug的话，在不同的地方设置断点，有的时候，offset就能被刷回到remote，这是最让人迷惑的。

所以，问题在于：
1）有的Q正常，有的Q不正常
2）有的时候，不正常的Q能刷回offset，有的时候不能。

呵呵

**Comment by Jaskey** [comment]
According to the code from `updateConsumeOffsetToBroker`

        if (findBrokerResult != null) {
            UpdateConsumerOffsetRequestHeader requestHeader = new UpdateConsumerOffsetRequestHeader();
            requestHeader.setTopic(mq.getTopic());
            requestHeader.setConsumerGroup(this.groupName);
            requestHeader.setQueueId(mq.getQueueId());
            requestHeader.setCommitOffset(offset);

            this.mQClientFactory.getMQClientAPIImpl().updateConsumerOffsetOneway(
                    findBrokerResult.getBrokerAddr(), requestHeader, 1000 * 5);
        }

update offset to master is not a sync call, it is a oneway call, not a sync call , which may not be relyable.

You may try modify the source code

                 this.mQClientFactory.getMQClientAPIImpl().updateConsumerOffsetOneway(
                    findBrokerResult.getBrokerAddr(), requestHeader, 1000 * 5);

to:
                 this.mQClientFactory.getMQClientAPIImpl().updateConsumerOffset(
                    findBrokerResult.getBrokerAddr(), requestHeader, 1000 * 5);


and retest?

**Comment by crossz** [comment]
sure, will let you know the test result soon.

**Comment by crossz** [comment]
I changed and also some comments print to test this change touched:

` 
            this.mQClientFactory.getMQClientAPIImpl().updateConsumerOffset(
                    findBrokerResult.getBrokerAddr(), requestHeader, 1000 * 5);
            System.out.println("++++++++++++++++++++++++++++++++++++++++++++++++++" + offset);
`

but still same result, the first Q still is different from other 3:

`
++++++++++++++++++++++++++++++++++++++++++++++++++5579
++++++++++++++++++++++++++++++++++++++++++++++++++5642
++++++++++++++++++++++++++++++++++++++++++++++++++5644
++++++++++++++++++++++++++++++++++++++++++++++++++5645
`

**Comment by Jaskey** [comment]
原来你说的offset不同是这个意思？ 

这里的offset是指consumer group 的消费记录。

确认以下：

1.  撇开offset的具体数值，你觉得有问题的那个q，是不是收到了重复的消息？

2.  这个offset数值不一样，很可能是由于本身queue的最大offset本来就不一样，这个不一样是由于你的生产者不是一直在线。producer端负载均衡是从0开始循环发送，但是每次你重启，都会从0开始发。所以q小的，offset应该较大。

3. 建议你使用控制台console, 上面能看清楚具体我说的queue offset, consumer group consume offset 等。

**Comment by crossz** [comment]
@Jaskey 平时这个rocketmq我们都能上到几万的offset，而且我也查看了console, 没什么问题，如下：

> #Broker Name 	#QID 	#Min Offset 	#Max Offset 	#Last Updated
> broker-a 	0 	5500 	5697 	2016-09-30 11:37:15,890
> broker-a 	1 	5501 	5697 	2016-09-30 11:37:15,891
> broker-a 	2 	5500 	5695 	2016-09-30 11:37:15,892
> broker-a 	3 	5500 	5696 	2016-09-30 11:37:15,893 

但是我发现问题可能来自这里：

我在您说的那个方法里加入注释，结果发现在for循环中第一个Q的时候，并没有这个我追加的打印，而其他几个Q，在我新produce了一些数据后，循环到他们的时候，则有追加的日志打印出来。

所以，我觉得应该还是这个RemoteBrokerOffsetStore类中，对于第一个Q的判断中有问题，这和我用Mac，Windows 上测试结果吻合，虽然不同系统出问题的queueId不一样，但是都是第一个Q出问题。

**Comment by crossz** [comment]
如果先启动 这个consumer，跑几遍 while 循环，就能把所有Queue的Offset刷到最大。但是由于是oneway写的，rocketmq-docs的demo中pullconsumer的结果会有重复的消费数据。

**Comment by vongosling** [comment]
please use english.

**Comment by crossz** [comment]
The problem here is because that "consumer.fetchSubscribeMessageQueues(topic);" is not a pure "read" function, in which there is writing action. I do think this is not a good design!

This will cause the background async remote store offset persistence uncompleted/interrupted, as the program showed in the  https://github.com/alibaba/RocketMQ-docs/wiki about pullconsumer. The result of this demo will generate the result as I described above.

**Comment by ranqiqiang** [comment]
demo 例子  轮训时间 是20秒，不建议更改，这个是为什么呢？我16个Q，如果我pull  要达到push
 那样的消费速度 怎么搞的哦？ 能给个demo吗？  还是搞16个线程？

**Comment by crossz** [comment]
@ranqiqiang there are a lot of Thread.sleep() in the source codes. So you have to wait for some time....
