### ISSUE TITLE
How to use consume messsage hook?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#372]
I notice that rockcet mq suports message consumption tracing.

I have some questions:

1. how to use this functionality? Do I have to modify the source code from broker startup to call:
     
        controller.registerConsumeMessageHook(hook)

2. What does ConsumeMessageContext's properties mean, like:
  
         private String status;//what will be the possible value
         private Object mqTraceContext;//what is this message store?

3.  What will be a best pratice to use this hook?

**Comment by gaoyf** [comment]
Aliyun ONS has implemented it for tracing messages but not open the source code, [FYI](http://img3.tbcdn.cn/5476e8b07b923/TB1TtJVKFXXXXb_XFXXXXXXXXXX)
Don't expect too much. After all, it's a open source free  software.
You need read the source code for doing more things...

**Comment by Jaskey** [comment]
@gaoyf 

You donot answer my questions, since we are arguing about rocketmq not aliyun's mq.

1.So I have to modiy the source code to trace the consumption , don't I?

2.I read the source code but mqTraceContext is not use at the open source code, so this is our user defined context?

3. For open source project, what will be a best practice or example to use this hook.?

**Comment by lizhanhui** [comment]
1. Yes, you need to modify the source code to implement trace feature.
2. traceContext instance contains context information of the event under tracing. You probably need it when constructing your trace event.
3. For best practice guide, it's advisable to read Google paper about Dapper. BTW, there are several open source implementations of Dapper-like tracing systems available. Twitter's zipkin, for example, is well known.

**Comment by vongosling** [comment]
@Jaskey  yes, ConsumeMessageHook is just our SPI,not HOOK API.you need to modify source code or in other way,you can intercept the concrete consumption logic,adding your hooker
