### ISSUE TITLE
rocketmq  Design defects  设计缺陷

### ISSUE THREAD

**Issue by a11123939** [alibaba/RocketMQ#373]
主要问题：主从不能自动切换，导致了一系列小问题。
1：普通消息当主挂了，会拉取从上面的消息，最后如果主又活过来了，会导致重复消费（之前消费的进度在从上面）。
2：主down，顺序消息不能写入，不能消费（顺序消费不能消费slave上面的消息）

The main problem: the master-slave does not switch automatically, led to a series of small problems.
1: Normal message when the master down, will pull message from slave, and if  master  finally came back to life,this case  cause duplication of consumption message.
2: master down, the  sequentially message can not be written , not consumption (sequential consumer can not consume slave message above)

**Comment by Jaskey** [comment]
1. rocketmq 对于消息重复的处理能力是不足且没有保障的，文档中也明确说明需要业务去重。2
2. 主挂无法写入，所以使用到时候建议使用多组broker。单组broker不能保证高可用写。

**Comment by a11123939** [comment]
多组broker，顺序消息也不能读取和写入。 顺序消息是写入特定的queue，这个queue所在的机器挂了，就不能写了，手动写入其他的queue，在业务来看，也是有问题。

**Comment by Jaskey** [comment]
@a11123939 

多组的情况下，写入和读取都没问题的。

只是说顺序消息本来写到b1qx，由于b1那一瞬间挂了，会切到b2的q1上。

消费上，原来b1qx的消费和b2q1的消费顺序就无法保证，因为是同时监听同时消费，因此消息分布到不通的q。

按照这样看，顺序消费这个功能似乎存在单点问题。

**Comment by Jaskey** [comment]
@a11123939

多组的情况下，写入和读取都没问题的。

你可以在selector中，记录状态，某一组q挂了发不通，发往另外一组的相同qid的broker中。

消费上，原来b1qx的消费和b2q1的消费顺序就无法保证，因为是同时监听同时消费，因此消息分布到不通的q。

按照这样看，顺序消费这个功能似乎存在单点问题。

**Comment by a11123939** [comment]
发送到其他queue，是有小问题的。还有，顺序消息是不能消费从上面的数据的。

**Comment by Jaskey** [comment]
@a11123939 

are you sure 顺序消费不能消费slave的数据？ master 挂了，路由上寻址寻到的就是slave的地址，就从slave上拉。

按照我的理解，没有所谓的顺序消息，只有顺序消费一说。所以，拉消息的逻辑应该是一样的。

由于没有使用过顺序消费功能，需要等其他人来confirm了。

**Comment by a11123939** [comment]
顺序消费不能消费slave，这个我测过了，你可以测一下，代码中就是这么设计的。

**Comment by vongosling** [comment]
please use english.

**Comment by a11123939** [comment]
Order consumer can not consume message in  slave, I have tested the case. the code is so designed.

**Comment by xiukongtiao** [comment]
@vongosling  
Can you help us to confirm if the test result of @a11123939  is original target of your team please?
Does that mean, the slave server is useless for orderly consumer?

**Comment by a11123939** [comment]
ConsumeMessageOrderlyService. lockOneMQ 
public synchronized boolean lockOneMQ(final MessageQueue mq) {
        if (!this.stopped) {
            return this.defaultMQPushConsumerImpl.getRebalanceImpl().lock(mq);
        }

        return false;
    }

FindBrokerResult findBrokerResult =
                this.mQClientFactory.findBrokerAddressInSubscribe(mq.getBrokerName(), MixAll.MASTER_ID, true);

# MixAll.MASTER_ID,

**Comment by xiukongtiao** [comment]
Do you have any good suggestion, or solution?
the slave looks like useless for orderly consumer?
@vongosling Do you have any suggestion for this problem?
