### ISSUE TITLE
 [BUG] Multiple Network card , the mq choosed ip is outer ip

### ISSUE THREAD

**Issue by a11123939** [alibaba/RocketMQ#374]
public class RemotingUtilTest {
    @Test
    public void test() throws Exception {
        String a = RemotingUtil.getLocalAddress();
        System.out.println(a);
    }
}
the test show mq choose the outer ip

**Comment by vongosling** [comment]
please see source code，it's not a bug

**Comment by a11123939** [comment]
if master choosed the out ip , slave cannot update log from master . producer cannot send message to the broker . because of the out ip cannot access .

**Comment by lizhanhui** [comment]
You may configure your broker IP manually in configuration file.
