### ISSUE TITLE
获取broker默认配置报错

### ISSUE THREAD

**Issue by kkrgwbj** [alibaba/RocketMQ#382]
sh mqbroker -m
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=320m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be 
removed in a future release.Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file /webapp/tmpfs/logs/gc.log due to No such file 
or directory

**Comment by vongosling** [comment]
It's obvious that your jdk config may be wrong.BTW, please use english next time
