### ISSUE TITLE
Why deleting commit log will have performace impact on put message ?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#383]
I notice that at 4:00 am, I will possibly got : 

```
 putMessage not in lock eclipse time(ms) 1195
 putMessage not in lock eclipse time(ms) 1315
 putMessage not in lock eclipse time(ms) 1003
 putMessage not in lock eclipse time(ms) 1006
 putMessage not in lock eclipse time(ms) 1010
 putMessage not in lock eclipse time(ms) 1013
 putMessage not in lock eclipse time(ms) 1016
```

As far as I know: 
1. put message is only writing to page cache , 
2. delete message and put message are working in different thread
3. delete message does not have any lock
4.  Though I use sync master , but slave is syncing message to its page cache too

My question is when putting message, both master and slave **should only have memory operation thus not reply on IO** ,please correct me if I am wrong,  but why deleting message will have performce impact on putMessage?

PS:
version 3.2.6
both slave(I have two slave) and master delete messages on 4:00 am

**Comment by Jaskey** [comment]
@vongosling any help on this? We suffer from this for long.

**Comment by lizhanhui** [comment]
Which file system do you guys use? Ext3 or Ext4?

**Comment by vongosling** [comment]
please use the latest broker version

**Comment by Jaskey** [comment]
@lizhanhui , we did use ext3 file system and try ext4 file system in our test env which does has improvment.

But the problem is why deleting file will have impact on writing page cache, before we have make clear this of thie problem, we can't update the file system on our prod env, since as far as I am concerned, updating to ext4 is only help to improve IO, the impact is still there which is still unclear.

**Comment by Jaskey** [comment]
@vongosling , Does latest version actually fix this issue, if yes, please explain why and how.  I can't see the related issue on the release note.

We can't update to our runinng prod so recklessly before we make clear of the reason the solution.

**Comment by lizhanhui** [comment]
First, the following statement(bold section) does not hold true: "But putting message is only writes to page cache which **does not have actual IO flush** , so the impact is still there which is still unclear."   If you are not familiar with internals of page cache, please refer to https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics and http://www.redhat.com/f/pdf/summit/dshakshober_1010_part_1_performance_analysis.pdf etc. To put it roughly: when putMessage(), we are creating **dirty pages**; when the ratio of dirty page reaches **vm.dirty_background_ratio**, background flush thread(s), pdflush in linux kernel 2.6.31 and prior, start(s) to sync data into underlying storage. If the dirty pages keep increasing and become more than **vm.dirty_ratio**, all write operations become **synchronous**.

For your scenario, a highly possible, though not yet justified by real experiments, reason is: deletion of large files from ext3 file system is very IO extensive and occasionally costs about 1 second per file to complete. When your OS has limited memory, it won't be strange deleting deprecate commit log files would affect putMessage speed and thus total throughput of RocketMQ.

**Comment by lizhanhui** [comment]
To fix this issue, IMO, the following options are worth considering
1) Use Ext4 file system which has better large file deletion performance;
2) Use large memory;
3) Tune your kernel parameter carefully, especially those relating to virtual memory, say dirty_background_ratio, diry_ratio, dirty_writeback_centisecs, dirty_expire_centisecs, etc.

**Comment by lizhanhui** [comment]
Refer to this slide for reference: http://events.linuxfoundation.org/sites/events/files/lcjp13_moriya.pdf
