### ISSUE TITLE
能告诉我们为什么吗？

### ISSUE THREAD

**Issue by kkrgwbj** [alibaba/RocketMQ#384]
为什么阿里偌大的一个公司，写代码没有源码注释？看看spring的源码,看看apache的任何一个工具类的源码，注释都非常的详细。往往我们在使用框架的过程中，发现问题调试都是最直接的看源码，毕竟方便，没有一个人喜欢边看源码，边在看文档这个到底啥意思。
我加入rocketmq群已经第三天了，在这里我看到了很多人都在问一些很基本的问题，比如如何创建topic如何更新topic的对列个数。然而回答的人并不多。将近1000个人的群，却这样。我想更多的问题可能是因为rocketmq偌大的框架，没有源码注释，没有良好的quick start。虽然是国人开发的框架，但是写的文档比国外人的开发指南还难理解。为什么满篇都是英文？框架无国界可言，如果你们是因为没有时间做这些。那么可以至少给大家一个完整的指南，让国内会翻译的人，按着你们英文版的翻译也可以。

**Comment by Lihuanghe** [comment]
you can you up ,no can no BB

**Comment by vongosling** [comment]
no quick start ? if you have more patient to learn some  tech. or framework, you can find the reason. if you love open source,love rocketMQ. please pack up your complaints, join us to help us to update and optimize our product,including wiki ~
