### ISSUE TITLE
What is the purpose of method "checkInDiskByCommitOffset"

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#385]
I am trying to understand the logic when pulling message from store.

```

 boolean isInDisk = checkInDiskByCommitOffset(offsetPy, maxOffsetPy);

if (this.isTheBatchFull(sizePy, maxMsgNums, getResult.getBufferTotalSize(), getResult.getMessageCount(),isInDisk)) {
        break;
 }

```

 checkInDiskByCommitOffset: 

```
    private boolean checkInDiskByCommitOffset(long offsetPy, long maxOffsetPy) {
        long memory = (long) (StoreUtil.TotalPhysicalMemorySize * (this.messageStoreConfig.getAccessMessageInMemoryMaxRatio() / 100.0));
        return (maxOffsetPy - offsetPy) > memory;
    }

```
1. It seems that this is to messure the message size from the pulling ofsset to max offset, which is confusing since the variable it assgined to is named isInDisk, which lead us to think this is to check whether the message is loaded to the memory or not.
2. Commit log's message is storing all kind of topic, say if I have message of topicA in offset 1 to 10, and then 1billions message of topicB is stored and offset is up to **offset_very_large**. Then when checkInDiskByCommitOffset is invoked, it will return true, and this will affect the result of `isTheBatchFull`, isn't this confusing?

**Comment by lizhanhui** [comment]
1. You are right;
2. RocketMQ uses two kinds of offsets: consume offset and logical offset. The former one is relating to topic/queue while the latter is actually the offset of commit log in bytes.

**Comment by Jaskey** [comment]
@lizhanhui  Thank you for your response. 

1. What I am confusing about this point is `checkInDiskByCommitOffset` messures the message size from the pulling ofsset to max offset. However, why the offset diff is a sufficient condition to judge if this message is indisk or not?  

What I comprehend is that rocket is trying to **GUESS** if this message in disk or not, but why 40%(accessMessageInMemoryMaxRatio=40 by default)?

2. I totolly understand there are three offset , 1. consume offset which for client to use, 2. logic offset which is store in consume queue, 3 phy offset which is store in commit log. 

The example I am giving is trying to point out an case that there are 10 messages for topic A, and then 1 billions messages for topic B, which the topic A'offset will be very small and the max offset will be very large. Then when invoking ` boolean isInDisk = checkInDiskByCommitOffset(offsetPy, maxOffsetPy); , this isInDisk will be true. And then this will be passed to isTheBatchFull, which will let isTheBatchFull goes to another code flow. What I am confusing is this still right for my special case.
`

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)
