### ISSUE TITLE
storeerror.log异常

### ISSUE THREAD

**Issue by wangchao102** [alibaba/RocketMQ#386]
你好，帮我看下这个异常如何解决

RocketMQ版本：3.2.6， noslave模式

**2016-05-20 22:03:11 WARN FlushConsumeQueueService - findMapedFileByOffset offset not matched, request Offset: 12000000, index: 2, mapedFileSize: 6000000, mapedFiles count: 2, StackTrace:
	java.lang.Thread.getStackTrace(Thread.java:1589)
	com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
	com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
	com.alibaba.rocketmq.store.MapedFileQueue.commit(MapedFileQueue.java:442)
	com.alibaba.rocketmq.store.ConsumeQueue.commit(ConsumeQueue.java:345)
	com.alibaba.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.doFlush(DefaultMessageStore.java:1522)
	com.alibaba.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.run(DefaultMessageStore.java:1544)
	java.lang.Thread.run(Thread.java:745)
2016-05-20 22:03:13 WARN FlushConsumeQueueService - findMapedFileByOffset offset not matched, request Offset: 12000000, index: 2, mapedFileSize: 6000000, mapedFiles count: 2, StackTrace:
	java.lang.Thread.getStackTrace(Thread.java:1589)
	com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
	com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
	com.alibaba.rocketmq.store.MapedFileQueue.commit(MapedFileQueue.java:442)
	com.alibaba.rocketmq.store.ConsumeQueue.commit(ConsumeQueue.java:345)
	com.alibaba.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.doFlush(DefaultMessageStore.java:1522)
	com.alibaba.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.run(DefaultMessageStore.java:1544)
	java.lang.Thread.run(Thread.java:745)**

**Comment by lizhanhui** [comment]
Upgrade to the latest release is recommended to fix this issue.

**Comment by wangchao102** [comment]
@lizhanhui thank for your advise!
