### ISSUE TITLE
在使用过程中，突然偏移量变成了负值,为什么会变成负值，怎么解决呢？

### ISSUE THREAD

**Issue by dengkx** [alibaba/RocketMQ#387]
我使用的是3.4.6版本的，使用过程中突然偏移量就变成负值了，为什么会变成负值呢？怎么能避免出现负值，或者怎么样能解决这种情况呢？

**Comment by dengkx** [comment]
![xn 5w r8q29wgi9 1 ijxq3](https://cloud.githubusercontent.com/assets/15144261/19752024/98de6b4e-9c2c-11e6-9297-42807a5dfaf9.png)
如图所示

**Comment by lizhanhui** [comment]
Please rephrase this issue in English so that more developers may get involved as we are moving to Apache.

**Comment by Jaskey** [comment]
Do you clean your store or delete topic then re-created before?

**Comment by dengkx** [comment]
no，My data is production data,How to make the offset normal?

**Comment by dengkx** [comment]
In use process, the offset suddenly turns negative, why will become a negative value?How to solve this kind of situation, how to avoid negative?

**Comment by Jaskey** [comment]
Have you confirm the broker offset and consumer offset of that problematical topic for your consumer group?

**Comment by vongosling** [comment]
please update your version to latests
