### ISSUE TITLE
FAQ: Name Server地址不存在

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#39]

**Comment by panpanxu** [comment]
benchmark的producer直接运行会提示这个错误。

**Comment by panpanxu** [comment]
benchmark的producer直接运行会提示这个错误。
源码添加调用setNamesrvAddr后正常。

**Comment by sculinyun** [comment]
@panpanxu  在windows下设置了NAMESRV_ADDR 但是跑rocketmq-example的Producer还是报No name server address, please set it.See https://github.com/alibaba/RocketMQ/issues/39 for further details.
