### ISSUE TITLE
+DisableExplicitGC may result in OOM of Direct buffer memory

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#391]
From runbroker.sh, a jvm option `-XX:+DisableExplicitGC` is set 

However, since great amount of memory allocated by directbytebuffer are used , which means memory allocated by direct buffers may accumulate for a long time before it is collected.  

There are at least two place where rocketmq process will call System.gc();

_1_.reserveMemory from `DirectByteBuffer`,  when there are not enough direct memory size out there, System.gc() will be called so that some unused directByteBuffer instance which lies in Old can be collected thus fress direct momory

Here is source code of method `reserveMemory`

```
    // These methods should be called whenever direct memory is allocated or
    // freed.  They allow the user to control the amount of direct memory
    // which a process may access.  All sizes are specified in bytes.
     static void reserveMemory(long size, int cap) {
        synchronized (Bits.class) {
            if (!memoryLimitSet && VM.isBooted()) {
                maxMemory = VM.maxDirectMemory();
                 memoryLimitSet = true;
            }
        // -XX:MaxDirectMemorySize limits the total capacity rather than the
        // actual memory usage, which will differ when buffers are page
        // aligned.
        if (cap <= maxMemory - totalCapacity) {
            reservedMemory += size;
            totalCapacity += cap;
            count++;
            return;
        }
    }

        System.gc();
        try {
            Thread.sleep(100);
        } catch (InterruptedException x) {
            // Restore interrupt status
           Thread.currentThread().interrupt();
       }
        synchronized (Bits.class) {
            if (totalCapacity + cap > maxMemory)
                throw new OutOfMemoryError("Direct buffer memory");
            reservedMemory += size;
            totalCapacity += cap;
            count++;
        }
    }
```

Also check https://bugs.openjdk.java.net/browse/JDK-8142537

_2._When Rocketmq find that there is no enough space for commitlog or consume queue, `System.gc()`will be called in `isSpaceToDelete()`. at version v_3.2.6 .

Above two problem shows that 'System.gc()' is still needed and NO.2 problem , rocketmq even call System.gc() itself, disableExplictGC is self-contradiction.

PS:
According to http://www.oracle.com/technetwork/articles/java/vmoptions-jsp-140102.html 

> By default calls to System.gc() are enabled (-XX:-DisableExplicitGC). Use -XX:+DisableExplicitGC to disable calls to System.gc(). Note that the JVM still performs garbage collection when necessary.

**Comment by zhouxinyu** [comment]
Did you find OOM in your environment ?

**Comment by Jaskey** [comment]
@zhouxinyu 

No , I fall into another problem. When dianosing, I find this may be a problem so post an issue here to confirm.

**Comment by zhouxinyu** [comment]
Normally, 100ms is not enough for once garbage collection, so System.gc in reserveMemory may not meet your expectations.

BTW, RocketMQ will release DirectByteBuffer by itself.

**Comment by Jaskey** [comment]
@zhouxinyu 

JVM distable system.gc(), but rocketmq call system.gc(), which is self-contradiction, which is issued at *#2*.

DirectByteBuffer is not only used for mmaping, but also at netty.

**Comment by zhouxinyu** [comment]
Both Netty and RocketMQ don't rely on System.gc. I think it's a bad practice to call system.gc explicitly.

**Comment by Jaskey** [comment]
@zhouxinyu 

1. DirectByteBuffer use System.gc,  and BOTH netty and RokectMQ use `DirectByeBuffer`, check my question's source code.

2. RocketMQ use System.gc at `isSpaceToDelete()` at v3.2.6, but indeed it has been remove at later version.

**Comment by zhouxinyu** [comment]
Yes, DirectBuffer use System.gc(reserveMemory), JDK may consider that If anyone forget to release DirectBuffer, but as for RocketMQ, all the code are in our control.

BTW, you can remove this flag from your environment.

**Comment by vongosling** [comment]
lt's easy to prove you problem if you disable that setting. any oom case occur.please let us know.

**Comment by Jaskey** [comment]
@zhouxinyu , I just point out this risk, it seems you agree to me that jdk relies on System.gc when using DirectBuffer, and if user uses the defualt `runbroker.sh`, some memory problem may occur, so what I recommend is we should remove this jvm options on the shell script.
