### ISSUE TITLE
没有释放线程，导致内存溢出

### ISSUE THREAD

**Issue by kiwiflydream** [alibaba/RocketMQ#396]
02-Nov-2016 21:36:50.527 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@29b87dea]) and a value of type [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap] (value [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap@7bf94940]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
02-Nov-2016 21:36:50.529 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@29b87dea]) and a value of type [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap] (value [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap@7afa3563]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
02-Nov-2016 21:36:50.529 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@29b87dea]) and a value of type [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap] (value [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap@4ca18f86]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
02-Nov-2016 21:36:50.532 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@29b87dea]) and a value of type [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap] (value [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap@7117a858]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
02-Nov-2016 21:36:50.533 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@29b87dea]) and a value of type [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap] (value [com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.InternalThreadLocalMap@40154c73]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by vongosling** [comment]
please beautify your question
