### ISSUE TITLE
unnecessary connections are established for every cluster 

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#397]
Say I have 2 cluster IDC1, IDC2, which rigister to one namesrv N1.

I have two client. A ,B. 

A needs to subcribe topic from IDC1 and publish message to IDC2, so A will send heart beat to both IDC1 and IDC2 thus connections are estabilished on both cluster , which is fine and necessary.

For client B, which only send message to topic1 which only exits at IDC1, but when sending heartbeat, a *defaut public* `TBW102` is added to the producerdataset when start:

         this.topicPublishInfoTable.put(this.defaultMQProducer.getCreateTopicKey(), new TopicPublishInfo());

the `TBW102` ,which is the default topic, will be possibly be created at all broker when start, so heart beart to send to all broker which contains `TBW102` , thus connections will be both estalished to IDC1 as well as IDC2, but IDC2 is not needed for neither client B nor IDC2's broker.

This may result in more connections than necessary need acrouss cluster which will become large problem when there are many clsuters but same same namesrv since many unnessary connections and bandwith are wasted.

**Comment by vongosling** [comment]
TBW102 topic will work only if you set topic auto creation. That's not recommendation in product environment.

**Comment by Jaskey** [comment]
@vongosling 
warnings https://github.com/alibaba/RocketMQ/issues/314  will occur if I set that, does this issue fix at this version?
