### ISSUE TITLE
How to set Message character set with UTF-8?

### ISSUE THREAD

**Issue by xjcoka** [alibaba/RocketMQ#398]
As the title,My project use UTF-8,
 1.Producer Consumer also use utf8, but the message include chinese text, when consumer recieve the message ,the text will be garbled .
2.I can use **new String("my text","UTF-8")**  get the text.

How can I desine the character set?

Thanks very.

**Comment by lizhanhui** [comment]
Your question is not properly formulated and is unlikely to get any useful response. To improve, please:

1. Use English to state your problem;
2. List detailed steps to reproduce your issue if possible; otherwise, provide as much/thorough background info as possible.

**Comment by Jaskey** [comment]
How do you send your message.

You should encode your message content with "UTF-8" like:

     mssg.setBody(content.getBytes("UTF-8"));

**Comment by lizhanhui** [comment]
RocketMQ uses "AS-IS" approach to send message body, aka, consumer gets what exactly is set into body. It's up to you to decide how to encode and decode the byte array.
