### ISSUE TITLE
FAQ: 启动Producer、Consumer失败，Group Name重复

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#40]

**Comment by ronyongxian** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: The consumer group[t11] has been created before, specify another name please.
See https://github.com/alibaba/RocketMQ/issues/40 for further details.
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:714)
	at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:365)

**Comment by ronyongxian** [comment]
这个好像是bug，因为只是调用了
DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("t11");
新增consumer

**Comment by devpage** [comment]
作者呢?

**Comment by devpage** [comment]
算不算个bug

**Comment by lizhanhui** [comment]
错误提示不太准确， 你start前设置一个不同的instance name

**Comment by cfmui** [comment]
楼上说得对，需要设置不同的instanceName，这个提示确实不够准确，让人误解

**Comment by xyf19920109** [comment]
错误提示不太准确， 你start前设置一个不同的instance name ，没有太懂这句话是什么意思
