### ISSUE TITLE
broker slave 节点的作用

### ISSUE THREAD

**Issue by markray** [alibaba/RocketMQ#400]
如果一个broker的 master挂了，slave 会晋升为master吗？ slave节点是在什么情况下被消费者消费的？

**Comment by xiukongtiao** [comment]
No, slave can not upgrade to master.
That means  if a master is killed,  producer can not publish message to slave, but consumer still can read message from slave server.

Slave just can be read, can not receive message from producer.

**Comment by markray** [comment]
谢谢您的及时回复. 但是如果一条消息在master提交后，master挂了，但是master还没来得及同步给slave，这条消息不久丢失了？

**Comment by xiukongtiao** [comment]
Please write english.
RocketMQ will be an international(牛逼范儿) project ^-^

Yes, you are right,  it will be lost.
Can you check the document about the property of broker config named 'brokerRole', then you can get the answer.

**Comment by markray** [comment]
Thank you . To be international ,totally support !
