### ISSUE TITLE
readQueueNums and writeQueueNums

### ISSUE THREAD

**Issue by markray** [alibaba/RocketMQ#401]
I have always been confused with readQueueNums and writeQueueNums when creating topics.
why queue has to be distinguished with readqueue  and wirtequeue?
what if readQueueNums  is not equal to writeQueueNums ?
and when readQueueNums    is not equal to writeQueueNums ?

**Comment by gaoyf** [comment]
When you want to scale out your ordered queue,  you can first set `writeQueueNums` to your expected, at this time `readQueueNums` is not change, so your consumer will consume the messages orderly like before.
When the consumer finished consume, set `readQueueNums` the same as `writeQueueNums`.
So you can scale out ordered queue dynamicly for keeping the order.

**Comment by markray** [comment]
So ,this is only intended for manual scalability

**Comment by markray** [comment]
Seemed this is intended for manually scalability.
But how can this ensure orderly consuming?
e.g. the initial writeQueueNums and readQueueNumbs is 5, and in the producer ,we have
MessageQueueSelector  which has logics like queueindex=id%5.
Then we set writeQueuenums to 10, the queue selector logics will  automatically be changed to queueindex=id%10,   how can this ensure order? what happened next?

**Comment by gaoyf** [comment]
Yes, transient out-of-order.

**Comment by markray** [comment]
if so, is it necessary to  differentiate readNum from writeNum ?
let's say that we only have one term queueNum, if you want to scale out ,you just need to change the queueNum ,then after a transient out-of-order, the producer and consumer  will automatically reach a new orderly state.

**Comment by gaoyf** [comment]
Yes, you just need modify the queueNum simply when you want to scale out your queue.
But if you want to shrink your queue, the two term can be useful, [FYI](https://github.com/alibaba/RocketMQ/issues/316).

**Comment by markray** [comment]
thank you
