### ISSUE TITLE
RocketMQ支持定时队列吗？

### ISSUE THREAD

**Issue by cnJun** [alibaba/RocketMQ#402]
RocketMQ支持定时队列吗？

延时队列只支持：1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h。不支持自己设定一个延时时间吗？

**Comment by gaoyf** [comment]
You can set it in your config file like that:
messageDelayLevel=1s 5s 10s ...

**Comment by cnJun** [comment]
阿里云的MQ服务也是使用的 RocketMQ，开源的如果能类似使用延时或定时队列，就更灵活了。

/**
 * 定时消息投递，设置投递的具体时间戳，单位毫秒例如2016-03-07 16:21:00投递
 */
long timeStamp =new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse("2016-03-07 16:21:00").getTime();
msg.setStartDeliverTime(timeStamp);

https://help.aliyun.com/document_detail/29550.html?spm=5176.doc29549.6.141.044FnK

// 延时时间单位为毫秒（ms），指定一个时刻，在这个时刻之后才能被消费，这个例子表示 3秒 后才能被消费
long delayTime = 3000;
msg.setStartDeliverTime(System.currentTimeMillis() + delayTime);

https://help.aliyun.com/document_detail/29549.html?spm=5176.doc29551.6.140.UBQ8pF

**Comment by vongosling** [comment]
Not support, nowadays~
