### ISSUE TITLE
use  DefaultMQAdminExt  exception  The adminExt group[xx] has created already,

### ISSUE THREAD

**Issue by wangyixiaohuihui** [alibaba/RocketMQ#409]
rocketmq version 3.4.6
i want wo monitor the rocketmq.  so i use DefaultMQAdminExt to to get rocketmq status.
eg: 
configureInitializer = new ConfigureInitializer(nameSrvAddress);
 DefaultMQAdminExt defaultMQAdminExt = new DefaultMQAdminExt(Long.toString(System.currentTimeMillis()));

use  defaultMQAdminExt   to check rocketmq status.
every 10 minute.  the exception  The adminExt group[xx] has created already   happened.
i have set the name use time.  why come out the same adminExt ?

**Comment by zhouxinyu** [comment]
Hi, wangyixiaohuihui

There is no need to new DefaultMQAdminExt repeatedly, you can reuse one instance in your monitor application.

Please refer to rocketmq-tools(package com.alibaba.rocketmq.tools.command) for more details.

**Comment by vongosling** [comment]
If you have any question about rocketmq, please ask http://stackoverflow.com/questions/tagged/rocketmq or https://www.quora.com/topic/RocketMQ
