### ISSUE TITLE
C++ 客户端不支持 c++11标准编译

### ISSUE THREAD

**Issue by flames85** [alibaba/RocketMQ#411]
下载c++ linux sdk
http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/assets/attach/29555/cn_zh/1478590702454/aliyun-mq-linux-cpp-sdk.zip?spm=5176.doc29555.2.2.0Hw8AB&file=aliyun-mq-linux-cpp-sdk.zip

在代码中添加
    boost::asio::io_service io;
    io.run();
并在g++编译参数中添加std=c++11

运行rocketmq例子:
onsclient4cpp的example代码在执行SendResultONS sendResult = pProducer->send(msg)必然抛异常:
send catche exception:Topic Route does not exist, Topic:STATUS exception:msg: No route info of this topic, ,error:-1,in file <../src/producer/DefaultMQProducer.cpp> line:587
See https://github.com/alibaba/ons/issues/7 for further details.

去掉std=c++11, 没有此问题.

环境: 
ububtu 14.04 LTS 64bit Intel® Core™ i3-2350M CPU
gcc version 4.8.4

**Comment by vongosling** [comment]
please use english
