### ISSUE TITLE
假如rocketmq宕机后重启，原先设置24小时过期的消息，现在会如何处理

### ISSUE THREAD

**Issue by tonychenz** [alibaba/RocketMQ#412]
如题：rocketmq宕机之后，原先设置为24小时之后处理的定时消息（假设宕机时只过了12个小时），之后重启，那么这个消息会丢，还是仍旧在24小时的时候被处理，或者处理时间变为24小时+宕机至重启的时间？

另外有一个问题：updateBrokerConfig  支持动态更新 messageDelayLevel 吗？

sh mqadmin updateBrokerConfig  -n '*****'  -b '****' -k 'messageDelayLevel' -v ‘1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h 1d’ 这样设置去查看配置文件只有
messageDelayLevel=1s  其他的都不见了

**Comment by Jaskey** [comment]
please issue in English.

For point 2, messageDelayLevel does not support dymatically update since the schedue task is triggered by startup config
