### ISSUE TITLE
Which IO scheduler does rocketmq broker suggest

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#415]
According to the user guide of rocketmq v3.2.4(Chinese version),which is the lastest one I can find.

It suggests two kinds of IO schedulers .One is deadline and another is noop. It seems that there are some clerical error on it.  

On os.sh, deadline is set,  but actually, which one is suggested and why.

**Comment by lizhanhui** [comment]
Deadline should be the right choice for most cases. If you have large RAID controller cache, noop should also be fine.

**Comment by Jaskey** [comment]
@lizhanhui 
would you please also explain why deadline is the right scheduler and which feature does the tirck on performance improvment, and what kind of performace?

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
