### ISSUE TITLE
about high availability  mechanism

### ISSUE THREAD

**Issue by markray** [alibaba/RocketMQ#416]
If a master broker is down,  messages sent to the broker will all be failed ,and consumers will switch to slaver broker. What will happen if the master broker cant resume for ever ? in that case can we ensure no message lost?

**Comment by Jaskey** [comment]
Only master can be be sent message to.

You should ensure that there are at least two master to provide writing service on one topic.

**Comment by markray** [comment]
two master ? how to keep in sync ?

**Comment by Jaskey** [comment]
Synchrinazation is only happens in one broker set. There's no need for masters in different broker set  to sync.

**Comment by markray** [comment]
You may misunderstand me . I mean in one broker set, if the master broker is gone for ever, what will happen to ensure no message lost?  will re-balance be triggered both at producer and consumer end?

**Comment by markray** [comment]
thank you @Jaskey   “Say you have two broker set b1 b2, when master of b1 is down, client will find that there are only/still b2 can be sent to, and thus writing message service is still available.”
