### ISSUE TITLE
Queue's offset is not be updated to broker server,but msg has been consumed !

### ISSUE THREAD

**Issue by 893605721** [alibaba/RocketMQ#417]
![qq 20161116154120](https://cloud.githubusercontent.com/assets/3427518/20338635/2b1153dc-ac13-11e6-8d52-05301cd8c487.png)

Msg has bean consumed ,but offset in broker is old .

**Comment by vongosling** [comment]
please.... https://github.com/alibaba/RocketMQ/issues/108

**Comment by 893605721** [comment]
I use 3.2.6 version,found that pushConsumer don't update offset to broker ,so that my broker-b queue [0-7],offset is not right .Look like message has blocked！Actualy,client had consume this part of message.
