### ISSUE TITLE
MQ 能通过QueueId 之类的 pull 消息吗？

### ISSUE THREAD

**Issue by ranqiqiang** [alibaba/RocketMQ#418]
我看kafka  可以通过 partitionID  拉取指定分片的队列。
而rocket 默认有16个对了，但是我要保证消息不丢，而且处理时间很长，消费不急，因此用pull 的模式，但是pull 模式一次从16个对了拉取，消息太多，我需要用16个机器，分别从16个queue拉取，能做到吗？

**Comment by vongosling** [comment]
of course, look for pool related api carefully ~ please use english next time~

**Comment by lizhanhui** [comment]
"look for pool related api carefully" --> " look for PULL related api carefully"
