### ISSUE TITLE
[BUG]The mapedfile queue's data is damaged

### ISSUE THREAD

**Issue by liuliuwd** [alibaba/RocketMQ#419]
I have meet this problem that can't read message normally with many exceptions like this  “selectMapedBuffer request pos invalid, request pos: 878, size: 877, fileFromOffset: 1299814809600, wrotePostion: 905”, but all message can still write normally. All exceptions show that the wrotePostion of file 1299814809600  is always 905, but the file is still writting, why wrotePostion  don't inscrease.  I suspect that there are two mapedfiles with the same filename 1299814809600 exits in memory. After restart, the problem will recover. Please help me.

**Comment by lizhanhui** [comment]
1. Please specify which version of RocketMQ is being used.
2. Please paste the original exception trace so that we can look into the issue.
3. Clarify role of the broker, master or slave?

**Comment by liuliuwd** [comment]
version:3.2.6 , I have make some changes about the store, set the mapedfile size of every commitlog to 100M;
broker:master
exceptions:
selectMapedBuffer request pos invalid, request pos: 878, size: 877, fileFromOffset: 1299814809600, wrotePostion: 905
selectMapedBuffer request pos invalid, request pos: 1755, size: 878, fileFromOffset: 1299814809600, wrotePostion: 905
selectMapedBuffer request pos invalid, request pos: 2633, size: 608, fileFromOffset: 1299814809600, wrotePostion: 905
selectMapedBuffer request pos invalid, request pos: 3241, size: 905, fileFromOffset: 1299814809600, wrotePostion: 905
selectMapedBuffer request pos invalid, request pos: 4146, size: 878, fileFromOffset: 1299814809600, wrotePostion: 905
selectMapedBuffer request pos invalid, request pos: 5024, size: 905, fileFromOffset: 1299814809600, wrotePostion: 905
......

**Comment by lizhanhui** [comment]
Version 3.2.6 prints some false-alarming logs. Best to use the latest code.
"I have made some changes about the store, set the mapedfile size of every commitlog to 100M;" --> Make sure all commit log files are of same size. If not, you would mess all things up.

**Comment by liuliuwd** [comment]
MapedFileSizeCommitLog is seted in advance, and has never been changed after the broker start.

**Comment by liuliuwd** [comment]
Is there possiable two mapedfiles have the same fileFromOffset?

**Comment by lizhanhui** [comment]
No. This is not possible.

**Comment by liuliuwd** [comment]
In version 3.5.8, mapedFileQueue  adds a method named “checkSelf” , checking the consistence of mapedFiles'size. Whether the bug "mapedfile queue's data is damaged" has appeared before?

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
