### ISSUE TITLE
  Consumers how to active timeout

### ISSUE THREAD

**Issue by youlingguest** [alibaba/RocketMQ#420]
com.alibaba.rocketmq.client.consumer.DefaultMQPullConsumer

……

public QueryResult queryMessage(String topic, String key, int maxNum, long begin, long end)
            throws MQClientException, InterruptedException {}

example：
this.queryMessage(topic, key, 1, 0, System.currentTimeMillis());

question:
15 seconds consumers do not timeout，Do you know what it is?  demo or example？thanks.

**Comment by Jaskey** [comment]
Please speak in English and also make sure you make yourself clear, what kind of problem are you facing?

**Comment by youlingguest** [comment]
ok

example：
this.queryMessage(topic, key, 1, 0, System.currentTimeMillis());

question:
15 seconds consumers do not timeout，Do you know what it is? demo or example？thanks.

**Comment by Jaskey** [comment]
How do you know it is not timeout?

By the way, And why do you need a very very big numbers as System.currentTimeMillis()?

**Comment by youlingguest** [comment]
Did not see timeout.

example：
this.queryMessage(topic, key, 1, 0, ???);

question:
What are the parameters of the method？thanks.

**Comment by Jaskey** [comment]
The last parameter is the end offset you want to serach. 

What example do you want , just try to put a small value for that and see what's comming out.

**Comment by youlingguest** [comment]
thanks.

consumer API and method? thank you.

**Comment by Jaskey** [comment]
check rocketmq-example module for running demo please.

If you are using pull consumer, the method `pull` should be used.

**Comment by youlingguest** [comment]
pull consumer,How to implement the method?link where?thanks.

**Comment by Jaskey** [comment]
https://github.com/alibaba/RocketMQ/tree/master/rocketmq-example
