### ISSUE TITLE
When selecting SYNC_MASTER+SYNC_FLUSH mode,  it seems that producer doesn't wait slave return ack?

### ISSUE THREAD

**Issue by liuliuwd** [alibaba/RocketMQ#421]
Version: 3.5.8
In CommitLog class, line : 636,
GroupCommitRequest has been coutdown when sync flush, so  in synchronous write double stage, the same request will return directly?

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
