### ISSUE TITLE
the broker is not start under two master

### ISSUE THREAD

**Issue by kevin123de** [alibaba/RocketMQ#423]
i want build the 2m-nosalve,but the broker is not start,under is my configuration file
one machine ip is  192.168.1.121(hostname:rocketmq-nameserver1) other machine host is 192.168.1.122(hostname:rocketmq-nameserver2)  
two machine namesrv is started
121:broker-a.properties  
#所属集群名字 
brokerClusterName=rocketmq-cluster 
#broker名字，注意此处不同的配置文件填写的不一样 
brokerName=broker-a
#0 表示 Master，>0 表示 Slave 
brokerId=0 
#nameServer地址，分号分割
namesrvAddr=rocketmq-nameserver1:9876;rocketmq-nameserver2:9876 
122:broker-b.properties
#所属集群名字 
brokerClusterName=rocketmq-cluster 
#broker名字，注意此处不同的配置文件填写的不一样 
brokerName=broker-b 
#0 表示 Master，>0 表示 Slave 
brokerId=0 
#nameServer地址，分号分割
namesrvAddr=rocketmq-nameserver1:9876;rocketmq-nameserver2:9876 

When two machines namesrv has started, I through the following command start the broker in 121 and the broker in 122
nohup sh mqbroker -c /usr/local/rocketmq/conf/2m-noslave/broker-a.properties  >/dev/null 2>&1 & 
nohup sh mqbroker -c /usr/local/rocketmq/conf/2m-noslave/broker-b.properties  >/dev/null 2>&1 & 

but the broker not started,Error is as follows:
load config properties file OK, /usr/local/rocketmq/conf/2m-noslave/broker-a.properties
The Name Server Address[rocketmq-nameserver1:9876;rocketmq-nameserver2:9876 ] illegal, please set it as follows, "127.0.0.1:9876;192.168.0.1:9876"
but i assign the namesrv address 
nohup sh mqbroker  -n rocketmq-nameserver1 -c /usr/local/rocketmq/conf/2m-noslave/broker-a.properties  >/dev/null 2>&1 & 
nohup sh mqbroker  -n rocketmq-nameserver2 -c /usr/local/rocketmq/conf/2m-noslave/broker-b.properties  >/dev/null 2>&1 & 
the broker can start
So I Want to ask you the reason!
Thank you !

**Comment by wjh1234** [comment]
/etc/hosts 绑定namesrv的主机名

**Comment by kevin123de** [comment]
嗯，已经绑定过了
