### ISSUE TITLE
Why the consume queue's offset is sync from remote broker store in  CONSUME_FROM_TIMESTAMP mode? 

### ISSUE THREAD

**Issue by 1964405262** [alibaba/RocketMQ#424]
I am a rocketmq user in beibei and I  use the  V3.4.6 client rocketmq pushConsumer .
I fount that the consume queue's offset is sync from remote broker store in  CONSUME_FROM_TIMESTAMP mode . 
The code is like these in com.alibaba.rocketmq.client.impl.consumer.RebalancePushImpl#computePullFromWhere
method 

case CONSUME_FROM_TIMESTAMP: {
            long lastOffset = offsetStore.readOffset(mq, ReadOffsetType.READ_FROM_STORE);
            if (lastOffset >= 0) {
                result = lastOffset;
            }
            else if (-1 == lastOffset) {
                if (mq.getTopic().startsWith(MixAll.RETRY_GROUP_TOPIC_PREFIX)) {
                    try {
                        result = this.mQClientFactory.getMQAdminImpl().maxOffset(mq);
                    }
                    catch (MQClientException e) {
                        result = -1;
                    }
                }
                else {
                    try {
                        long timestamp =
                                UtilAll.parseDate(
                                    this.defaultMQPushConsumerImpl.getDefaultMQPushConsumer()
                                        .getConsumeTimestamp(), UtilAll.yyyyMMddHHmmss).getTime();
                        result = this.mQClientFactory.getMQAdminImpl().searchOffset(mq, timestamp);
                    }
                    catch (MQClientException e) {
                        result = -1;
                    }
                }
            }
            else {
                result = -1;
            }
            break;
        }

Why do we sync consume offset from remote broker first ?  In my opinion , the purpose of using CONSUME_FROM_TIMESTAMP mode is to consume back a little to make assure that the messages are not omitted. 

In addtition ,the timestamp is set on pushconsumer , can we set the timestamp on topics ? ?

**Comment by Jaskey** [comment]
No , the  purpose of CONSUME_FROM_XXX is only to affect the where to consume when this consume group is first starts.

Any time the consume offset exists in broker, that offset will be used to consumed from.

If you need to consume from in the other ways, use pull consumer .
