### ISSUE TITLE
Rocketmq3.5.8 how to configure the network access

### ISSUE THREAD

**Issue by zhechu** [alibaba/RocketMQ#426]
Rocketmq3.5.8 receives the message, and how to configure the network if only given a configuration case

**Comment by lizhanhui** [comment]
Not sure what you are asking for. Could you elaborate your issue?

**Comment by zhechu** [comment]
I want to outer net receives the message, But I don't know how to configure.

**Comment by zhechu** [comment]
My consumers and outer net, unlike producers network, only through the net.

**Comment by lizhanhui** [comment]
If I understand correctly, you want consumers capable of consuming messages from non-local networks. 
You have several options here to consider:

1.  Use public IP address for name servers and brokers. For security, you may enable SSL for two-way-authentication. This option is very easy to accomplish and you may have my fork as reference.

1.  Build a proxy and locate it in DMZ. This may involves some development work.

**Comment by zhechu** [comment]
Your understanding is correct.But I'm just a rookie.Thank you for your answer.
