### ISSUE TITLE
why response time is unstable when producer send message ?

### ISSUE THREAD

**Issue by StartFeng** [alibaba/RocketMQ#431]
why avg is small ,but max is much bigger?
avg response time: 2ms
max response time : hundreds
model : 2m-2s, sync persistent
putMessageDistributeTime: 4909739022(70.93309913575439%) 2010391787(29.044989823285444%) 355008(0.005128952383242559%) 299232(0.004323132660510292%) 465138(0.006720047586636577%) 397228(0.005738922777206923%) 0(0.0%)
![2016-12-06 8 12 43](https://cloud.githubusercontent.com/assets/18475842/20925196/62c413d6-bbf0-11e6-8d2f-8492ee1c3fa1.png)

**Comment by StartFeng** [comment]
more server info
![qq20161206-0](https://cloud.githubusercontent.com/assets/18475842/20925681/2d60f314-bbf3-11e6-8cfb-9018776135cb.png)

![2016-12-06 8 31 28](https://cloud.githubusercontent.com/assets/18475842/20925647/ff66fc06-bbf2-11e6-89b3-9f903eacb7b3.png)

**Comment by zhouxinyu** [comment]
Well, there are many latencies when access mem or page cache..

Let's look forward to the new version of Apache RocketMQ, it will be soon.

BTW, SSD is better~

**Comment by vongosling** [comment]
We polish here in the latest version 4.0.0. please update it once we released it.:-)
