### ISSUE TITLE
1.perm option description is wrong 2.fetchBrokerRuntimeStats putMessageDistributeTime is wrong

### ISSUE THREAD

**Issue by StyleTang** [alibaba/RocketMQ#434]
I think it is bug
1.   UpdateTopicPermSubCommand  perm option:   R and W is wrong
//        @see com.alibaba.rocketmq.common.constant.PermName
//        public static final int PERM_READ = 0x1 << 2; 4 read
//        public static final int PERM_WRITE = 0x1 << 1; 2 write
//opt = new Option("p", "perm", true, "set topic's permission(2|4|6), intro[2:R; 4:W; 6:RW]");

2. when we use mqAdmin fetchBrokerRuntimeStats ,the result of the putMessageDistributeTime is wrong .
putMessageDistributeTime will be changed by initPutMessageDistributeTime per PrintTPSInterval time,but putMessageTopicTimesTotal not,so we can't use putMessageTopicTimesTotal to calculate totalTimes,  each putMessageDistributeTime item should divide sum of putMessageDistributeTime to calculate the percentage.
@see  com.alibaba.rocketmq.store.StoreStatsService  printTps

Pull request:
https://github.com/alibaba/RocketMQ/pull/433

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
