### ISSUE TITLE
JDK 8 support with RocketMQ

### ISSUE THREAD

**Issue by netroby** [alibaba/RocketMQ#435]
Today i tried RocketMQ with JDK 8(OpenJDK8), seems the bin/play.sh and other shell scripts. relay on JDK < 8, because the GC and Perm size not available on JDK8. so may we tune shell scripts to support JDK 8?

**Comment by dongeforever** [comment]
Jdk 8 should be ok. please show the message in ns.log and bk.log under the running path

**Comment by netroby** [comment]
```

OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=320m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.

```

I means the warning message. may be we can detect the JDK version .then decide which options should be use or not.

**Comment by vongosling** [comment]
You can ignore it now, we will release the 4.0.0 in the near future. In this version. we will update our JVM bootstrap parameters :-)
