### ISSUE TITLE
some error log in pullMessageProcessor

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#437]
16-12-09 19:54:21 ERROR NettyServerNIOSelector_3_1 - transfer many message by pagecache failed, /10.9.193.91:42436
java.nio.channels.ClosedChannelException: null

`		FileRegion fileRegion = new ManyMessageTransfer(
		response.encodeHeader(getMessageResult.getBufferTotalSize()), getMessageResult);
		channel.writeAndFlush(fileRegion).addListener(new ChannelFutureListener() {
							@Override
							public void operationComplete(ChannelFuture future) throws Exception {
								getMessageResult.release();
								if (!future.isSuccess()) {
									log.error("transfer many message by pagecache failed, " + channel.remoteAddress(),
											future.cause());
								}
							}
						});
					} catch (Throwable e) {
						log.error("transfer many message by pagecache exception", e);
						getMessageResult.release();
					}`

**Comment by zhouxinyu** [comment]
Don't worry, may be the client channel just be closed unexpectedly.
