### ISSUE TITLE
why pagecache unmap need invoke sun.* cleaner() to clean the mmap file .

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#438]
> With regard to the "workaround", described in the JDC comments, of (ab)using
reflection in order to invoke a mapped buffer's cleaner object: This is highly
inadvisable, to put it mildly.  It is exceedingly dangerous to forcibly unmap a
mapped byte buffer that's visible to Java code.  Doing so risks both the
security and stability of the system.
Here is the RDer of jdk advice .

**Comment by Ah39** [comment]
invoke cleaner need check JDK version is not a good idea. And, how kafka deal with mmap file?? 
Can we use the way which is the same in Kafka

**Comment by zhouxinyu** [comment]
It depends. It's really dangerous If RocketMQ depends on GC to free direct byte buffer.

**Comment by dongeforever** [comment]
For Kafka,  use mmap only for Index File, and its delete logic: 
 /**
   * Delete this index file
   */
  def delete(): Boolean = {
    info("Deleting index " + _file.getAbsolutePath)
    if (Os.isWindows)
      CoreUtils.swallow(forceUnmap(mmap))
    _file.delete()
  }
For windows, it also invokes sun.* cleaner(). For Linux, it leaves it for GC

**Comment by Ah39** [comment]
@dongeforever  Do kafka log file used pagecache ?? and Do you know how kafka deal with log file ??

**Comment by dongeforever** [comment]
@Ah39 kafka's log file use FileChannel, which is different of mmap, but also take advantage of Page Cache. When produce messages, the log file just write normally.When consuming, it will use transferTo to avoid copying data from kernel to user space.

**Comment by zhouxinyu** [comment]
This issue should be closed, please feel free to open a new one if you still have questions.
