### ISSUE TITLE
Can  update server version to 3.5.8 and Client version is still is 3.4.6 ? How we update the rocketmq Version ??

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#439]
and how we restart the server dont affcet the service ???

**Comment by zhouxinyu** [comment]
Hi Ah39,

Client version behind Server is ok, but the newest is recommended.

Tips about restarting server: 

1. Restart name server in batches, and never stop all name servers.

2. Restart broker in batches, update brokerPermission to read-only and wait util the in/out TPS reduced to zero is recommended before stop a broker server.

Warning: If you use ordered message in your cluster, be carefully  and quickly..

**Comment by Ah39** [comment]
Thanks
