### ISSUE TITLE
MessageClientIDSetter  溢出

### ISSUE THREAD

**Issue by wangkang007** [alibaba/RocketMQ#443]
public static synchronized String createUniqID() {
            long current = System.currentTimeMillis();
            if (current >= nextStartTime) {
                setStartTime(current);
            }            
            buffer.position(0);          
            sb.setLength(basePos);            
            buffer.putInt( (int)(System.currentTimeMillis() - startTime) );
            buffer.putShort(counter++);
            sb.append(UtilAll.bytes2string(buffer.array()));
            return sb.toString();
    }
查看了下源码发现方便counter其实是short类型，问下counter++的肯定会造成溢出问题，一旦溢出，造成id重复的几率就变大了，基本靠时间戳来维持，这样会不会又问题

**Comment by zhouxinyu** [comment]
Hi,

RocketMQ generate msgId by `PID`, `IP`, `counter` and `timestamp`,  the client can't produce `Short.MAX_VALUE` messages at the same time. so don't worry about this.

**Comment by wangkang007** [comment]
hi 我这边还有疑问，如下代码
Short.java
public final class Short extends Number implements Comparable<Short> {

    /**
     * A constant holding the minimum value a {@code short} can
     * have, -2<sup>15</sup>.
     */
    public static final short   MIN_VALUE = -32768;

    /**
     * A constant holding the maximum value a {@code short} can
     * have, 2<sup>15</sup>-1.
     */
    public static final short   MAX_VALUE = 32767;
}
java 里面short最大值是32767，如你回复所说the client can't produce Short.MAX_VALUE messages ，也就是说一个client发送32767之后就会溢出，按照正常32767 条消息很快就会发送溢出的

**Comment by zhouxinyu** [comment]
Overflow is ok, the counter will start from zero again.

As for your concern, it does matter If and only if the client send `2^16-1(65535)` messages in one millisecond. Did you forget the timestamp factor ?

**Comment by vongosling** [comment]
please use english ;-)

**Comment by xiaoma20082008** [comment]
the processId is int,but in [this line](https://github.com/alibaba/RocketMQ/blob/master/rocketmq-common/src/main/java/com/alibaba/rocketmq/common/message/MessageClientIDSetter.java#L55-L55) the buffer position to 0 and then putInt,so if the processId > 32767,  will the processId lost the first and second byte ?
please see in the picture
![image](https://cloud.githubusercontent.com/assets/10076393/21361467/1887b00e-c71f-11e6-967a-9c4f355f6344.png)
