### ISSUE TITLE
After wipeWritePerm we clear the broker write permission, then how do we recover its  write permission?

### ISSUE THREAD

**Issue by tonychenz** [alibaba/RocketMQ#447]
It happens when i want to update the broker config but the config issue(messageDelayLevel) doesn't support dynamic changing. So i have to restart the broker.  but how do we recover its  write permission?

**Comment by zhouwei198732** [comment]
you can use such command “sh mqadmin  updatebrokerconfig -k brokerPermission -v 4(2:w; 4:r; 6: r+w) -b +your broker ip:port” in broker /bin directory

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
