### ISSUE TITLE
how to calculate message counts by producer and consumer everyday

### ISSUE THREAD

**Issue by adpoint** [alibaba/RocketMQ#448]
how to calculate message counts by producer and consumer everyday,do you have any tools available？

**Comment by vongosling** [comment]
You can look through our bin directory :-)

Just for your question, you can use sh ./mqadmin topicstatus -t yourTopic -n 10.125.3.140:9876 to calculate message counts(Max Offset-Min Offset)

You can also use sh ./mqadmin topicstatus -h ask for help

**Comment by adpoint** [comment]
I think this command "sh ./mqadmin topicstatus -t yourTopic -n yournameseveraddress" calculates all messages ,not everyday,yes?

**Comment by zhouxinyu** [comment]
Please refer to ~/logs/rocketmqlogs/stats.log for more statistics.
