### ISSUE TITLE
Client能否把Logger标准化？

### ISSUE THREAD

**Issue by Antergone** [alibaba/RocketMQ#449]
官方能否使用标准的slf4j-api？
接入系统如果想打log，自己去加实现就好了。
官方的包里面还有对日志系统的判断等等。。包括netty部分也是
而且包名也很诡异
``` com.aliyun.openservices.shade.com.alibaba.rocketmq.shade.io.netty.util.internal.logging ```
这到底是阿里云还是阿里巴巴？

**Comment by zhouxinyu** [comment]
Thanks for your suggestion.

BTW, Are you use Aliyun MQ ? if yes, you can open a issue at [here](https://selfservice.console.aliyun.com/ticket/scene?productCode=ons) for more help.
