### ISSUE TITLE
为何这里面 并没有告诉他人如何安装 使用 就好比RabbitMQ一样的文档

### ISSUE THREAD

**Issue by lihaoaini2008** [alibaba/RocketMQ#452]
为何这里面 并没有告诉他人如何安装 使用 就好比RabbitMQ一样的文档

**Comment by dongeforever** [comment]
please refer to:https://github.com/alibaba/RocketMQ/wiki/quick-start

Now we are refactoring our code and document, and you will get a fresh experience very soon

**Comment by zhouxinyu** [comment]
This issue should be closed, please feel free to open a new one if you still have questions.

**Comment by lihaoaini2008** [comment]
好吧。谢谢你的解答。

2016-12-16 23:16 GMT+08:00 Xinyu Zhou <notifications@github.com>:
