### ISSUE TITLE
About os.sh  vm.dirty_ratio set to 50 is  reasonable ??

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#453]
echo 'vm.dirty_background_ratio=50' >> /etc/sysctl.conf
echo 'vm.dirty_ratio=50' >> /etc/sysctl.conf
Here is mongodb vm tips 
![image](https://cloud.githubusercontent.com/assets/2367243/21285735/400066bc-c47c-11e6-92e8-91205c06872e.png)

# If your system continues to write to the action, then it is better to actually reduce this value, so you can cut the spike write operation to multiple write operations.

**Comment by zhouxinyu** [comment]
Hi,
os.sh is for reference only, there is no ideal tuning script that fits all situations, and just be careful with os.sh. 

Use and adjust it if and only if you understand all the items in os.sh.

**Comment by zhouxinyu** [comment]
For more detail about os.sh, reference [here](https://www.kernel.org/doc/Documentation/sysctl/vm.txt)

**Comment by lizhanhui** [comment]
Increasing the dirty_ratio is to ensure the system is less likely to enter a state where it needs to start blocking on writes.  The downside is that you are having more data at risk if you are using async_flush mode.

In terms of write spike, you have a handful of other parameters to tune, say dirty_background_ratio, dirty_writeback_centisecs, etc. All of them may change a spike write into multiple writes. 

As a matter of fact, there is no golden rule here without knowledge of your storage details. Using a raid with pretty large cache does requires a different set of params in contrast with a simple disk drive. Measure it, tweak it if unsatisfied.

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
