### ISSUE TITLE
[TIMEOUT_CLEAN_QUEUE]broker busy

### ISSUE THREAD

**Issue by baixiongfei** [alibaba/RocketMQ#455]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 200ms, size of queue: 32
如上错误日志，我在做压力测试的时候报的错误，怎么解决？有人碰到过吗？

**Comment by lizhanhui** [comment]
@baixiongfei Try the latest release [here](https://github.com/apache/incubator-rocketmq). Remember to configure transientStorePool properly.

**Comment by lizhanhui** [comment]
BTW, please raise issue using [Apache JIRA](https://issues.apache.org/jira/browse/ROCKETMQ/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)  next time.

**Comment by baixiongfei** [comment]
@lizhanhui OK,tks!

**Comment by vongosling** [comment]
if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq
