### ISSUE TITLE
Is the MessageClientId lost the first and the second byte of the processId?

### ISSUE THREAD

**Issue by xiaoma20082008** [alibaba/RocketMQ#456]
the processId is int,but in [this line](https://github.com/alibaba/RocketMQ/blob/master/rocketmq-common/src/main/java/com/alibaba/rocketmq/common/message/MessageClientIDSetter.java#L55-L55) the buffer position to 0 and then putInt,so if the processId > 32767,  will the processId lost the first and second byte ?
please see in the picture
![image](https://cloud.githubusercontent.com/assets/10076393/21361467/1887b00e-c71f-11e6-967a-9c4f355f6344.png)

**Comment by vongosling** [comment]
if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq
