### ISSUE TITLE
Ordering message deadlock problems ? 

### ISSUE THREAD

**Issue by 1964405262** [alibaba/RocketMQ#459]
I used Rocketmq (V3.4.6)'s ordering message  and seems like that we have deadlock problems .
The enviorment is list below: 
     2 brokernames  to supply HA
     1 master + 1 slave in one brokername 
     3 nameservers 
     topic with 6 queues in brokername1 and 6 queues in brokername2 
     consumergroup with 5 consumers  use messages to sync data to Elasticsearch 
     use push consumer to consume ordering messages.

On one night , the biz consumers said they can't consume messages anymore and feed back their Elasticsearch cluster is down for 10 minutes . During that 10 mins , they return 
ConsumeOrderlyStatus.SUSPEND_CURRENT_QUEUE_A_MOMENT in MessageListenerOrderly. 
After Elasticsearch recover, they cant' consume messages anymore and after restarting the consumers ,the ordering messages recovers.

I logged on to these consumers' machines and found that one consumer has log below:
---------------
[BUG]doRebalance, {}, remove unnecessary mq, {}, because pull is pause, so try to fixed it
doRebalance, {}, add a new mq, {}
---------------

These logs  repeated until the consumer restarted .

 we reviewed the code found the ProcessQueue's isPullExpired method 
------------
    public boolean isPullExpired() {
        boolean result = (System.currentTimeMillis() - this.lastPullTimestamp) > PullMaxIdleTime;
        return result;
    }
------------

But during that 10mins ,the consumer's heartbeat to broker is normal. Why the processqueue is 
pull expired ? In addition , it did not occur on other  consumers.

In RocketMQ V3.5.8 release, we found that the fix bugs include  "Fix ordering message deadlock problems" . Did you encounter  the deadlock problems before ? I reviewed the code and found that:
  in v3.5.8 , the RebalanceImpl#updateProcessQueueTableInRebalance method lock the messagequeue before dispatch pullrequest . 

 in v3.4.6 the RebalanceImpl#updateProcessQueueTableInRebalance  dispatch the pull request first and lazy lock the consume queue in ConsumeMessageOrderlyService#ConsumeRequest

The diffrence is the source  of deadlock problems ? Looking forward to your help  .

**Comment by Ah39** [comment]
Have the Consumer Thread Dump ？？

**Comment by 1964405262** [comment]
The SA restarted all consumers and we can not do get the thread dump using jstack .

**Comment by vongosling** [comment]
if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq
