### ISSUE TITLE
can't consume for a while, maybe blocked, 597688ms

### ISSUE THREAD

**Issue by ezhishui** [alibaba/RocketMQ#466]
你好，我用rocketmq的时候出现了这个错，topic中是有消息的，消费者也存活，但是消息就是不能被消费，
用这个命令查看的时候：sh mqadmin consumerStatus -n localhost:9876 -g SYNC_TOOL_brzhu
显示：
001  192.168.39.88@SYNC_TOOL                  V3_2_1               1483105100092/192.168.39.88@SYNC_TOOL
Same subscription in the same group of consumer
Rebalance OK
192.168.39.88@SYNC_TOOL MessageQueue [topic=IME_Biz_102_brzhu, brokerName=imebroker, queueId=0] can't consume for a while, maybe blocked, 597688ms

**Comment by vongosling** [comment]
please refer to https://github.com/alibaba/RocketMQ/issues/463
