### ISSUE TITLE
consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET) no use

### ISSUE THREAD

**Issue by loongshaw** [alibaba/RocketMQ#469]
i want to read data from last  offset, but  use consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET)  no effect

**Comment by vongosling** [comment]
please refer to https://github.com/alibaba/RocketMQ/issues/463
