### ISSUE TITLE
重启mq以后，导致消息重复下发消费问题？

### ISSUE THREAD

**Issue by shuhuiguo** [alibaba/RocketMQ#471]
版本：3.2.6 
您好,请教个问题，重启rocketmq，导致历史消息，重复下发，consumer重复消费，在日志中，出现了很多 WriteSocketService service has exception，请问到这个历史消息重复下发，有可能哪方面的原因呢？

**Comment by GiilianRose** [comment]
test

**Comment by zhouxinyu** [comment]
Hi, RocketMQ now has a new repo, please refer to [here](https://github.com/apache/incubator-rocketmq).
