### ISSUE TITLE
pull request 已经提交：rocketmq 在复杂网络环境下性能不佳的优化 #472

### ISSUE THREAD

**Issue by tain198127** [alibaba/RocketMQ#473]
由于 clientconfig 在获取本地 ip 时，ipv4获取最后一个 ip，致使在双网卡的环境中，如果最后一个 ip 对应的是外网 ip。那么可能会造成性能下降或者无法联通。虽然可以使用 setClientIP方法来解决这个问题。但是处理太过硬性。在集群环境中会对部署造成很大压力。

**Comment by zhouxinyu** [comment]
Hi, RocketMQ now has a new repo, please refer to [here](https://github.com/apache/incubator-rocketmq).
