### ISSUE TITLE
consumeMessageContext null

### ISSUE THREAD

**Issue by trj832000** [alibaba/RocketMQ#474]
ConsumeMessageConcurrentlyService.ConsumeRequest
ConsumeMessageContext consumeMessageContext = null;
 if (ConsumeMessageConcurrentlyService.this.defaultMQPushConsumerImpl.hasHook())
null 异常导致后续 updateOffset无法执行，offset 一直是0,是不是有什么配置不对？

**Comment by zhouxinyu** [comment]
Hi, this bug has been resolved in the newest version, and RocketMQ now has a new repo, please refer to [here](https://github.com/apache/incubator-rocketmq).
