### ISSUE TITLE
remove commitlog, messagequeue bug

### ISSUE THREAD

**Issue by liyinsheng** [alibaba/RocketMQ#475]
this.scheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                DefaultMessageStore.this.cleanFilesPeriodically();
            }
        }, 1000 * 60, this.messageStoreConfig.getCleanResourceInterval(), TimeUnit.MILLISECONDS);  
scheduleAtFixedRate function should change to scheduleAtFixedRate because  executions will commence after {@code initialDelay} then {@code initialDelay+period}, then {@code initialDelay + 2 * period}, and so on,that means executions delay time should more and more longer

**Comment by zhouxinyu** [comment]
Hi, RocketMQ now has a new repo, please refer to [here](https://github.com/apache/incubator-rocketmq).
