### ISSUE TITLE
about sdk(.net)

### ISSUE THREAD

**Issue by xLabel** [alibaba/RocketMQ#476]
Is Rocketmq provide .NET SDK ?

if yes , Please provide the download link ! 

thanks : )

![952711](https://cloud.githubusercontent.com/assets/3363613/23009542/88d17746-f451-11e6-945e-5902f8f00b81.jpg)

**Comment by twtiyb** [comment]
+1

**Comment by vongosling** [comment]
Sorry, .net SDK has only published in aliware MQ,https://help.aliyun.com/document_detail/29561.html?spm=5176.doc29546.6.587.Ue1SNT.
