### ISSUE TITLE
  How to get offsetMsgId？

### ISSUE THREAD

**Issue by soulCalibur** [alibaba/RocketMQ#481]
Org.apache.rocketmq.client.impl.producer.defaultmqproducerimpl
Function sendmessageintransaction
No copy sendresult setoffsetmsgid to transactionsendresult
I would like to manually call endtransaction to do the current transaction, but MsgId can not change the object's messageId!
How do I get to OffsetMsgId? Only extend the default handler class?

**Comment by vongosling** [comment]
Question can be send into our user mail list. http://rocketmq.incubator.apache.org/about/contact/
