### ISSUE TITLE
创建队列的时候，为什么要指定读对列和写队列的数量，设计目的是什么？

### ISSUE THREAD

**Issue by y123456yz** [alibaba/RocketMQ#483]
@vintagewang @vongosling 

通过分析代码：
    consumequeue/topic/目录下的数字编号，这些编号由写队列数决定。
    例如创建队列的时候设置读队列数为2，写队列为10，那么消息的索引信息会记录到consumequeue/topic/下面的0-9数字编号文件中，但是因为读队列数为2，那么也就只能消费0和1索引队列指定的消息可以被消费者消费，索引2-9队列上的消息就会消费不到？
   
    这种设计的目的是什么？消息投递进去后，却不能被消费，为什么要设计这个功能点？是基于什么原因？
    
    谢谢。

**Comment by vongosling** [comment]
Question can be send into our user mail list. http://rocketmq.incubator.apache.org/about/contact/
