### ISSUE TITLE
Topic auto create not working in new .NET SDK

### ISSUE THREAD

**Issue by santanu044** [alibaba/RocketMQ#493]
I am using the new version of .NET SDK for RocketMQ. But new topic is not creating automatically. Getting the exception :   
    Topic Route does not exist, Topic:topic1 exception:msg: No route info of this topic.

In BrokerConfig file, i have added autoCreateTopicEnable = true
and another strange thing, Using the old .NET SDK, topic auto creation is working.

some part of the log file of producer:
updateTopicRouteInfoFromNameServer with default[..\src\MQClientFactory.cpp:175]
INFO 18240 - updateTopicRouteInfoFromNameServer start:topic557[..\src\MQClientFactory.cpp:195]
WARN 18240 - tryToFindTopicPublishInfo null:topic557[..\src\MQClientFactory.cpp:181]
WARN 18240 - Retry many times, still failed[..\src\producer\DefaultMQProducer.cpp:578]
INFO 18240 - updateTopicRouteInfoFromNameServer start:topic557[..\src\MQClientFactory.cpp:195]
INFO 18240 - updateTopicRouteInfoFromNameServer with default[..\src\MQClientFactory.cpp:175]
INFO 18240 - updateTopicRouteInfoFromNameServer start:topic557[..\src\MQClientFactory.cpp:195]
WARN 18240 - tryToFindTopicPublishInfo null:topic557[..\src\MQClientFactory.cpp:181]
WARN 18240 - Retry many times, still failed[..\src\producer\DefaultMQProducer.cpp:578]
ERROR 18240 - msg: No route info of this topic, ,error:-1,in file <..\src\producer\DefaultMQProducer.cpp> line:581[..\src\producer\DefaultMQProducer.cpp:134]
FATAL 18240 - send msg failed of msg topic:topic557[..\src\ons-client\ProducerImpl.cpp:99]
INFO 18240 - input exception type:MQClientException with error:-1[..\src\ons-client\ProducerImpl.cpp:137]
WARN 18064 - sendheartbeat brokeradd is empty[..\src\MQClientFactory.cpp:669]
....end of log file

**Comment by vongosling** [comment]
Could you paste your problem in apache rocketmq's user mail list ?http://rocketmq.incubator.apache.org/about/contact/
