### ISSUE TITLE
rocketmq如何保证安全

### ISSUE THREAD

**Issue by yhnnhyyhnn** [alibaba/RocketMQ#499]
如果我的rocketmq服务器IP和端口被别人知道了,别人就能直接使用我的rocketmq了.请问如何保证安全?

**Comment by haoshijing** [comment]
首先你这个应该部署在内网，然后只有跳板机才能上吧

**Comment by Lihuanghe** [comment]
别把安全的功能放在mq上实现，它只是个mq
