### ISSUE TITLE
(疑问)如何扩容consumer

### ISSUE THREAD

**Issue by brucechan0921** [alibaba/RocketMQ#5]
本来的设想：

一台机器，一个consumer group消费多个topic。某天通过扩容的方式将某1个关键topic分离出来（或者隔离应用消费各自的topic），继续使用相同的consumer group，消费这个分离的topic。这样就可以动态扩容缩容了。

实际情况：

订阅信息是按照consumer group来区分的，跟topic无关。 所以2个应用，相同的consumer group，认为是对等的，而不关心 具体订阅的topic。 这样可能出现的问题是：队列被均衡了，但是却没有被实际消费。

疑问：
遇到类似这种情况，应该如何规划扩容，毕竟基于offset是最准确的。 目前想到的方案，每个topic对应1个consumer group，将consumer group作为扩容单元

**Comment by yanfeipeng** [comment]
还有一种情况也会出现此问题，同一个consume group下不同consumer 对于同一个topic,订阅的tag不一致时也会产生这种消费消息丢失的情况。
按照@vintagewang 换group的解决方式，感觉会导致，group不断膨胀，不优雅难维护。
致于为什么会出现以上说的情况呢？
不一定是代码的问题，可能是出现在布署时，因为机器不一定是全部一起关闭或重启的。
有点纠结。

**Comment by blueszhangsh** [comment]
是不是用法不对？同一个consumerGroup去订阅不同的topic本来就有悖于consumer group的概念本身。如果有这个需求，是不是去开两个consumerGroup去消费不同的topic，或者用一个consumerGroup并且group的所有consumer都订阅两个topic比较合理？

**Comment by reallax** [comment]
同一group下两个consumer订阅不同topic，会导致这些consumer漏掉订阅的消息，在release-4.0.1-incubating中依然存在。
当然按照上面所说，定义不同的group来消费不同的topic可以解决此问题，当然前提是大量的group不会影响性能，这个我不能确定。
此外，说一下我也有同样需求的场景。比如说一个group订阅多个Topic，但是某个TopicX的消息量特别大，而其余Topic的消息都比较小，我只想调整TopicX的消费线程数量，但事实上我调整增加的线程有效范围是该group下订阅的全部Topic的全部queue，而不是仅作用于TopicX。
为了解决此问题，我考虑一个group仅消费一个Topic（便于调整消费线程数）。不知道这样有没有什么副作用，或者有没有更好的建议。
