### ISSUE TITLE
FAQ: 发送消息尝试多次失败

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#50]
## 可能产生的原因
* Broker向Producer返回了错误码，具体错误形式参见这个异常对应的嵌套异常

	或

* Broker宕机后，Producer还没有从Name Server拿到最新的Broker列表，会短暂报此异常

	或

* Producer向Broker发送消息超时

## 解决方案一（推荐阿里内部用户使用）
阿里内部一般不会报此错误，如果报此错误，可能服务器正在重启维护或者服务器压力过大产生超时现象。

如果是短暂报几个这样的异常，属于正常现象。

## 解决方案二（推荐开源社区用户使用）
请部署多个Master，一般不会报此异常。

**Comment by sunguilin** [comment]
单机版运行贵公司的demo就出现此异常了。

rmbp 13顶配加16GB内存。

**Comment by RainboW-SYF** [comment]
nameServer+ Broker 部署在同一台机器上 且 机器配置为2核2G 就报这个错

**Comment by logertower** [comment]
nameServer + broker 部署在一台windows电脑上
本机发送拉取消息正常
另一台电脑访问报错com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [49]ms, Topic: MyMQTest, BrokersSent: [DESKTOP-IV7LKRL, null, null]

**Comment by cfmui** [comment]
单点部署的一个broker，一个nameserver，执行os.sh之前效率很高也没报错，执行了os.sh之后，再进行压测就出现com.alibaba.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel，是执行了os.sh后就必须要多个broker作为master运行吗？

**Comment by rlliu** [comment]
10:52:07,674 ERROR [RocketMQSupport] Send [1] times, still failed, cost [3003]ms, Topic: autoPolicy, BrokersSent: [broker-a, null, null]
See https://github.com/alibaba/RocketMQ/issues/50 for further details.null


producer 发送方一直播这个错误是为什么？

**Comment by zmatsh** [comment]
https://firsh.me/2017/07/19/rocketmq-p-c/ 这里面已经介绍了，其实错误很简单就是少启动了一个bar
