### ISSUE TITLE
获取集群问题

### ISSUE THREAD

**Issue by chencai186** [alibaba/rocketmq#501]
请问为什么examineBrokerClusterInfo获取不到所有集群？一次请求只能随机获取到其中的某一个集群

**Comment by xyzmonday** [comment]
我在搭建2m-noslave集群的时候，启动namesrv正常，但是启动broker时却报com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <rocketmq-nameserver2:9876>

我的配置是：
#所属集群名字
brokerClusterName=rocketmq-cluster
#broker名字，注意此处不同的配置文件填写的不一样
brokerName=broker-a
#0 表示 Master， >0 表示 Slave
brokerId=0
#nameServer地址，分号分割
namesrvAddr=192.168.1.105:9876;192.168.1.107:9876
brokerIP1=192.168.232.23
#在发送消息时，自动创建服务器不存在的topic，默认创建的队列数
defaultTopicQueueNums=4
#是否允许 Broker 自动创建Topic，建议线下开启，线上关闭
autoCreateTopicEnable=true
#是否允许 Broker 自动创建订阅组，建议线下开启，线上关闭
autoCreateSubscriptionGroup=true
#Broker 对外服务的监听端口
listenPort=10911
#删除文件时间点，默认凌晨 0点
deleteWhen=00
#文件保留时间，默认 48 小时
fileReservedTime=120
#commitLog每个文件的大小默认1G
mapedFileSizeCommitLog=1073741824
#ConsumeQueue每个文件默认存30W条，根据业务情况调整
mapedFileSizeConsumeQueue=300000

**Comment by vongosling** [comment]
请参考问问题 #108
