### ISSUE TITLE
问一个关于c++客户端消息回溯的问题

### ISSUE THREAD

**Issue by peacedog123** [alibaba/rocketmq#504]
项目中有一个需要，是C++利用DefaultPushConsumer启动消费以后，需要在周期性的某个时候（比如每天中午），把消息消费的offset重置为当天的开始再重新消费，看了下RocketMQ的文档好像提供这个消息回溯的功能，但是在c++SDK里却找不到相应信息，还请指教，谢谢！

**Comment by vongosling** [comment]
请参考问问题 #108
