### ISSUE TITLE
not understand for whether instances of a group can subcribe more topics

### ISSUE THREAD

**Issue by danceyoung** [alibaba/rocketmq#506]
through official websit https://rocketmq.apache.org/docs/core-concept/
<img width="892" alt="wx20180109-174423 2x" src="https://user-images.githubusercontent.com/1777025/34714632-045696d4-f565-11e7-95b3-e8d8874910e8.png">

what is difference bettween the points of drawing red lines

**Comment by vongosling** [comment]
请参考问问题 #108
