### ISSUE TITLE
rocket c++ 版本广播模式不能够正常工作

### ISSUE THREAD

**Issue by shuihan0555** [alibaba/rocketmq#507]
rocket c++ 版本广播模式不能够正常工作, 被注册的消费者对象不能够被回调. 
经查, 代码在OffsetStore 的构造函数主目录和子目录没有追加目录分隔符('/'). 
另外, 在该文件的load函数, 因为是第一次广播消费,所有不会存在目录,也不会存在offsets.Json文件. 导致被注册的消费者对象不能够被回调.

请问广播模式下,本地的offsets.Json文件是什么样格式文件, 可否给一个样板, 谢谢

**Comment by vongosling** [comment]
请参考问问题 https://github.com/alibaba/rocketmq/issues/108

**Comment by shuihan0555** [comment]
是源码版本的问题, 下载最新源码运行就正常了,谢谢!!
