### ISSUE TITLE
消息浏览问题

### ISSUE THREAD

**Issue by airkira** [alibaba/rocketmq#509]
刚开始使用RocketMQ，用的3.2.6版本，不知道有没有浏览消息，还有复制导出消息的接口呢，我们想在rocketmq堆积的消息中查找到指定业务关键字的消息，可是3.2.6版本只提供时间，消息ID和key的查询，不是很好用

**Comment by vongosling** [comment]
please refer to https://github.com/alibaba/rocketmq/issues/108
