### ISSUE TITLE
Broker消息数量统计问题

### ISSUE THREAD

**Issue by jerryldh** [alibaba/RocketMQ#52]
在StatsItem类中
// 具体的统计值
private final AtomicLong value = new AtomicLong(0);
针对某一类消息进行统计，比如
某topic@group对应的get的数量
如果这一数量超过long的最大值是不是会溢出

**Comment by vintagewang** [comment]
long对于业务来说 就是天文数字， 怎么可能超过呢 ？ 有生之年是不会超过的。
