### ISSUE TITLE
RMQ如何利用多块磁盘？

### ISSUE THREAD

**Issue by jwwang3** [alibaba/RocketMQ#55]
现有多块盘挂在不同目录下，RMQ-3.2.2应该如何配置才能使用多块盘？
/disk1
/disk2
目前我的配置为：
storePathRootDir=/home/disk1/store
storePathCommitLog=/home/disk1/store/commitlog

**Comment by vintagewang** [comment]
几种方式
1、启动多个实例，每个实例配置到不同的磁盘

2、使用raid卡来帮助软件做这件事情。
