### ISSUE TITLE
使用RocketMQ进行跨地域数据收集

### ISSUE THREAD

**Issue by zhenchuan** [alibaba/RocketMQ#57]
目前我们使用RocketMQ作为数据收集的pipeline .

由于业务的关系,我们的一些服务器部署在欧美,这个时候无法实时收集了(不稳定,传输慢)...
目前我们的办法是在前端服务器写入日志(按分钟)后,每隔N分钟通过async的方式批量同步一次,然后再写入到rocketmq. 

我不太确定这是不是最好的方案.欢迎交流...

这里我写了个小工具,来辅助做这件事情,希望对后面遇到类似问题的人有用.
https://github.com/zhenchuan/filewatcher

**Comment by vintagewang** [comment]
跨地域是个问题，目前内部用的是单独的组件来做路由的。

**Comment by songlin411** [comment]
请问跨地域，是什么概率，是一个集群，发到另外一个集群吗，还是一个地区，发到另外一个地区？例如中国发美国？






在 2015-01-25 20:44:35，"Xiaorui Wang" <notifications@github.com> 写道：


跨地域是个问题，目前内部用的是单独的组件来做路由的。

**Comment by zhenchuan** [comment]
@vintagewang 是跨国家么?
