### ISSUE TITLE
FAQ: async_flush和async_master模式 master-slave消息同步问题

### ISSUE THREAD

**Issue by linckham** [alibaba/RocketMQ#62]
hi,shijia
   async_flush和async_master模式，似乎存在master-slave无法同步消息的问题。
   从commitLog代码来看，一旦配置了这个模式，master-slave的消息同步存在问题。

**Comment by linckham** [comment]
// 同步双写
        if (BrokerRole.SYNC_MASTER == this.defaultMessageStore.getMessageStoreConfig().getBrokerRole()) {
            HAService service = this.defaultMessageStore.getHaService();
            if (msg.isWaitStoreMsgOK()) {
                // 判断是否要等待
                if (service.isSlaveOK(result.getWroteOffset() + result.getWroteBytes())) {
                    if (null == request) {
                        request = new GroupCommitRequest(result.getWroteOffset() + result.getWroteBytes());
                    }
                    service.putRequest(request);
只有SYNC_MASTER模式下，才会调用haService.putReques()，那么在AYNC_MASTER,模式下，master-slave是如何同步的？

**Comment by vintagewang** [comment]
service.putRequest(request);


这行代码是为了通知Master开始同步消息到Slave， 然后等待同步结果。


那么如果异步复制，则发送消息线程不用这个过程，master本身就是实时的向slave同步数据的。

**Comment by linckham** [comment]
shijia,好
  master实时向slave同步数据，相关代码在哪个模块。
  谢谢

**Comment by linckham** [comment]
@vintagewang master实时向slave同步数据，相关代码在哪个模块。

**Comment by linckham** [comment]
@vintagewang  Master与Slave的数据同步，是不是在HAConnection和HAService两个类里面？

**Comment by vintagewang** [comment]
对的
