### ISSUE TITLE
事务回查问题

### ISSUE THREAD

**Issue by ccvcd** [alibaba/RocketMQ#65]
事务回查机制中，Broker2Client类中的checkProducerTransactionState方法没有任何地方调用，麻烦问问怎么实现事务回查的？3.2.2版本

**Comment by vintagewang** [comment]
这块逻辑暂时没有开源，请期待吧，

或者欢迎您投简历到我司，内部有源码

**Comment by yanfeipeng** [comment]
请问这个功能有具体的开源计划吗？

**Comment by vintagewang** [comment]
这块逻辑暂时没有开源，请期待吧，

或者欢迎您投简历到我司，内部有源码

**Comment by wangrongruo** [comment]
没有事务回查的化,请问有相应的解决方案吗?这样与kafka相比较,竞争力太小了.

**Comment by yanfeipeng** [comment]
@wangrongruo 更低的版本rocketmq 3.1.x版本是还有相关的功能，你应该也可以在网上还能搜索到相应的代码，我曾经把它补全到当前的版本，能够正常使用，但具体会不会引入新的BUG，不是很清楚，因为使用的项目规模上不去，同时也被close了。
