### ISSUE TITLE
请问rocketmq有android端的client吗？

### ISSUE THREAD

**Issue by wangke8476** [alibaba/RocketMQ#67]
想用rocketmq在andorid端和服务器端相互发送和接收消息，请问在android端怎样引入rocketmq?

**Comment by vintagewang** [comment]
移动端使用rocketmq  sdk  会比较耗电， 不推荐在移动端使用。

**Comment by wangke8476** [comment]
在移动端做即时消息推送的话，你们一般用什么框架呢，netty可以吗？

**Comment by vintagewang** [comment]
没有框架， 一般这类系统都单独研发的。

**Comment by wangke8476** [comment]
移动端和netty通信，然后用netty向rocketmq发送和接收消息？
