### ISSUE TITLE
BrokerStartup中未关闭-c参数的fd

### ISSUE THREAD

**Issue by brucechan0921** [alibaba/RocketMQ#68]
-c参数指定的file没有关闭fd

            // 指定配置文件
            if (commandLine.hasOption('c')) {
                String file = commandLine.getOptionValue('c');
                if (file != null) {
                    InputStream in = new BufferedInputStream(new FileInputStream(file));
                    Properties properties = new Properties();
                    properties.load(in);
                    MixAll.properties2Object(properties, brokerConfig);
                    MixAll.properties2Object(properties, nettyServerConfig);
                    MixAll.properties2Object(properties, nettyClientConfig);
                    MixAll.properties2Object(properties, messageStoreConfig);

                    brokerConfig.setBrokerConfigPath(file);

                    System.out.println("load config properties file OK, " + file);
                }
            }

**Comment by vintagewang** [comment]
非常感谢， 下个版本我们修复掉。

**Comment by vintagewang** [comment]
已经修复
