### ISSUE TITLE
Broker处理send message请求时未考虑死信消息处理

### ISSUE THREAD

**Issue by guoyu9** [alibaba/RocketMQ#7]
https://github.com/alibaba/RocketMQ/blob/develop/rocketmq-broker/src/main/java/com/alibaba/rocketmq/broker/processor/SendMessageProcessor.java

如果消费者处理消息失败，并且向原始broker执行sendback失败，会执行消息send操作，所以SendMessageProcessor.java的sendMessage方法只有对resumeTimes的处理，如下
msgInner.setReconsumeTimes(requestHeader.getReconsumeTimes() == null ? 0 : requestHeader
            .getReconsumeTimes());

没有判断死信消息的处理（resumeTimes超过最大重试次数限制）

**Comment by bwzhang2011** [comment]
any update with such issue ?

**Comment by vongosling** [comment]
please using our new 3.4.6 version to validate
