### ISSUE TITLE
版本同步更新问题：什么时候会将3.2.5版本的源码开放出来？

### ISSUE THREAD

**Issue by vancepym** [alibaba/RocketMQ#74]
说好的“RocketMQ开源社区版本与内部保持同步更新”，说话能算数吗？

通过 http://mvnrepository.com/artifact/com.alibaba.rocketmq 查到当前最新版本3.2.5，发布于2015年2月9日，但github上看不到该版本的源码呀？

**Comment by vintagewang** [comment]
开源新版本需要走流程，有时间差正常，稍安勿躁。
