### ISSUE TITLE
AbstractSendMessageProcessor类中文乱码

### ISSUE THREAD

**Issue by juaby** [alibaba/RocketMQ#80]
RocketMQ 3.2.6

/**
 * 澶勭悊瀹㈡埛绔彂閫佹秷鎭殑璇锋眰
 * 
 * @author shijia.wxr<vintage.wang@gmail.com>
 * @since 2013-7-26
 */
public abstract class AbstractSendMessageProcessor implements NettyRequestProcessor {
......

**Comment by vintagewang** [comment]
下个版本修复。
