### ISSUE TITLE
log频繁报：WriteSocketService - findMapedFileByOffset offset not matched, request Offset

### ISSUE THREAD

**Issue by gitriver** [alibaba/RocketMQ#81]
集群情况：
3个namesrv,  4台broker 分别为是broker-a, broker-a-s,broker-b, broker-b-s

发现就broker-a频繁报如下错误，其他三台不报或很少报

broker-a	
#BID	#Addr	#Version	#InTPS	#OutTPS	#InTotalYest	#OutTotalYest	#InTotalToday	#OutTotalToday
0	192.168.0.35:10911	V3_1_8	0.0	0.0	11989	11803	4232	4178
1	192.168.0.36:10911	V3_1_8	0.0	0.0	0	0	0	0
broker-b	
#BID	#Addr	#Version	#InTPS	#OutTPS	#InTotalYest	#OutTotalYest	#InTotalToday	#OutTotalToday
0	192.168.0.37:10911	V3_1_8	0.49995000499950004	0.49995000499950004	11991	11810	4259	4188
1	192.168.0.38:10911	V3_1_8	0.0	0.0	0	0	0	0

用的MQ版本3.1.8

storeerror.log 日志频繁的报如下错误:
2015-04-02 10:34:06 WARN WriteSocketService - findMapedFileByOffset offset not matched, request Offset: 6318636453, index: -1, mapedFileSize: 1073741824, mapedFiles count: 1, StackTrace: 
        java.lang.Thread.getStackTrace(Thread.java:1589)
        com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:59)
        com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:156)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:150)
        com.alibaba.rocketmq.store.DefaultMessageStore.getCommitLogData(DefaultMessageStore.java:793)
        com.alibaba.rocketmq.store.ha.HAConnection$WriteSocketService.run(HAConnection.java:334)
        java.lang.Thread.run(Thread.java:745)
2015-04-02 10:34:06 WARN WriteSocketService - findMapedFileByOffset offset not matched, request Offset: 6318636453, index: -1, mapedFileSize: 1073741824, mapedFiles count: 1, StackTrace: 
        java.lang.Thread.getStackTrace(Thread.java:1589)
        com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:59)
        com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:156)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:150)
        com.alibaba.rocketmq.store.DefaultMessageStore.getCommitLogData(DefaultMessageStore.java:793)
        com.alibaba.rocketmq.store.ha.HAConnection$WriteSocketService.run(HAConnection.java:334)
        java.lang.Thread.run(Thread.java:745)

**Comment by vintagewang** [comment]
升级到最新版本试下   v3.2.6

**Comment by pisces2012** [comment]
我也碰见了，我是最新版本
2015-04-02 10:54:06 WARN ReputMessageService - findMapedFileByOffset offset not matched, request Offset
: 4294967296, index: 4, mapedFileSize: 1073741824, mapedFiles count: 4, StackTrace: 
        java.lang.Thread.getStackTrace(Thread.java:1589)
        com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
        com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:148)
        com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:142)
        com.alibaba.rocketmq.store.DefaultMessageStore$ReputMessageService.doReput(DefaultMessageStore.
java:1730)
        com.alibaba.rocketmq.store.DefaultMessageStore$ReputMessageService.run(DefaultMessageStore.java
:1785)
        java.lang.Thread.run(Thread.java:745)

**Comment by gitriver** [comment]
现在解决没有呀？

**Comment by vintagewang** [comment]
@pisces2012 用的什么版本， 服务器

**Comment by pisces2012** [comment]
虚拟机 SUSE
JDK 1.7.0_75
MQ版本3.2.6

**Comment by gitriver** [comment]
先删除 slave的 store目录 ，然后重启测试，仍然有问题呀

**Comment by gitriver** [comment]
系统用的是CENTOS 6.4

**Comment by leo27lijiang** [comment]
这个问题我也遇到过，V3.1.0版本，也是主从模式，从节点重启后会狂报 findMapedFileByOffset offset not matched, request Offset，刷过好几天。后面我把从节点直接去掉了。。。

**Comment by vintagewang** [comment]
已经确认，这个日志是主从复制过程中多余的打，新版本会修复此问题。 感谢大家的关注。

**Comment by leopardoooo** [comment]
我也有这个问题，我版本是3.2.6, 而且我没有使用主从，我仅仅使用4m-noslave, 大概30秒一次

**Comment by OlinaRuan** [comment]
这个方法里： MapedFileQueue#findMappedFileByOffset(final long offset, final boolean returnFirstOnNotFound)
if (index < 0 || index >= this.mappedFiles.size()) 
改成
 if (!returnFirstOnNotFound && (index < 0 || index >= this.mappedFiles.size())) 
试试。

**Comment by yaoguangluo** [comment]
有个QQ群不错,服务器高手都在里面 id是 167461951

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions

**Comment by huozhicheng** [comment]
` WARN WriteSocketService - findMapedFileByOffset offset not matched, request Offset: 39566592813, index: -41, mapedFileSize: 1073741824, mapedFiles count: 3, StackTrace: 
	java.lang.Thread.getStackTrace(Thread.java:1589)
	com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
	com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
	com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:148)
	com.alibaba.rocketmq.store.CommitLog.getData(CommitLog.java:142)
	com.alibaba.rocketmq.store.DefaultMessageStore.getCommitLogData(DefaultMessageStore.java:818)
	com.alibaba.rocketmq.store.ha.HAConnection$WriteSocketService.run(HAConnection.java:334)
	java.lang.Thread.run(Thread.java:745)`

3.2.6 版本 1master1slave，master频繁报这个警告，请问这个bug是在哪个版本开始修复的呢？3.4.6吗？
