### ISSUE TITLE
顺序消费消息异常堵塞问题

### ISSUE THREAD

**Issue by ccvcd** [alibaba/RocketMQ#82]
应用有一个顺序消费的topic队列，进行数据交换，发现某个消息的数据结构异常了，此消息不能正常消费，导致整个队列就堵塞在此消息上
就想根据msgId删除这个消息，使其他消息进行消费，查看管理工具命令，发现没有。
出现这种情况，大家都是如何处理的.

**Comment by vintagewang** [comment]
应用选择跳过吧。  顺序消息的语义就是排队，前面的消息不消费成功，如果跳过消费就会可能乱序。

**Comment by ccvcd** [comment]
应用可以选择跳过，那样每个消费应用就需要考虑异常的原因，系统级异常（数据库连接异常等）还是应用级异常（数据格式异常），如果能够确认忽略消息，选择用管理工具删除消息还是比较简单，毕竟应用级的异常必定是不能被消费的。
还有一种情况就是，消息的重复发送，业务消费消息时，会报异常（业务判断已处理或数据库主键冲突等），此时也就需要忽略此条消息

**Comment by vintagewang** [comment]
顺序消费方式异常分两种
1、系统级异常
2、应用消费异常，如数据格式错误，卡号被冻结。

第一种异常需要重试

第二种异常需要跳过。


应用做下异常捕获，识别出这种异常， 跳过即可。


为什么rocketmq不能做消息删除？
1、主要原因在于数据存储在文件，不具备kv存储系统的删除能力。


如果选择非顺序消费， 那么就不存在此问题，消费失败， 会自动跳过。 服务器重试。

**Comment by vintagewang** [comment]
另外假设支持这种功能，这个删除的动作也需要人工来干预，给运维的人增加了工作量， 还不如应用更智能，自动识别出这种情况， 做跳过处理。
