### ISSUE TITLE
广播消费时rocketmq_offsets.json乱码，readLocalOffset Exception, maybe fastjson version too low

### ISSUE THREAD

**Issue by leopardoooo** [alibaba/RocketMQ#83]
启动应用开始消费的时候会抛出MQClientException异常readLocalOffset Exception, maybe fastjson version too low。检查了下本地的.rocketmq_offsets.json 和 bak均是乱码，这是什么原因造成的？请教作者。我本地是windows 7 64bits的环境！

**Comment by vintagewang** [comment]
请升级客户端到 3.2.6看下，是否还报错
