### ISSUE TITLE
大数据包报错:transfer many message by pagecache failed

### ISSUE THREAD

**Issue by TGrape** [alibaba/RocketMQ#87]
设置系统属性com.rocketmq.remoting.frameMaxLength,大于默认8388608；
消费的时候报错：transfer many message by pagecache failed，这是什么原因呢？

**Comment by vintagewang** [comment]
上下文是什么，为什么要设置这个参数，设置的是否正确

**Comment by vintagewang** [comment]
上下文是什么，为什么要设置这个参数，设置的是否正确

**Comment by vintagewang** [comment]
上下文是什么，为什么要设置这个参数，设置的是否正确

**Comment by TGrape** [comment]
因为数据包太大，报错frame超出8388608；

**Comment by vintagewang** [comment]
消息体超过8M？

**Comment by TGrape** [comment]
是的，支持吗？

**Comment by vintagewang** [comment]
不支持。

**Comment by vintagewang** [comment]
推荐你用FTP哦

**Comment by TGrape** [comment]
超过8M，写入队列没有报错，消费的时候报错？

**Comment by vintagewang** [comment]
MQ不是用来传输大数据的， 术业有专攻，特定的产品做特定的事情吧。

**Comment by TGrape** [comment]
好的，谢谢。
还想问一下，通过设置别的属性能够支持吗？

**Comment by vintagewang** [comment]
你可以尝试下，不过不建议这么用。 mq里的网络传输没有对大的网络包做优化， 风险很大。

**Comment by TGrape** [comment]
有另外一个小疑问，跟这个没关系，就是在队列里有一定量数据之后，启动多个Consumer消费（多个线程）的时候，会重复获取数据包；但是，先启动Consumer，再写入数据包到队列，就不会重复消费，这怎么说？

**Comment by archerstarlee** [comment]
其实我也有这个疑问, 在rocketmq与storm对接的时候, spout只能设置为1个线程, 然后写入队列中缓冲. 这样其实不太好,
有丢数据的风险.

2015-04-10 23:29 GMT+08:00 TGrape <notifications@github.com>:
