### ISSUE TITLE
HA主机备机之间无消息复制时候，会不停断连重连

### ISSUE THREAD

**Issue by njchenkejin** [alibaba/RocketMQ#9]
测试主备功能时候发现，主备之间无消息复制的时候，会断连重连
定位是主备双向心跳引起的，主机发现心跳超时会主动断掉链路。
原因是：
       备机的客户端链路只用一个变量lastWriteTimestamp来记录时间，这个时间应该是来记录写数据时间，目前代码中链路读数据(主机的心跳消息)的时候，也更新了此时间，会导致备机有可能不主动发心跳消息给主机，导致主机发现心跳超时会主动断掉链路。
       建议增加一个变量lastReadTimestamp来把读写时间分开记录。

**Comment by vintagewang** [comment]
这是个问题，但是不影响功能与性能。修复优先级低
