### ISSUE TITLE
在v3.2.6中PushConsumer的setConsumeFromWhere不起作用

### ISSUE THREAD

**Issue by sk163** [alibaba/RocketMQ#91]
rocketmq的版本：V3.2.6
部署方式双master，双nameServer

重现方式：
1、先启动生产者发送5条消息，进TestTopic
2、再启动DefaultMQPushConsumer，GroupName="C1"
设置
consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET);
在之前没有订阅关系的时候，把之前发的5条消息给处理了。
3、更改GroupName="C2"，又把之前发的5条消息给处理了。

不知为何ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET不起作用？还是哪块没有设置对？

CONSUME_FROM_TIMESTAMP这个参数也不起效果，希望您能给予一些帮助，多谢~

**Comment by Liubey** [comment]
都换了groupname了肯定还得消费一次持久化的消息

**Comment by sk163** [comment]
谢谢Liubey，那CONSUME_FROM_LAST_OFFSET这个参数起到什么作用呢？
