### ISSUE TITLE
No route info of this topic

### ISSUE THREAD

**Issue by xiarilian12** [alibaba/RocketMQ#94]
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic,
通常什么情况下会出现这个异常

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/44

**Comment by vongosling** [comment]
鼓励代码方式了解，拉下来，搜索关键字‘No route info of this topic’，^_^。也可参看之前文档，https://github.com/alibaba/RocketMQ/issues/44
