### ISSUE TITLE
Broker启动失败

### ISSUE THREAD

**Issue by jwwang3** [alibaba/RocketMQ#97]
1. nameserver 启动正常，端口已经提供服务
2. 使用nohup ./mqbroker -n  xxx:9876 -c ../conf/broker.properties  &命令启动broker，发现无法启动。
查看broker.log,
![qq 20150507175606](https://cloud.githubusercontent.com/assets/5888301/7512886/a4aa3efa-f4e2-11e4-93d6-062e771ce6e1.png)

查看remoting.log,
![qq 20150507175621](https://cloud.githubusercontent.com/assets/5888301/7512897/b5a77a9c-f4e2-11e4-9f9b-209f355c642f.png)

无其他异常，该问题现在仍没有定位，不知道大家有没有遇到过？

**Comment by lizhanhui** [comment]
异常提示很明显啊， 连接name server连接不上去.
